### ISSUE TITLE
[UI] Accounting

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#102]
- [x] 日記帳頁面
- [x] 日記帳清單檢視頁面
- [x] 傳票檢視頁面

可參考WF
#59

**Comment by StrawHo** [comment]
LINK:
https://www.figma.com/file/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?type=design&node-id=4%3A369&mode=design&t=Zk7I6vtGMmzodS3M-1

花費時間約6hr10min

剩餘部分為轉移欄位、記帳儲存區域與確認畫面，預計還需要2hr
