### ISSUE TITLE
Login page sign-in & up with invitation Code

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#1028]
Login page login with invitation Code

Url example: /users/login?invitation=code

pass query to sign-in and sign-up

**Comment by arealclimber** [comment]
- http://localhost:3000/en/users/login?invitation=111bd*&action=register
- http://localhost:3000/en/users/login?invitation=222!@%^&action=login


https://github.com/CAFECA-IO/iSunFA/assets/20677913/b44a67e6-53fe-497c-b497-f393059c1bcc

**Comment by arealclimber** [comment]
took 2 hrs
done

**Comment by arealclimber** [comment]
備註：單一 query 內容不能有 #, &
