### ISSUE TITLE
[UI] Salary

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#103]
- [x] Employees List
- [x] Salary Bookkeeping

可參考
#58

**Comment by StrawHo** [comment]
LINK:
https://www.figma.com/file/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?type=design&node-id=384%3A119430&mode=design&t=OHbUUaUtnjoW1UQ0-1

花費時間約7hr
