### ISSUE TITLE
i18n JSON - general components

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1030]
- 所有 modal 的多語系
- mobile navbar 裡面所有選項的多語系
- desktop navbar 的 App menu 多語系

**Comment by jing12345678910** [comment]
took 3 hrs

- 所有 modal 的多語系
- mobile navbar 裡面所有選項的多語系
- desktop navbar 的 App menu 多語系
- 上列已經翻譯，詳[PR1319](https://github.com/CAFECA-IO/iSunFA/pull/1319)，剩餘部分已另外開票處理 ：[#1323](https://github.com/CAFECA-IO/iSunFA/issues/1323)、[#1325](https://github.com/CAFECA-IO/iSunFA/issues/1325)、[#1326](https://github.com/CAFECA-IO/iSunFA/issues/1326)、[#1327](https://github.com/CAFECA-IO/iSunFA/issues/1327)

done
