### ISSUE TITLE
i18n JSON - select-company page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1031]
![Screenshot 2024-06-12 at 17 32 55](https://github.com/CAFECA-IO/iSunFA/assets/20677913/659e125e-8ba9-44e3-aa29-86314d0aeca4)

**Comment by jing12345678910** [comment]
took 1 hr
<img width="1431" alt="image" src="https://github.com/CAFECA-IO/iSunFA/assets/143787831/1fe1ed33-4175-4ac9-a115-98c5b1c78bd0">

done
