### ISSUE TITLE
i18n JSON - dashboard page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1032]
- 儀表板頁面的多語系

![Screenshot 2024-06-12 at 16 31 48](https://github.com/CAFECA-IO/iSunFA/assets/20677913/9b056912-f869-46b1-90cb-fa84ba318515)

**Comment by jing12345678910** [comment]
took 2 hrs
儀表板頁面翻譯完成
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/33e76be6-81eb-4646-bc43-60cab708df95">

done
