### ISSUE TITLE
i18n JSON - project page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1033]
- project page 的多語系

![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/f1104eae-eb13-4be8-8fac-4f40eb96b8e9)

**Comment by jing12345678910** [comment]
took 2 hrs
<img width="1384" alt="image" src="https://github.com/CAFECA-IO/iSunFA/assets/143787831/a63ecbf6-dd60-4875-8ba9-cff8b30337a3">

下拉選單部分已另外開票處理：[#1323](https://github.com/CAFECA-IO/iSunFA/issues/1323)

done
