### ISSUE TITLE
i18n JSON - account page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1034]
- account page 的多語系，包含 sidebar 裡面的內容

![Screenshot 2024-06-12 at 16 32 39](https://github.com/CAFECA-IO/iSunFA/assets/20677913/6982ddae-6219-4845-82f2-ff30c0fcb63f)

**Comment by jing12345678910** [comment]
took 2 hrs
<img width="1426" alt="image" src="https://github.com/CAFECA-IO/iSunFA/assets/143787831/18df773d-f1a0-4713-806b-43c08d7e0e2d">

done
