### ISSUE TITLE
i18n JSON - salary page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1035]
- salary page 的多語系
![Screenshot 2024-06-12 at 16 33 05](https://github.com/CAFECA-IO/iSunFA/assets/20677913/fc921f51-a860-4d26-8feb-325a2f72189c)

**Comment by jing12345678910** [comment]
took 1 hr
<img width="1439" alt="image" src="https://github.com/CAFECA-IO/iSunFA/assets/143787831/4b78647f-97fe-40f3-b9f1-841f0d5fc4fc">

done
