### ISSUE TITLE
i18n JSON - report page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1036]
- report page 的多語系，包含 sidebar 裡面的內容

![Screenshot 2024-06-12 at 16 33 34](https://github.com/CAFECA-IO/iSunFA/assets/20677913/26277f62-b1e2-4de1-a04b-ae702c9924d1)

![Screenshot 2024-06-12 at 16 33 22](https://github.com/CAFECA-IO/iSunFA/assets/20677913/254863bd-a22e-4a9b-8c9d-0a7e154229bc)

![Screenshot 2024-06-12 at 16 33 39](https://github.com/CAFECA-IO/iSunFA/assets/20677913/a1e2a944-acd0-40ff-b7a7-a25bc92ce8d2)
![Screenshot 2024-06-12 at 16 34 06](https://github.com/CAFECA-IO/iSunFA/assets/20677913/f3f23ad0-e515-40c8-9fc3-c5f080d21ab3)
![Screenshot 2024-06-12 at 16 33 57](https://github.com/CAFECA-IO/iSunFA/assets/20677913/b1545ebf-a04e-4160-b837-cb49ae2d6e1c)

**Comment by jing12345678910** [comment]
took 2 hrs

---

<img width="1429" alt="image" src="https://github.com/CAFECA-IO/iSunFA/assets/143787831/7efe12e6-ac95-4b3e-aef1-a11ec2e09e7e">

---

<img width="1430" alt="image" src="https://github.com/CAFECA-IO/iSunFA/assets/143787831/039aed03-b27d-424e-b839-be908bbb54dc">

---

<img width="413" alt="image" src="https://github.com/CAFECA-IO/iSunFA/assets/143787831/e85fa676-b6d2-4b3c-aad7-ed306992d9e8">

下拉選單部分已另外開票處理：[#1323](https://github.com/CAFECA-IO/iSunFA/issues/1323)

---

done
