### ISSUE TITLE
i18n JSON - Audit report page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1038]
- audit report page (`https://isunfa.com/reports`) 多語系 

![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/2f8af827-b871-4b22-b8e0-1d77f19850b0)

**Comment by jing12345678910** [comment]
took 1 hr
<img width="495" alt="image" src="https://github.com/CAFECA-IO/iSunFA/assets/143787831/45eee49e-6b7d-42bf-965a-fa48952ddc7b">
<img width="421" alt="image" src="https://github.com/CAFECA-IO/iSunFA/assets/143787831/d7748378-8299-4246-84cd-1c969e560dcd">
<img width="414" alt="image" src="https://github.com/CAFECA-IO/iSunFA/assets/143787831/d965cccd-f614-46a1-9734-1a6f62b533c3">
done
