### ISSUE TITLE
[UI] Setting

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#104]
- [x] 會計科目管理
- [x] 交易對象管理
- [x] 管理員設定
- [x] 支付與訂閱設定

**Comment by StrawHo** [comment]
LINK:
https://www.figma.com/file/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?type=design&node-id=199%3A78282&mode=design&t=B9KB4afryXlvsBo3-1

花費時間約8hr
