### ISSUE TITLE
MilestoneCalendar

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/iSunFA#1057]
![image](https://github.com/CAFECA-IO/iSunFA/assets/114177573/640e6e15-22ae-449c-866e-7d9b4fe9526e)

1. 點擊單一日期時，整個 dashboard 要切換到指定日期當天的資料
2. 用下面的選單調整 stage 時，call PUT api 給後端調整資料，途中會有幾秒鐘的 loading
3. 需要一直 call GET api 刷新資料，並重畫畫面

**Comment by TeresaYang00** [comment]
已調整設計
