### ISSUE TITLE
SettingAccountTitlePage (ISFMK00031) (ISFMK00040) (desktop)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1104]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/5a3e4fce-7a0c-449f-b957-11abb25ef518)

[desktop mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&m=dev)｜[mobile mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811-111363&m=dev)

**Comment by Julian0701** [comment]
- take 3 hrs, done
