### ISSUE TITLE
EditAccountTitleModal (desktop)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1112]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/2347651f-b91a-4e79-a93b-4fcf9a99a71f)

[desktop mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&m=dev)｜[mobile mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811-111363&m=dev)

**Comment by Julian0701** [comment]
- take 2 hrs, done
