### ISSUE TITLE
AddAccountTitleModal (desktop)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1113]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/570b3b0e-d87a-4515-960f-79bd9d25044a)

[desktop mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&m=dev)｜[mobile mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811-111363&m=dev)

**Comment by Julian0701** [comment]
- take 1 hr, remain 1 hr

**Comment by Julian0701** [comment]
- take 1 hr, done
