### ISSUE TITLE
SettingAccountTitlePage (ISFMK00031) (ISFMK00040)  (mobile)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1132]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/02e3c5ae-68c8-48bf-ae25-9367b44301fa)

[desktop mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&m=dev)｜[mobile mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811-111363&m=dev)

**Comment by Julian0701** [comment]
- take 2 hrs, done
