### ISSUE TITLE
CompanySettingsModal (TeamSettingsModal on component diagram) (mobile)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1133]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/02e28e4c-d4e8-40e0-9475-4cbdf6393206)

[desktop mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&m=dev)｜[mobile mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811-111363&m=dev)

**Comment by TeresaYang00** [comment]
設計稿已調整 無此需求
