### ISSUE TITLE
AddAccountTitleModal  (mobile)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1134]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/f3e2d901-3602-4c40-a243-f5bf7ab8da18)

[desktop mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&m=dev)｜[mobile mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811-111363&m=dev)

**Comment by Julian0701** [comment]
- take 1 hr, done
