### ISSUE TITLE
SettingSideBar  (mobile)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1137]
![Screenshot 2024-06-20 at 16 30 16](https://github.com/CAFECA-IO/iSunFA/assets/20677913/5b17dd99-5c3f-4679-ab67-65af64386189)
![Screenshot 2024-06-20 at 16 30 14](https://github.com/CAFECA-IO/iSunFA/assets/20677913/a6271cd8-f8eb-4bde-ac09-b5de72c8b00d)

[desktop mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&m=dev)｜[mobile mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811-111363&m=dev)

**Comment by TeresaYang00** [comment]
設計稿已調整 無此需求
