### ISSUE TITLE
MyNewAccountTitle  (mobile)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1139]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/0526989d-acb2-4c34-9e24-f0a0e7fb6863)

[desktop mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&m=dev)｜[mobile mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811-111363&m=dev)

**Comment by TeresaYang00** [comment]
設計稿已調整 無此需求
