### ISSUE TITLE
EditAccountTitleModal  (mobile)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1140]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/6b786b3b-6c84-4065-940e-59f051751d1b)

[desktop mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&m=dev)｜[mobile mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811-111363&m=dev)

**Comment by Julian0701** [comment]
- take 1 hr, done
