### ISSUE TITLE
AddTransactionPartnerModal  (mobile)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1143]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/291d62e7-2667-4004-98bf-722cc7c2add2)

[desktop mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&m=dev)｜[mobile mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811-111363&m=dev)

**Comment by TeresaYang00** [comment]
設計方向調整 票已無需要
