### ISSUE TITLE
EditTransactionPartnerModal  (mobile)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1144]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/3eae3546-f473-4bad-9b60-ffbe2a294ee8)

[desktop mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&m=dev)｜[mobile mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811-111363&m=dev)

**Comment by TeresaYang00** [comment]
設計稿已調整 無此需求
