### ISSUE TITLE
AddNewCardsModal  (mobile)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1154]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/fbda93d1-129c-477a-b9f1-9d1a486aad7a)

[desktop mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&m=dev)｜[mobile mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811-111363&m=dev)

**Comment by TeresaYang00** [comment]
設計稿已調整 無此需求
