### ISSUE TITLE
SubscriptionModal  (mobile)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1155]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/4d177b61-a364-4644-9f6b-b55b7fe654ec)

[desktop mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&m=dev)｜[mobile mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811-111363&m=dev)

**Comment by TeresaYang00** [comment]
設計稿已調整 無此需求
