### ISSUE TITLE
規劃 iSunFA 開發時程跟開票 contract management

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#117]
規劃 [contract management](https://www.figma.com/file/rBgNsf93LVEhZ1xnS5uCnD/iSunFA-Wireframe?type=design&mode=design) component

**Comment by Julian0701** [comment]
![iSunFa component contract management](https://github.com/CAFECA-IO/iSunFA/assets/114177573/2e05bd1d-7119-4081-a59b-197e3d34772f)

- 14 components，共 38 pt

**Comment by Julian0701** [comment]
- take 3 pt
