### ISSUE TITLE
規劃 iSunFA 開發時程跟開票 project

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#120]
規劃 [project](https://www.figma.com/file/rBgNsf93LVEhZ1xnS5uCnD/iSunFA-Wireframe?type=design&node-id=33-308635&mode=design) component

**Comment by Julian0701** [comment]
![iSunFa component project](https://github.com/CAFECA-IO/iSunFA/assets/114177573/d5d76d2f-1c64-43e0-ab43-743a10d47e0d)


 24 components ，共 13+53 = 66 pt
- take 4 hrs
