### ISSUE TITLE
規劃 iSunFA 開發時程跟開票 accounting

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#122]
規劃 [accounting](https://www.figma.com/file/rBgNsf93LVEhZ1xnS5uCnD/iSunFA-Wireframe?type=design&node-id=36-55820&mode=design) component

**Comment by Julian0701** [comment]
![iSunFa - accounting drawio](https://github.com/CAFECA-IO/iSunFA/assets/114177573/1a8bbd47-1bad-4e68-a775-24709b682d2f)

- 15 components ，共 47 pt
