### ISSUE TITLE
 [Bug] 登入頁面－畫面左邊圖片慢了很多秒

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1348]
Time of occurrence
7/5 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://isunfa.com/users/login

**Reproduction steps**
1. Go to'登入介面'
2. Click on '登入'
3. Scroll down to '登入'

**Current Result**
左側圖片慢了幾秒出現

**Expected Result**
希望要同時出現左側圖片和登入
不會延遲

**Comment by arealclimber** [comment]
took 1 hr
- 圖片從 svg (8.6MB) 改成 png (2.3MB ~~639KB, 解析度700x967~~) 圖片

done

**Comment by arealclimber** [comment]
took 1 hr
- 圖片從 svg (8.6MB) 改成 png (2.3MB ~~639KB, 解析度700x967~~) 圖片

done

**Comment by arealclimber** [comment]
took 0.5 hrs
再次壓縮圖片大小，但效果不彰，之後有時間可以採用 `page.ready` 的方式去用 skeleton 掩蓋正在 loading 的圖片

**Comment by arealclimber** [comment]
done
