### ISSUE TITLE
[Bug] 登入頁面－早上已註冊，無法掃描即登入．必須重新註冊

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1351]
經常已註冊，無法掃描即登入．必須重新註冊 重複數次
Time of occurrence
7/5 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://isunfa.com/users/login

無法掃二維碼即登入

Go to'登入'
Click on ' 掃碼'
Scroll down to ''
See error 沒有成功登入數次
<img width="735" alt="截圖 2024-07-08 上午11 51 34" src="https://github.com/CAFECA-IO/iSunFA/assets/150103188/e9f9b8cc-aa74-4978-809a-51f3b50cb437">

**Expected Result**
已註冊過的二維碼可以掃一次就直接登入成功

**Comment by arealclimber** [comment]
took 0.5 hrs
bug 目前無法重現

**Comment by TinyMurky** [comment]
08/07 bug 目前無法重現
