### ISSUE TITLE
[Bug] 登入頁面－點選試試看 直接跳轉到儀表板 並跳出試用結束 ，並跑出錯誤訊息

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1353]
Time of occurrence
7/5 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://isunfa.com/users/login

在沒有建立公司的情況下
以個人身份登入儀表板
**Reproduction steps**
1. Go to'儀表板'
2. Click on '  所有按鈕'
3. Scroll down to ''
4. See error  跳出錯誤訊息並無法跳轉其他頁面
<img width="1064" alt="截圖 2024-07-08 上午11 43 12" src="https://github.com/CAFECA-IO/iSunFA/assets/150103188/ec0d0ab0-893f-4178-9ab8-045995b12f64">

**Expected Result**
不會跳出錯誤訊息，並可以按其他快速鍵跳轉到其他頁面

**Comment by Luphia** [comment]
- look good

**Comment by arealclimber** [comment]
但沒有選公司情況下會跳錯誤訊息，

### case 1: 登入後自動跳轉到 select company page 後，選擇 try out

https://github.com/user-attachments/assets/b7b1ae0d-7b97-49da-9acd-be31c0c6495f


### case 2: 登入後自動跳轉到 dashboard page
https://github.com/user-attachments/assets/5c0165ac-3ae2-4ad8-97fc-61b348d5828a

**Comment by arealclimber** [comment]
解法：後端應創建公共 company，前端應使用公共 company id

**Comment by TeresaYang00** [comment]
問題尚未解決

https://github.com/user-attachments/assets/7509f530-2e90-4ca4-8f99-53e71b4efdb1

**Comment by arealclimber** [comment]
公共 company id： `1001`

**Comment by TzuHanLiang** [comment]
- 前端已將 trial company 串接到 company select，並可以透過 session看到後端有成功處理
- 但跟 company 相關的 API 目前都還會出錯，錯誤原因為 forbidden ，應該是權限的問題，所以這個問題是後端需要進一步處理，前端已處理完成
- took 3hrs
- done
