### ISSUE TITLE
[Bug] 儀表板頁面－儀表板快速清單下面拉霸原先設計稿沒有,只有左右可移動

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1357]
儀表板快速清單下面拉霸原先設計稿沒有,只有左右可移動
- [ ] YES, I have searched for similar issues.

### Time of occurrence

7/8 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.com/users/dashboard

### Reproduction steps

```markdown
1. Go to'儀表板介面'
2. Click on '快速登入的按鈕'
3. Scroll down to '左右滑動'
4. See error 不應該出現下面那條拉霸線
```

### Current Result

```markdown
出現下面那條拉霸線
```

### Screenshots

![截圖 2024-07-08 下午5 03 57](https://github.com/CAFECA-IO/iSunFA/assets/150103188/5732887a-75d9-4d15-adcb-aeabbc8c7942)

### Expected Result

```markdown
拉霸線消失可以按左右箭頭移動
```

**Comment by arealclimber** [comment]
took 0.5 hrs 
done
