### ISSUE TITLE
[Bug]日記帳頁面－無法用上傳憑證方式

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1358]
無法用上傳從檔案上傳憑證方式

### Time of occurrence

7/8 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.com/users/select-company

### Reproduction steps

```markdown
1. Go to'日記帳頁面'
2. Click on '上傳憑證'
3. Scroll down to '無'
4. See error 無法使用電腦上傳憑證檔案
```

### Current Result

```markdown
無法使用電腦上傳憑證檔案
```

### Expected Result

```markdown
可以使用電腦附夾檔案成功上傳憑證
```

**Comment by Julian0701** [comment]
- take 3 hrs, done
