### ISSUE TITLE
[Bug] 日記帳頁面－事件描述按鈕（送出送出）

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1359]
### Time of occurrence

7/8 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction steps

```markdown
1. Go to'日記帳頁面'
2. Click on '事件送出'
3. Scroll down to ' '
4. See error 按鈕顯示送出送出
```

### Current Result

```markdown

```按鈕顯示送出送出


### Screenshots

### Logs

_No response_

### Expected Result

```markdown
按鈕可以顯示“送出”兩字即可
```

**Comment by Julian0701** [comment]
<img width="1062" alt="image" src="https://github.com/CAFECA-IO/iSunFA/assets/114177573/0067ce3d-1f3b-477c-bd6a-e337a1fb9306">

- done
