### ISSUE TITLE
[Bug] 日記帳－上傳憑證中 尚未送出 也無法刪除

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1364]
### Time of occurrence

7/8 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction steps

1. Go to'日記帳頁面'
2. Click on '新增日記帳'
3. Scroll down to ' 拍照上傳'
拍照上傳憑證後再上傳中 也無法刪除此憑證照片

![截圖 2024-07-11 下午3 11 51](https://github.com/CAFECA-IO/iSunFA/assets/150103188/39463c23-cf07-4da4-a61b-bf0b9ddc8caf)

### Current Result

     利用拍照憑證上傳中尚未儲存此張憑證 也尚未辨識成功 
     但卻無法成功刪除

### Expected Result

markdown
只要在尚未生成會計傳票的情況下，都要可以在未儲存狀態下 ，刪除憑證。

**Comment by TzuHanLiang** [comment]
- 目前直接上傳會失敗，需要用 #1455 的 branch
- 經討論發現未實作 delete OCR API，新增需求
- 前端先串接 `Delete /api/v1/company/<company>/ocr/<ocrId>` API

took 1.5hrs
done
