### ISSUE TITLE
[Bug] 日記帳頁面－付款方式下拉選單 語言顯示錯誤 

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1366]
### Time of occurrence

7/8 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction steps

```markdown
1. Go to'日記帳頁面'
2. Click on '付款方式'
3. Scroll down to ' 下拉選單'
4. See error  
```下拉選單語言顯示錯誤"




### Current Result

```markdown

```下拉選單語言顯示錯誤



### Screenshots

### Logs

_No response_

### Expected Result

```markdown
下拉選單我在選擇中文的時候請呈現中文 
選擇英文的時候請呈顯英文
```

**Comment by jing12345678910** [comment]
took 1 hr
付款方式下拉選單 調整翻譯完成
<img width="1420" alt="image" src="https://github.com/user-attachments/assets/4527d485-4442-4b4e-b495-3214ab178b87">

done
