### ISSUE TITLE
[Bug] 日記帳頁面－分期付款次數的線超出格子

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1367]
Time of occurrence
7/5 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://www.isunfa.com/users/accounting

![截圖 2024-07-08 下午6 53 44](https://github.com/CAFECA-IO/iSunFA/assets/150103188/16b51a03-cd7e-4a0a-938b-6fb3cb664505)

**Reproduction steps**
1. Go to'新增日記帳'
2. Click on '分期付款'
3. Scroll down to ''
4. See error “分期付款次數值中間的線超出格子外

**Current Result**
分期付款次數值中間的線超出格子外

**Expected Result**
分期付款次數值中間的線在格子以內

**Comment by Luphia** [comment]
- bug fixed with Anna
