### ISSUE TITLE
[Bug] 日記帳頁面－專案和合約排列方式為直式

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1368]
日記帳頁面－專案和合約排列方式為直式
  Time of occurrence
7/5 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://www.isunfa.com/users/accounting

![截圖 2024-07-08 下午6 44 21](https://github.com/CAFECA-IO/iSunFA/assets/150103188/dab7a738-fc61-43be-bb14-0ea0490e6dfd)

**Reproduction steps**
1. Go to'新增日記帳'
2. Click on '專案'
3. Scroll down to ''
4. See error “專案”和”合約“按鈕排列為直式

**Current Result**
“專案”和”合約“按鈕排列為直式

**Expected Result**
“專案”和”合約“按鈕排列為橫式

**Comment by Luphia** [comment]
- bug fixed with Anna
