### ISSUE TITLE
[Bug] 日記帳頁面－付款狀態部分付款無法輸入數字

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1369]
Time of occurrence
7/5 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://isunfa.com/users/accounting

![截圖 2024-07-08 下午7 22 24](https://github.com/CAFECA-IO/iSunFA/assets/150103188/17f86446-200d-4250-9c15-64b5838a356a)

**Reproduction steps**
1. Go to'新增日記帳'
2. Click on '部分付款'
3. Scroll down to ''
                     無法輸入數字
**Current Result**
無法輸入數字

**Expected Result**
可以輸入任意數字

**Comment by Julian0701** [comment]
- take 1 hr, done
