### ISSUE TITLE
[Bug] 日記帳頁面－資產管理頁面 預計使用壽命 數字無法輸入 

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1370]
Time of occurrence
7/5 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://isunfa.com/users/accounting

![截圖 2024-07-08 下午7 29 14](https://github.com/CAFECA-IO/iSunFA/assets/150103188/6a519b23-3a96-42ab-a18e-21573246f952)

**Reproduction steps**
1. Go to'新增日記帳'
2. Click on '新增資產'
3. Scroll down to ''
                     無法輸入數字
**Current Result**
無法輸入數字

**Expected Result**
可以輸入任意數字

**Comment by Julian0701** [comment]
- take 1 hr, done
