### ISSUE TITLE
[Bug] 日記帳頁面－資產管理頁面 預計使用壽命 中英夾雜

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1371]
Time of occurrence
7/5 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://isunfa.com/users/accounting

**Reproduction steps**
1. Go to'新增日記帳'
2. Click on '新增資產'
3. Scroll down to ''
                     "年year"按鈕修正成中文版 顯示中文 以此類推
**Current Result**
"年year"按鈕修正成中文版 顯示中文 以此類推

**Expected Result**
"年year"按鈕修正成中文版 顯示“年”中文 以此類推

**Comment by jing12345678910** [comment]
took 1 hr
已修復完成，顯示中文"年"

<img width="591" alt="image" src="https://github.com/CAFECA-IO/iSunFA/assets/143787831/9e6427d6-c287-436f-9046-54bb488296ff">

done
