### ISSUE TITLE
[Bug] 日記帳頁面－跳轉到日記帳頁面填入文字會整個頁面無法跳轉

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1372]
Time of occurrence
7/5 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://isunfa.com/users/accounting

![截圖 2024-07-08 下午7 42 23](https://github.com/CAFECA-IO/iSunFA/assets/150103188/18f4123f-adc0-477d-aac2-f4e5b520cc02)

Reproduction steps

Go to'新增日記帳'
Click on '填入描述'
Scroll down to ''
See error
填入資料後要"上傳"會整個無法儲存網頁壞掉

Current Result
填入資料後要"上傳"會整個無法儲存網頁壞掉

Expected Result
填入資料後要“上傳”成功

**Comment by Julian0701** [comment]
- take 6 hrs, unfinished

![image](https://github.com/CAFECA-IO/iSunFA/assets/114177573/45846c26-8d78-4919-83c6-005b3bb56284)
推測是這段的錯誤造成頁面重整，須重構 `changeVoucherAmountHandler`


另外有發生 `createInvoice` 首次建立 invoice 時頁面會重整的情況（第二次建立就不會），須釐清是否為同一個問題

**Comment by Julian0701** [comment]
- take 5 hrs, unfinished
- 從 `ConfirmModal` 開始地毯式搜索

**Comment by Julian0701** [comment]
- take 5 hrs, unfinished
- 發現錯誤的原因是 `<AccountingVoucherRow />` 在第一次 create invoice 時還沒拿到 `accountList` ，導致 crush 和網頁重整

### To-Do List
- [ ] 修復 accountList 造成的錯誤
- [ ] AccountingVoucherRowMobile
- [ ] 修復 `<ConfirmModal />` 的 ask AI API 和 submit btn

**Comment by Julian0701** [comment]
- take 6 hrs
- 仍有部分錯誤：
  - ask AI API 還沒修好
  - 在電腦版和手機版切換時 vocher row 沒有及時更新

**Comment by Julian0701** [comment]
- take 4 hrs, done
- 修正 voucher row 有時候沒有寫入的錯誤
