### ISSUE TITLE
[Bug] 登入頁面－公司統一編號重複無法登入跳出錯誤訊息並未告知錯誤的原因

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1380]
Time of occurrence
7/5 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://www.isunfa.com/users/select-company

![截圖 2024-07-09 下午1 31 28](https://github.com/CAFECA-IO/iSunFA/assets/150103188/5e48933f-7e9d-492d-b0f9-71e532b338bf)

**Reproduction steps**
1. Go to'登入'
2. Click on '建立公司'
3. Scroll down to ''
   重複的公司統編，導致無法新建成功，錯誤訊息並未跳轉正確
                 
**Current Result**
 重複的公司統編，導致無法新建成功，錯誤訊息並未跳轉正確

**Expected Result**
請告知為何沒成功建立公司的訊息，並以我選擇的語言顯示。

**Comment by arealclimber** [comment]
在統一編號重複時，會發生 API request 502 bad gateway，無法讀取對應的 error code

![CleanShot 2024-07-15 at 10 27 37](https://github.com/user-attachments/assets/aa7b7370-3848-4f8e-bbf7-2be975c53957)


https://github.com/user-attachments/assets/2cb6f374-8b85-4912-a1d6-eb6cc4be003c

**Comment by arealclimber** [comment]
took 1 hr
remaining 1 hr

**Comment by arealclimber** [comment]
took 1 hr
done
