### ISSUE TITLE
[Bug] 報告頁面－報告類型下拉選單語言錯誤

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1383]
Time of occurrence
7/5 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://www.isunfa.com/users/reports/my-reports

**Reproduction steps**
1. Go to'報告'
2. Click on '我的報告'
3. Scroll down to ''
   我選擇的語言是中文 但報告上的檔名應該也要對應中文
   現在全部都是英文
                 
**Current Result**
 選擇的語言是中文 但報告上的檔名應該也要對應中文
  現在全部都是英文

**Expected Result**
選擇的語言是中文 但報告上的檔名應該也要對應中文

**Comment by arealclimber** [comment]
took 1 hr
- 與 @Luphia 討論後，報告名稱不需要翻譯，但在畫面上新增報告類型欄位 (#1465)，這個欄位需要翻譯
- 將新增的欄位跟欄位選擇補上後，避免翻譯檔管理有誤，所以我沒有加上翻譯，這部分已在 code 上面註記，請 @jing12345678910 協助處理

![CleanShot 2024-07-12 at 14 57 41](https://github.com/user-attachments/assets/e838b3d4-f1f1-4b68-a1e4-ca666c781c44)


![CleanShot 2024-07-12 at 13 26 19](https://github.com/user-attachments/assets/748d12f1-1501-404e-8701-e9c84cab85bf)

**Comment by jing12345678910** [comment]
took 1 hr
已經把新加的欄位翻譯完成
生成中：
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/52e5744b-e5f3-4a3c-b492-06038009cbf0">

歷史報告：
<img width="1187" alt="image" src="https://github.com/user-attachments/assets/708f9a72-42f2-44f8-8722-0b8b447c4f30">


done
