### ISSUE TITLE
[Bug] 報告頁面－我的報告排序方式 無法依照最新或最舊

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1385]
Time of occurrence
7/5 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://www.isunfa.com/users/reports/my-reports?pending=1&history=1

![截圖 2024-07-09 上午11 46 17](https://github.com/CAFECA-IO/iSunFA/assets/150103188/394a750f-021a-4817-846e-b0d11c4de90d)

**Reproduction steps**
1. Go to'報告'
2. Click on '我的報告'
3. Scroll down to '排序方式'
   我的報告排序方式選擇最新或最舊的都無法顯示最新或最舊
                 
**Current Result**
我的報告排序方式選擇最新或最舊的都無法顯示最新或最舊

**Expected Result**
我的報告排序方式選擇最新或最舊可以依照指定方式排列

**Comment by arealclimber** [comment]
took 1 hrs
- 前端傳 query 給後端

**Comment by arealclimber** [comment]
took 1 hr
done
