### ISSUE TITLE
🐛 [BUG] - 登入頁面－無法創建公司

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1401]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

7/8 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.com/users/select-company

### Reproduction steps

```markdown
1. Go to'登入介面'
2. Click on '我的公司列表'
3. Scroll down to '選擇公司'
4. See error
```

### Current Result

```markdown
無法送出創建新的公司成功
```

### Screenshots

![截圖 2024-07-08 下午4 38 40](https://github.com/CAFECA-IO/iSunFA/assets/150103188/2a3d5d7e-5eb9-42e2-adb3-acb4aa3ecdc2)

### Expected Result

```markdown
可以成功送出新建公司
```

**Comment by Luphia** [comment]
- bug already fixed
