### ISSUE TITLE
🐛 [BUG] - 營業費用分成銷管研，要在name的部分更新前面的名稱

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#1403]
### Searched for similar issues

- [X] YES, I have searched for similar issues.

### Time of occurrence

2024/7/8 17:15

### Device

MacBook Pro

### Device Version

2018

### OS

macOS

### OS Version

2018

### Browsers

Firefox

### Browser Version

3

### Reproduction URL

None

### Reproduction steps

```markdown
1. Go to the database and find out that 折舊 has 3 different kinds of code, which are: 6124, 6224, 6324
```

### Current Result

```markdown
The name that accounts return only returns 折舊, which is confusing
```

### Screenshots

![DESCRIPTION](LINK.png)

### Expected Result

```markdown
Maybe be 營業費用-折舊
```

**Comment by gibbs-shih** [comment]
在 saveToJson 前新建 adjustAccountElements function 調整對應名稱
![CleanShot 2024-07-29 at 15 32 23](https://github.com/user-attachments/assets/a511f6af-b6ed-4769-bdd3-479026402410)

**Comment by gibbs-shih** [comment]
adjustAccountElements
<img width="553" alt="CleanShot 2024-07-29 at 15 46 39@2x" src="https://github.com/user-attachments/assets/1b8b0e7c-2020-424d-9a4c-6f78303578cf">
<img width="524" alt="CleanShot 2024-07-29 at 15 47 05@2x" src="https://github.com/user-attachments/assets/7f680c95-f37e-4140-80d9-5a42841c2b47">
<img width="543" alt="CleanShot 2024-07-29 at 15 47 24@2x" src="https://github.com/user-attachments/assets/ad50be70-4b7f-4b99-a780-f64fb43c06ff">

**Comment by gibbs-shih** [comment]
![CleanShot 2024-07-29 at 16 05 37](https://github.com/user-attachments/assets/070c49d8-b551-42e3-872e-d36f5b304bd2)
![CleanShot 2024-07-29 at 16 07 13](https://github.com/user-attachments/assets/44bd9e62-0415-40f7-aa24-913acc777857)
![CleanShot 2024-07-29 at 16 07 26](https://github.com/user-attachments/assets/f8f4de96-a8a9-45e8-b617-186d11dd8c5c)
![CleanShot 2024-07-29 at 16 07 38](https://github.com/user-attachments/assets/4cf584e9-f210-4b17-a6ec-ad64b368e225)

**Comment by gibbs-shih** [comment]
take 2-3 hr
