### ISSUE TITLE
🐛 [BUG]分析報告- 專案欄位選擇overall，也可以按產生，未跳錯誤訊息

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1413]
Time of occurrence
7/9 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://www.isunfa.com/users/reports/financials

![截圖 2024-07-09 下午6 56 57](https://github.com/CAFECA-IO/iSunFA/assets/150103188/76677cf5-f00e-413d-8527-94443770c9ab)

**Reproduction steps**
1. Go to'報告'
2. Click on '分析報告'
3. Scroll down to '專案'
專案選擇overall 還是可以產生報告 未跳轉錯誤訊息
                 
**Current Result**
專案選擇overall 還是可以按“產生”報告 未跳轉錯誤訊息

**Expected Result**
專案選擇overall 還是可以“產生”報告 請跳轉錯誤訊息或是無法“產生”

**Comment by jing12345678910** [comment]
took 2 hrs
經過前後端討論，選擇overall，代表選擇全部的專案，可以產出報告是合理的
因此這張票的修復，僅是把overall的下拉選單，翻譯為中文完成
<img width="1303" alt="image" src="https://github.com/user-attachments/assets/407ce006-0b14-4d5b-a464-cf7ceac8fdde">


done
