### ISSUE TITLE
🐛 [BUG] - 分析報告專案欄位，顯示語言錯誤

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1414]
Time of occurrence
7/9 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://www.isunfa.com/users/reports/analyses

![截圖 2024-07-09 下午6 33 25](https://github.com/CAFECA-IO/iSunFA/assets/150103188/a8410760-1936-4a06-99b4-5f03db815241)

**Reproduction steps**
1. Go to'報告'
2. Click on '分析報告'
3. Scroll down to '專案'
中文版本專案,下拉選單 “overall  ”請改成中文 

                 
**Current Result**
中文版本專案,下拉選單 “overall  ”請改成中文 

**Expected Result**
中文版本專案,下拉選單 “overall  ”請改成中文 全部 
依照不同的語言版本應該要有不同的用字

**Comment by jing12345678910** [comment]
took 1 hr
已經調整翻譯完成
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/e5ce3624-549c-4a32-9747-a5a595abe15b">

done
