### ISSUE TITLE
🐛 [BUG] 報告頁面－錯誤訊息無法正確告知哪個欄位的錯誤問題

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1415]
Time of occurrence
7/9 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://www.isunfa.com/users/reports/financials

**Reproduction steps**
1. Go to'報告'
2. Click on '財務報告和分析報告'
3. Scroll down to '產出'
錯誤訊息無法正確告知哪個欄位的錯誤問題
                 
**Current Result**
財務報告專案欄位，顯示語言錯誤
**Expected Result**
財務報告專案欄位，顯示語言錯誤

**Comment by jing12345678910** [comment]
1. 因為我們現在還沒有報告的資料，所以會顯示報告生成失敗的訊息
2. 並且因為我們的輸入欄位都是下拉選單，沒有選擇日期區間的話，也不能按下產生報告的按鈕，因此不太可能是因為某個欄位的資料輸入錯誤，導致報告無法產生
3. 因此這張票Ｗon't fix

預設的輸入選單
<img width="619" alt="image" src="https://github.com/user-attachments/assets/8ea33344-5ad9-4983-a248-43ce1e743694">
<img width="604" alt="image" src="https://github.com/user-attachments/assets/2e37e8cf-5163-4d60-8596-5216ce57643a">

**Comment by jing12345678910** [comment]
經過和Luphia討論 這張票不能Ｗon't fix 因為就算沒有資料 也應該要產生空的報表 因此是還沒實作API的問題
