### ISSUE TITLE
🐛 [BUG] 日記帳頁面- 新增日記帳拍照 ai 辨識金額、日期有問題

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1416]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

today 12:00 PM

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.com/users/accounting

### Reproduction steps

```markdown
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Current Result

```markdown
1111
```

### Screenshots

![DESCRIPTION](LINK.png)

### Expected Result

```markdown
1111
```

**Comment by TinyMurky** [comment]
目前先用gemini替代，提昇辨識精確度
