### ISSUE TITLE
[FEATURE] - Implement unify input check

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#1454]
### Summary

Implement unify input check function

### Tasks

```markdown
- [ ] Implement unify input check
```

**Comment by TinyMurky** [comment]
Research: 
- [ ] #2315

**Comment by TinyMurky** [comment]
幫以下的api增加t unify input check
[FEATURE] - ocr unify input check
[FEATURE] - invoice  unify input check
[FEATURE] - journal unify input check
[FEATURE] - voucher unify input check

**Comment by TinyMurky** [comment]
Beta 版本開始
於v2 版本實做
