### ISSUE TITLE
🐛 [BUG] - 錯誤訊息無法正確告知哪個欄位的錯誤問題

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1457]
Time of occurrence
7/9 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://www.isunfa.com/users/reports/financials

![截圖 2024-07-11 上午10 47 31](https://github.com/CAFECA-IO/iSunFA/assets/150103188/ed10facb-c30b-4d04-bd7c-4ce10f1c2e53)

**Reproduction steps**
1. Go to'報告'
2. Click on '財務報告和分析報告'
3. Scroll down to '產出'
錯誤訊息無法正確告知哪個欄位的錯誤問題
                 
**Current Result**

錯誤訊息無法正確告知哪個欄位的錯誤問題
**Expected Result**
錯誤訊息正確告知哪個欄位的錯誤問題

**Comment by jing12345678910** [comment]
took 3 hrs
經過和Luphia討論 是api串接的問題 已修復完成
後面生成的報告還需要修改，有另外開票處理，詳[1427](https://github.com/CAFECA-IO/iSunFA/issues/1427)、[1428](https://github.com/CAFECA-IO/iSunFA/issues/1428)、[1429](https://github.com/CAFECA-IO/iSunFA/issues/1429)
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/6b313552-2427-4f33-89dc-53d81dfd57e1">


done
