### ISSUE TITLE
🐛 [BUG] - 日記帳頁面－選擇轉帳銀行帳號無反應

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1458]
Time of occurrence
7/5 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://isunfa.com/users/accounting

![截圖 2024-07-11 下午3 36 39](https://github.com/CAFECA-IO/iSunFA/assets/150103188/363d2830-6926-46b6-a06c-262b42534514)

Reproduction steps

Go to'新增日記帳'
Click on '付款方式選擇轉帳'
Scroll down to ''
See error
無法選擇銀行和填入銀行帳號

Current Result
無法選擇銀行和填入銀行帳號

Expected Result
可以選擇不同的銀行和填入銀行帳號

**Comment by TzuHanLiang** [comment]
took 1hr
done
