### ISSUE TITLE
🐛 [BUG]登入頁面－登入頁面沒註冊設備下， Toast 不會自己關閉

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1466]
Time of occurrence
7/11 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://isunfa.com/users/accounting

![截圖 2024-07-11 下午5 03 08](https://github.com/CAFECA-IO/iSunFA/assets/150103188/99edec65-a10b-46e7-8c80-1e7ea833e777)

**Reproduction steps**
1. Go to'登入'
2. Click on '註冊設備'
3. Scroll down to ''
     登入頁面沒註冊設備下， Toast 不會自己關閉
**Current Result**
登入頁面沒註冊設備下， Toast 不會自己關閉

**Expected Result**
登入頁面沒註冊設備下， Toast 過一段時間會自己關閉

**Comment by godmmt** [comment]
問題是指說
登入時沒有註冊設備，要關閉通知嗎

還是指說
登入之後，要關閉通知？

**Comment by TeresaYang00** [comment]
登入頁面沒註冊設備下， Toast 經過一段時間會自己關閉，不需要一直顯示。

**Comment by godmmt** [comment]
我目前打開 https://isunfa.com/users/login
沒有出現提示

**Comment by godmmt** [comment]
@TeresaYang00 
我目前打開 https://isunfa.com/users/login
沒有出現提示

<img width="1440" alt="截圖 2024-07-30 上午11 15 56" src="https://github.com/user-attachments/assets/5a84f29f-a285-4585-b66e-4c32a25dc20c">

**Comment by TeresaYang00** [comment]
那應該版本更新後沒有這個問題了感謝

**Comment by godmmt** [comment]
此問題經檢查後已不存在
所以 won't fix
