### ISSUE TITLE
🐛 [BUG] 登入頁面－特殊字元的人名無法產生頭貼

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1484]
Time of occurrence
7/12 12:00 PM

Device
MacBook Pro

OS
macOS

Browsers
Chrome

Browser Version
No response

Reproduction URL
https://isunfa.com/users/login

Go to'登入'
Click on ' 掃碼'
Scroll down to '創建名稱'
See error 
創建名稱特殊字元
圖片不能出現

**Expected Result**
創建名稱特殊字元需要提示無法創建
頭貼名稱可以順利出線

**Comment by Julian0701** [comment]
- take 2 hrs

**Comment by RexBearIU** [comment]
It takes 2.5 hours.

![image](https://github.com/user-attachments/assets/16a088f7-fd8d-4cda-bf36-ab83be086d5d)


add regex only get Chinese or English or number with small refactor on upload svg
