### ISSUE TITLE
🐛 [BUG]  日記帳頁面－掃瞄器以手機QRCODE為主並非打開電腦的相機

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1494]
### Time of occurrence

7/12 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction steps

1. Go to'日記帳頁面'
2. Click on '新增日記帳'
3. Scroll down to ' 拍照上傳'

應該是提供QRCODE 掃描

![截圖 2024-07-12 上午11 55 34](https://github.com/user-attachments/assets/6d17a75d-573f-422c-a2a3-7561be62e81f)

### Current Result

     利用拍照憑證上傳中尚未儲存此張憑證 也尚未辨識成功 
     但卻無法成功刪除

### Expected Result

markdown
只要在尚未生成會計傳票的情況下，都要可以在未儲存狀態下 ，刪除憑證。

**Comment by TzuHanLiang** [comment]
我目前的目標是構建一個系統，讓用戶可以通過手機端掃描電腦端頁面上的 QR code，在手機端上傳的照片可以實時顯示在電腦端的頁面上。

### 具體實現目標：
1. **生成 QR Code 讓用戶掃描**：
   - 電腦端頁面會顯示一個 QR Code，該 QR Code 包含唯一的會話標識或用戶 ID，讓手機端可以掃描並使用該 ID 進行圖片上傳。

2. **手機端上傳圖片**：
   - 用戶在手機端通過掃描 QR Code，跳轉到一個上傳頁面，選擇圖片並將其上傳到後端 API（如 `/api/v1/upload`）。
   - 上傳時，會攜帶該唯一標識（從 QR Code 獲取的會話 ID 或用戶 ID），以便將上傳的圖片與電腦端的用戶進行綁定。

3. **實時顯示上傳的圖片**：
   - 後端 API 接收到手機端上傳的圖片後，保存圖片，並通過 WebSocket 伺服器向所有連接的客戶端（例如電腦端的頁面）發送圖片上傳完成的通知。
   - 電腦端頁面通過 WebSocket 實時接收到來自後端的通知，並顯示手機端上傳的圖片。

### 工作流程：
1. **生成 QR Code**：
   - 電腦端頁面會生成一個包含唯一會話 ID 的 QR Code，該 QR Code 可以由手機端掃描。
   
2. **手機端掃描 QR Code 上傳圖片**：
   - 用戶掃描 QR Code，然後跳轉到上傳頁面。上傳圖片的 API 請求中攜帶該唯一會話 ID，來標識哪個用戶上傳了圖片。
   
3. **後端保存圖片並發送 WebSocket 通知**：
   - 後端 API 接收到手機端上傳的圖片後，將其保存到伺服器，並通過 WebSocket 伺服器向電腦端廣播通知，內容包括上傳完成的圖片 URL。

4. **電腦端實時更新**：
   - 電腦端通過 WebSocket 連接到伺服器，當收到圖片上傳完成的通知時，會自動更新頁面並顯示最新上傳的圖片。


### 總結：
1. 用戶掃描電腦端的 QR Code，進入手機端的上傳頁面。
2. 手機端上傳圖片，並將會話 ID（從 QR Code 獲取）與圖片一起發送到後端。
3. 後端接收圖片，保存後通過 WebSocket 通知電腦端頁面。
4. 電腦端頁面實時接收通知，並顯示上傳的圖片。


目前前端無法成功開啟websocket 連線，took 8hrs

**Comment by TzuHanLiang** [comment]
確認 websocket 是可行的，應該不用轉為pusher
took 1.5hrs
