### ISSUE TITLE
🐛 [BUG] 日記帳頁面－新增日記帳頁面，專案和合約選項出現意義不明的文字

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1495]
### Time of occurrence

7/12 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction steps

1. Go to'日記帳頁面'
2. Click on '新增日記帳'
3. Scroll down to ' 專案和合約'
4. See error  出現意義不明的文字

應該是提供QRCODE 掃描

### Current Resul

      出現意義不明的文字

### Screenshots
    
![截圖 2024-07-12 下午2 04 02](https://github.com/user-attachments/assets/6a5493a0-d76b-48e2-84da-1cdba1fa045c)

### Expected Result

  刪除出現意義不明的文字

**Comment by TeresaYang00** [comment]
問題沒有解決
https://github.com/user-attachments/assets/e071ec6a-bc48-4b98-bc3a-c0100432724f

**Comment by TeresaYang00** [comment]
問題尚未解決
https://github.com/user-attachments/assets/cb4a9697-fa54-49d6-b744-78df8320024b

**Comment by jing12345678910** [comment]
took 1 hr
<img width="1343" alt="image" src="https://github.com/user-attachments/assets/0ddac27e-279e-4605-8f3c-b5a06126559f">
<img width="1346" alt="image" src="https://github.com/user-attachments/assets/467e5724-f409-48dc-97f4-f316bf066287">

done
