### ISSUE TITLE
🐛 [BUG] 登入頁面－未選擇公司前的狀態，兩個按鈕應無法使用 

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1496]
### Time of occurrence

7/12 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction steps

1. Go to'登入頁面'
2. Click on '儀表板和方形按鈕 '
3. Scroll down to ' '

未選擇公司前的狀態，兩個按鈕可以使用 
設計調整 ＠Jodie

### Current Resul

      

未選擇公司前的狀態，兩個按鈕可以使用 

### Screenshots
    
<img width="601" alt="截圖 2024-07-12 下午2 10 50" src="https://github.com/user-attachments/assets/4b09cfbd-4bf6-42c0-958d-bbed1628b059">

### Expected Result

未選擇公司前的狀態，兩個按鈕應無法使用

**Comment by Julian0701** [comment]
- take 1 hr, done
