### ISSUE TITLE
🐛 [BUG] - 登入頁面－通知重疊

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1497]
### Time of occurrence

7/12 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction steps

1. Go to'登入頁面'
2. Click on '通知 '
3. Scroll down to ' '
4. See error  兩種通知會重疊

### Current Resul

      

兩種通知會重疊 

### Screenshots
    
![截圖 2024-07-12 下午2 26 44](https://github.com/user-attachments/assets/083d1b9d-e16c-48e6-a3c5-27f9d3a00cfd)

### Expected Result

 只會出現一種通知

**Comment by Julian0701** [comment]
- take 3 hrs, done
