### ISSUE TITLE
🐛 [BUG] 報告頁面- 下載好的報告沒有被轉到 history區，仍存在在pending區，並且產出日期沒有排序

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1503]
### Reproduction steps

1. Go to'報告'
2. Click on '待辦 '
3. Scroll down to ' 歷史紀錄'
              待辦下載好的報告沒有跳轉到歷史紀錄區
              產出報告日期沒有排序

### Current Resul
待辦下載好的報告沒有跳轉到歷史紀錄區
 產出報告日期沒有排序

### Screenshots
    

<img width="816" alt="截圖 2024-07-12 下午4 04 07" src="https://github.com/user-attachments/assets/925a04c9-da52-4560-a6f3-7168ceaef2ae">

### Expected Result

待辦下載好的報告跳轉到歷史紀錄區
 產出報告按日期排序

**Comment by Julian0701** [comment]
- take 1 hr, done

> 待辦下載好的報告沒有跳轉到歷史紀錄區

為 API 產生的錯誤，已請 Murky 協助處理
另外加上列表由新至舊排序
