### ISSUE TITLE
🐛 [BUG] 日記帳頁面－選項為“income”時不會有新增asset按鈕，payment reason與supplier 兩欄文字也該有所不同

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1506]
### Reproduction steps

請參考Jodie的設計稿

1. Go to'日記帳'
2. Click on '新增日記帳 '
3. Scroll down to ' income'

### Current Resul

   選項為“income”時會有新增asset按鈕，payment reason與supplier 兩欄文字也沒有所不同

### Screenshots
    

![截圖 2024-07-12 下午3 45 39](https://github.com/user-attachments/assets/6ded9d44-5d2c-4fab-bbc8-d693d5563a4f)

### Expected Result

選項為“income”時不會有新增asset按鈕，payment reason與supplier 兩欄文字也該有所不同

**Comment by Julian0701** [comment]
- take 1 hr, done
