### ISSUE TITLE
🐛 [BUG]  左側欄位icon沒有置中對齊

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1508]
### Time of occurrence

7/12 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.com/users/accounting/journal-list
### Reproduction steps

1. Go to'日記帳頁面'
2. Click on '左側欄位'
3. Scroll down to ' '
 icon沒有置中對齊

### Current Result

   icon沒有置中對齊

### Screenshots

![截圖 2024-07-12 下午4 21 24](https://github.com/user-attachments/assets/56432cee-b7f0-4f2c-a5c3-83a19e3a25dc)

### Expected Result

icon 置中對齊

**Comment by Julian0701** [comment]
- take 0.5 hr, done
<img width="58" alt="image" src="https://github.com/user-attachments/assets/07686e7e-a39e-4c33-a0c5-5df390432815">
