### ISSUE TITLE
🐛 [BUG] 登入頁面-建立第二間公司，第一間的建立資料不會reset

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1510]
### Time of occurrence

7/12 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction URL
https://isunfa.com/users/select-company

1. Go to'登入'
2. Click on '選擇公司'
3. Scroll down to ' '

### Current Result

建立第二間公司，第一間的建立資料不會reset

<img width="812" alt="截圖 2024-07-12 下午4 31 20" src="https://github.com/user-attachments/assets/de76f465-6fd4-4ea6-b45a-635bc73dfb38">

### Expected Result

建立第二間公司，第一間的建立資料會reset

**Comment by godmmt** [comment]
因為建立公司這部分不太熟悉，所以點數先開高一點，如果提早做完的話會再調低點數。

**Comment by godmmt** [comment]
20240719 @arealclimber 已修復此問題
