### ISSUE TITLE
[DOCS] - Discuss 401 report related changes

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#1511]
### Summary

Discuss 401 report related changes for issue tickets

### Tasks

```markdown
- [X] Discuss 401 report-related changes
```

**Comment by RexBearIU** [comment]
It takes 2 hours.
https://github.com/CAFECA-IO/iSunFA/issues/1467

**Comment by jing12345678910** [comment]
It takes 2 hours.

New issues opened based on the discussion content.
[#1504](https://github.com/CAFECA-IO/iSunFA/issues/1504)
[#1502](https://github.com/CAFECA-IO/iSunFA/issues/1502)

done
