### ISSUE TITLE
🐛 [BUG] -Tab狀態沒有Active

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1512]
### Time of occurrence

7/12 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.com/users/accounting/journal-list
### Reproduction steps

1. Go to''
2. Click on '左側欄位'
3. Scroll down to ' '

Tab狀態沒有Active

### Current Result

 Tab狀態沒有Active

### Screenshots
<img width="852" alt="截圖 2024-07-12 下午4 44 20" src="https://github.com/user-attachments/assets/31770ed2-830e-4c0e-a95b-eb9bb70d2c9e">

### Expected Result

 Tab狀態Active

**Comment by Julian0701** [comment]
- take 10 min, done
