### ISSUE TITLE
🐛 [BUG] -所有的翻譯錯誤

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1513]
### Time of occurrence

today 12:00 PM

### Device

None

### Screenshots
<img width="840" alt="截圖 2024-07-12 下午4 47 29" src="https://github.com/user-attachments/assets/d3f661e8-b0ff-4a01-b425-126fc508a91a">
<img width="426" alt="截圖 2024-07-12 下午4 47 39" src="https://github.com/user-attachments/assets/7c3918dd-b594-431c-be5d-a393c0e3cc84">
<img width="849" alt="截圖 2024-07-12 下午4 47 51" src="https://github.com/user-attachments/assets/f87691cd-56d7-4453-a6c1-cf5bb71d1f93">
<img width="571" alt="截圖 2024-07-12 下午4 48 23" src="https://github.com/user-attachments/assets/e130fdab-51ee-4408-900e-6348f4d67f1f">

<img width="688" alt="截圖 2024-07-12 下午4 48 01" src="https://github.com/user-attachments/assets/a8f4f4a2-7ce6-4db0-86f8-1ab416ee12f4">

<img width="806" alt="截圖 2024-07-12 下午4 48 43" src="https://github.com/user-attachments/assets/d904fda4-8ec7-40e0-b927-f91df04e6a1a">

**Comment by jing12345678910** [comment]
took 2 hrs
<img width="944" alt="image" src="https://github.com/user-attachments/assets/1d6a3f83-3cc2-4298-9b19-9e07006f56a8">
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/637dcf5b-07f6-42e2-a9ed-a65637953837">
<img width="234" alt="截圖 2024-07-15 下午2 45 03" src="https://github.com/user-attachments/assets/fabdd391-9f25-432c-980b-028f0fd0f4a5">
<img width="1252" alt="image" src="https://github.com/user-attachments/assets/1899a76e-33b1-4dc4-bdb2-205c5052702e">

done
