### ISSUE TITLE
Discuss ISF mock API spec and distributed API docs

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#152]
Discuss ISF mock API spec and distributed API docs for API wiki

會議連結：[點我](https://github.com/CAFECA-IO/EventReport/blob/main/meeting/20240415_isunfa_api.md)

**Comment by TinyMurky** [comment]
Figma: [https://www.figma.com/file/4PS1QfFhlwIrJ5WwyDcWws/iSunFA?type=design&node-id=497%3A34413&mode=design&t=sHGXlRIgiOJ6RgSM-1](https://www.figma.com/file/4PS1QfFhlwIrJ5WwyDcWws/iSunFA?type=design&node-id=497%3A34413&mode=design&t=sHGXlRIgiOJ6RgSM-1)

**Comment by TinyMurky** [comment]
took 5 hours
complete
會議連結：[點我](https://github.com/CAFECA-IO/EventReport/blob/main/meeting/20240415_isunfa_api.md)
