### ISSUE TITLE
[FEATURE] - GET all journal要依照 sort, event 回傳TotalPage totalEvent (number)

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#1520]
### Summary

GET all journal要依照 sort, event 來回傳TotalPage totalEvent

### Tasks

```markdown
這個API /src/pages/api/v1/company/[companyId]/journal/index.ts

要回傳
totalUploadedEvent: number
totalUpComingEvent: number
uploadedEventTotalPage: number
UpComingEventTotalPage: number
```

**Comment by RexBearIU** [comment]
It takes 1.5 hours.

將pagenation改成

export interface IPaginatedData<T> {
  data: T[];
  page: number;
  cursor: number;
  totalPages: number;
  totalCount: number; // 總數量
  pageSize: number; // 每頁顯示的項目數量
  hasNextPage: boolean; // 是否有下一頁
  hasPreviousPage: boolean; // 是否有上一頁
  sortOrder: string; // 排序方式
  sortBy: string; // 排序欄位
}

**Comment by RexBearIU** [comment]
It takes 2 hours.
done
