### ISSUE TITLE
[DOCS] - 討論0.8 Alpha release

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#1531]
### Summary

討論0.8 Alpha release

### Tasks

- 星期三早上11點確認進度
- 討論db schema 增加report 存放 json欄位
- 分配以下的票
    - [FEATURE - DELETE /ocr/:resultId #1470](https://github.com/CAFECA-IO/iSunFA/issues/1470) -3pt
    - [FEATURE - GET all Journal 要增加upcoming和 upload event #1518](https://github.com/CAFECA-IO/iSunFA/issues/1518) -3pt
    - [FEATURE - GET all journal sort by 專案進度與付款進度 #1519](https://github.com/CAFECA-IO/iSunFA/issues/1519) -3pt
    - [FEATURE - GET all journal要依照 sort, event 來回傳TotalPage totalEvent #1520](https://github.com/CAFECA-IO/iSunFA/issues/1520) -3pt
    - [FEATURE - Journal 要增加作廢欄位 #1521](https://github.com/CAFECA-IO/iSunFA/issues/1521) -3pt
    - [FEATURE - Invoice 要增加作廢欄位 #1522](https://github.com/CAFECA-IO/iSunFA/issues/1522) -3pt

**Comment by TinyMurky** [comment]
最後決定把report加上 context 叫做json

**Comment by TinyMurky** [comment]
took 1 hour
done

**Comment by RexBearIU** [comment]
開report db 與 與interface更改 - 2 pt
https://github.com/CAFECA-IO/iSunFA/issues/1470 -3pt
https://github.com/CAFECA-IO/iSunFA/issues/1518 -3pt
https://github.com/CAFECA-IO/iSunFA/issues/1519 -3pt
https://github.com/CAFECA-IO/iSunFA/issues/1520 -3pt
https://github.com/CAFECA-IO/iSunFA/issues/1521 -3pt
https://github.com/CAFECA-IO/iSunFA/issues/1522 -3pt
