### ISSUE TITLE
[FEATURE] - POST addNewSub API integration on setting page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1568]
### Summary
Integrate the POST addNewSub API on the setting page. This feature allows adding new subs to accounting titles.

### Tasks
- [x] ensure API interfaces
- [x] Implement API integration on page

**Comment by Julian0701** [comment]
- [API wiki](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getaccountsbyid)

**Comment by Julian0701** [comment]
- take 3 hrs, done
