### ISSUE TITLE
🐛 [BUG]日記帳 -總金額和成本數字千位數符號

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1618]
### Time of occurrence

today 12:00 PM

### OS

macOS

### Reproduction URL
https://isunfa.com/en/users/accounting

### Reproduction steps

1. Go to '日記帳'
2. Click on '.新增日記帳'
3. Scroll down to '成本和總金額欄位'

### Current Result

成本和總金額欄位

### Screenshots

![截圖 2024-07-18 下午2 19 40](https://github.com/user-attachments/assets/13b4db92-635c-453d-896c-2faf4b9d2486)

### Expected Result

成本和總金額欄位會需顯示千分位符號

**Comment by godmmt** [comment]
@TeresaYang00  Screenshots 圖片沒跑出來

**Comment by godmmt** [comment]
Reproduction URL 有誤

應該是 https://isunfa.com/en/users/accounting

**Comment by godmmt** [comment]
- 0722 took 3hours

**Comment by godmmt** [comment]
@TeresaYang00 是你圖中的 4 個紅框都要有千位數的逗號標記嗎？

1. 總金額
2. 費用
3. 部分付款
4. 估計成本

**Comment by TeresaYang00** [comment]
對的， 4 個紅框都要有千位數的逗號標記

**Comment by godmmt** [comment]
# 修改 NumericInput 元件
新增 prop : hasComma
並且分離 顯示值 和 存入 DB 值的儲存值

isDecimal 控制是否為整數或是浮點數（顯示值和儲存值都適用）
hasComma 控制是否要顯示千位數逗號（只會動到顯示值）

並且整合元件的其他效果
onChange ： 馬上變更顯示值和儲存值
失焦：空值或.就改為0
聚焦：清空0直接輸入
