### ISSUE TITLE
🐛 [BUG] 日記帳- 憑證AI辨識成功，新增日記帳填寫表單，上傳成功無先跳轉預覽頁面

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1633]
### Time of occurrence

7/18 12:00

### OS

macOS

### Reproduction URL

https://isunfa.com/users/accounting/10000269

### Reproduction steps

1. Go to '日記帳'
2. Click on '新增日記帳'
3. Scroll down to '上傳'
憑證AI辨識成功，新增日記帳填寫表單，上傳成功無先跳轉預覽頁面

### Current Result

憑證AI辨識成功，新增日記帳填寫表單，上傳成功無先跳轉預覽頁面

### Screenshots

![截圖 2024-07-18 下午4 44 01](https://github.com/user-attachments/assets/c67ea519-4773-4368-ac0e-2b52eed19c9e)

### Expected Result
憑證AI辨識成功，新增日記帳填寫表單，上傳成功跳轉預覽頁面

**Comment by Julian0701** [comment]
- take 3 hrs, remain 5 hrs
- 改用 `window.location.href` 就可以成功跳轉，但 journalId 有誤所以跳轉到了錯誤的日記帳頁面
- 觀察有沒有畫面不能互動的情形

**Comment by Julian0701** [comment]
- take 3 hrs, done
- 無其他異常
