### ISSUE TITLE
[DOCS] - W29清點團隊完成票數

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1643]
### Summary

追蹤進度

### Tasks

```markdown
1.前端點數比較滿，每日追蹤大家的完成度
```

**Comment by TeresaYang00** [comment]
7/18
1. 清點 Murky 手上還剩下24點
2.Emily 增加 11點
3.Julian減少9點 因為Setting-favorite不用

**Comment by TeresaYang00** [comment]
7/19(7/23前alpha點數)
Murky 剩 17 點
Emily 剩 17
Julian 剩 14
liz 剩 37 (bugs)+翻譯 ３
Anna 剩 33

**Comment by Luphia** [comment]
- overdue tasks
