### ISSUE TITLE
calculate total API number in ISF wireframe

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#165]
calculate total API number in ISF wireframe

分成三份
- Gibbs
    - 開帳
    - Employee
    - Report
    - DashBoard
- Jacky
    - Setting
    - KYC
- Murky
    - Contract Management
    - Project

**Comment by TinyMurky** [comment]
# Contract Management
1. GET `/contracts`
2. GET `/contracts/:id`
3. POST `/contracts/upload`
4. POST  `/contracts/upload/callback`
5. POST `/contracts`
6. POST `/contracts/:id`

**Comment by TinyMurky** [comment]
# Project

## a. projects
1. GET `/projects`
2. POST `/projects`

## b. main
3. GET `projects/:id/values` (包含 project value, total Revenue, net profit, net project, total expense)
4. GET `projects/:id/cases_count`
5. GET `projects/:id/progress`
6. GET `projects/:id/milestone`
7. GET `projects/:id/monthly_sales`
8. GET `projects/:id/sales`
9. GET `projects/:id/woker_rate`

## c. contracts, accounting
10. GET `projects/contracts`
11. GET `projects/event/accounting` ?????
12. POST `projects/event/income`
13. POST `projects/event/expence`
14. POST `projects/upload` ???
15. POST `projects/upload/callback` ???

## d. management
16. POST `projects/management`
17. POST `projects/management/:id`

**Comment by TinyMurky** [comment]
# Invoice and Certificate
1. GET `/certificate/:id`
2. GET `/invoice/:id`

**Comment by TinyMurky** [comment]
0. ㅏ

1. Configuration

2. 1. Get all-subjects? code = & subject =

3. dashboard

4. X

5. 2. Get

6. Yeport/

7. c. Post financial/

8. Get

9. (*)

10. 3. Post

11. analysis /projects/

12. # Get projects (id_and_name

13. 2. Post analysis/

14. own-subjects? type = Sliquid=

15. employees/

16. -+--

17. 1. Get

18. ? id=

19. 系統架構图

20. 2. Get departments /

21. Salary

22. 3. Post

23. 1. Get ?id=

24. 4 Delete ?id=

25. 2. Put ?id=

26. Sequence Diagram

27. API. respones request.

28. Class Diagram

29. evroode

30. 5.

31. Put

32. ?id=

33. 10.49

34. RELIGGER
![1000003034](https://github.com/CAFECA-IO/iSunFA/assets/55581222/1ce47cab-f6ac-4a94-960d-320a7b857cc9)

**Comment by RexBearIU** [comment]
[ISF WIKI](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0)

Total : 65
