### ISSUE TITLE
🐛 [BUG] 日記帳- 專案和合約選擇，導致無法上傳

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1650]
### Time of occurrence

7/18 12:00

### OS

macOS

### Reproduction URL

https://isunfa.com/users/accounting/10000269

### Reproduction steps

1. Go to '日記帳'
2. Click on '新增日記帳'
3. Scroll down to '專案和合約'
無法上傳

### Current Result

需先參考 [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&t=o6GDW7e8DXrhNe4d-1)目前頁面和設計稿不同
新增日記帳選擇專案和合約選擇，導致無法上傳

### Screenshots

![截圖 2024-07-19 下午3 26 18](https://github.com/user-attachments/assets/3090f7fd-dc6d-4df7-ba80-3cefdd312414)

### Expected Result
新增日記帳選擇專案和合約選擇，導致無法上傳

**Comment by Julian0701** [comment]
- take 2 hrs, done
