### ISSUE TITLE
🐛 [BUG] 日記帳- 新增日記帳填寫表格無法上傳，未告訴錯誤原因

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1653]
### Time of occurrence

2024/ 7/19 12:00

### OS

macOS

### Reproduction URL

https://isunfa.com/cn/users/accounting

### Reproduction steps

1. Go to '日記帳'
2. Click on '新增日記帳'
3. Scroll down to '上傳'

 新稱日記帳填寫表格無法上傳，未告訴錯誤原因

### Current Result

新稱日記帳填寫表格無法上傳，未告訴錯誤原因

### Screenshots
![截圖 2024-07-19 下午2 16 19](https://github.com/user-attachments/assets/ad6fd5b1-6ef0-4a99-892b-bbfbba7855fd)

### Expected Result
如有必填欄位沒有填，
可以按“上傳”
但會跳訊息告知哪一個欄位沒有填

**Comment by godmmt** [comment]
點擊 上傳 按鈕
跳出吐司通知有哪些欄位使用者必須填寫

**Comment by godmmt** [comment]
took 3.5 hours

done.

**Comment by Julian0701** [comment]
- take 5 hrs, done
- 新增欄位提醒
- 其他按鈕不能按的問題於 #1633 處理

**Comment by godmmt** [comment]
此張 issue 因為重複開票，所以重工了。

討論後決定採用 @Julian0701 的程式碼
所以我的 PR 就不發了
