### ISSUE TITLE
🐛 [BUG]日記帳- 從日記帳頁面上傳成功，切換其他頁面會跳出錯誤訊息

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1654]
### Time of occurrence

2024/ 7/19 12:00

### OS

macOS

### Reproduction steps

1. Go to '日記帳'
2. Click on '新增日記帳'
3. Scroll down to ''

 新稱日記帳填寫表格無法上傳，未告訴錯誤原因

### Current Result

新稱日記帳填寫表格無法上傳，未告訴錯誤原因

**Comment by Julian0701** [comment]
- take 5 hrs, done
- 新增欄位提醒
- 其他按鈕不能按的問題於 #1633 處理

**Comment by TeresaYang00** [comment]
待新版本更新確認有無此問題 
再補畫面

**Comment by Julian0701** [comment]
- take 3 hrs, done
- journal 畫面調整
