### ISSUE TITLE
[DOCS] - get All accounts wiki

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#1684]
### Summary

完成

### Tasks

```markdown
- [ ] get All accounts wiki
```

**Comment by gibbs-shih** [comment]
修改於：
[A020001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getAllAccounts) - GET /company/:companyId/account - ISFMK00040, ISFMK00031

**Comment by gibbs-shih** [comment]
take 2 hr
