### ISSUE TITLE
[FEATURE] - Assist Anna in implementing the three major tables

### ISSUE THREAD

**Issue by jing12345678910** [CAFECA-IO/iSunFA#1694]
### Summary

[FEATURE] - Assist Anna in implementing the three major tables

### Tasks

```markdown
[FEATURE] - Assist Anna in implementing the three major tables
```

**Comment by arealclimber** [comment]
![CleanShot 2024-07-23 at 12 19 44](https://github.com/user-attachments/assets/fdecaa29-3f3f-492a-8982-b99877eacb2b)
![CleanShot 2024-07-23 at 12 19 58](https://github.com/user-attachments/assets/96c8253e-fa09-49cd-916f-2f01d8cdfb08)

**Comment by arealclimber** [comment]
```tsx
reportLink={`${DOMAIN}/users/report/v1/${reportId}/${ReportUrlMap[reportFinancial?.reportType as keyof typeof ReportUrlMap]}`}

export const ReportUrlMap: {
  [key in ReportSheetType]: string;
} = {
  [ReportSheetType.BALANCE_SHEET]: 'balance-sheet',
  [ReportSheetType.INCOME_STATEMENT]: 'income-statement',
  [ReportSheetType.CASH_FLOW_STATEMENT]: 'cash-flow-statement',
  [ReportSheetType.CHANGE_IN_EQUITY_STATEMENT]: 'change-in-equity-statement',
};

```

**Comment by arealclimber** [comment]
使用 reportType 判斷報表類別
```tsx
interface APIResponse {
  general: IAccountReadyForFrontend[];
  details: IAccountReadyForFrontend[];
  reportType: ReportSheetType;
}
```

**Comment by arealclimber** [comment]
took 6 hrs
remaining x hrs

**Comment by arealclimber** [comment]
- 將財報放到 `users/` 路徑底下，需要登入才能看到頁面，會導致網頁轉 PDF 出錯，所以現在將財報路徑從 `https://isunfa.com/users/reports/10000036/balance-sheet` 改為 `https://isunfa.com/reports/10000036/balance-sheet` ，在部署到 production 之後再觀察 PDF 轉換的情況


![CleanShot 2024-07-26 at 12 21 25](https://github.com/user-attachments/assets/7526b7fe-8c80-4d95-88d7-a0a59f87e73c)

**Comment by arealclimber** [comment]
- 7/23 部署的版本將財報放到 `users/` 路徑底下，需要登入才能看到頁面，會導致網頁轉 PDF 出錯 (CORS)，所以現在將財報路徑從 `https://isunfa.com/users/reports/10000036/balance-sheet` 改為 `https://isunfa.com/reports/10000036/balance-sheet` ，在部署到 production 之後再觀察 PDF 轉換的情況


![CleanShot 2024-07-26 at 12 21 25](https://github.com/user-attachments/assets/7526b7fe-8c80-4d95-88d7-a0a59f87e73c)

**Comment by arealclimber** [comment]
- [ ] 觀察 HTML 轉 PDF
- [ ] 放上縮圖

**Comment by arealclimber** [comment]
- [x]  balance sheet 圓餅圖計算 (refer to Murky)
- [x]  balance sheet 確定會計科目
- [x]  報告側邊截圖縮圖
- [x]  用縮圖控制PDF換頁
- [x]  把 Create financial report 多餘的排版刪掉
- [ ]  將 PDF 顯示改成用 iframe 顯示
- [ ]  單獨報告頁面需登入跟確認用戶權限之後再顯示

**Comment by arealclimber** [comment]
took 2 hrs
remaining tasks in #1753  #1754

**Comment by arealclimber** [comment]
done
