### ISSUE TITLE
🐛 [BUG] 日記帳-已上傳活動的清單顯示借貸不平衡

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1696]
### Time of occurrence

7/23 12:00

### Reproduction URL

https://isunfa.com/users/select-company

### Reproduction steps

1. Go to '日記帳'
2. Click on '新增日記帳'
3. Scroll down to '即將到來的日記帳'

### Screenshots
![截圖 2024-07-22 下午6 26 09](https://github.com/user-attachments/assets/31c9c7c6-e3f4-4eec-87a5-49bde44ebaf2)

### Expected Result

清

**Comment by TinyMurky** [comment]
現在科目名稱會是借方和貸方最大的名稱
金額則是相加
<img width="1294" alt="截圖 2024-07-26 下午1 20 28" src="https://github.com/user-attachments/assets/797d4a12-6179-442a-b0be-4b458ed93f68">
<img width="1253" alt="截圖 2024-07-26 下午1 25 17" src="https://github.com/user-attachments/assets/ed4db148-08c7-431d-9f16-057fe63e58b7">

**Comment by TinyMurky** [comment]
took 2 hours
done
