### ISSUE TITLE
🐛 [BUG] - Post File  API 失敗

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#1713]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

Today 2:30 PM

### Device

MacBook Pro

### Device Version

15-inch, 2017

### OS

macOS

### OS Version

13.6.7 (22G720)

### Browsers

Chrome

### Browser Version

Version 126.0.6478.127 (Official Build) (x86_64)

### Reproduction URL

https://www.isunfa.com//users/kyc

### Reproduction steps

```markdown
1. Go to 'KYC'
2. Click on 'Upload Document'
3. Drag file to 'Drop your files here or Browse'
4. See API error
```

### Current Result

```markdown
1. API error
```

### Screenshots

<img width="1680" alt="Screenshot 2024-07-24 at 2 43 16 PM" src="https://github.com/user-attachments/assets/4b7bd17c-206b-4546-b6db-c6a4d98d265f">

### Expected Result

```markdown
1. API success
```

**Comment by RexBearIU** [comment]
There is a file path error due to the .env is miss, and the file path is not corresponding.

**Comment by RexBearIU** [comment]
It takes 2 hours.

done
