### ISSUE TITLE
[DOCS] - Update Voucher wiki

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#1717]
### Summary

Update Voucher wiki

### Tasks

```markdown
- [ ] Update voucher 需要有wiki
```

**Comment by gibbs-shih** [comment]
新增  V011002 updateAVoucher
`PUT /company/:companyId/voucher/:voucherId`

**Comment by gibbs-shih** [comment]
[V011002](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#updateAVoucherById) - PUT /company/:companyId/voucher/:voucherId - ISFMK00050右邊

**Comment by gibbs-shih** [comment]
take 1 hr
