### ISSUE TITLE
🐛 [BUG] - Update voucher點擊送出之後，畫面不會跳轉

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#1721]
### Searched for similar issues

- [X] YES, I have searched for similar issues.

### Time of occurrence

2026/07/26 11:00

### Device

MacBook Pro

### OS

macOS

### Reproduction URL

https://github.com/CAFECA-IO/iSunFA/tree/develop

### Reproduction steps

```markdown
1. Go to 日記帳清單頁面
2. Click on 更新圖示(需要是已經建立voucher的傳票，還未建立voucher的傳票不會出現這個bug)
3. 然後在voucher model 中修改voucher之後按下確認
4. 畫面會卡在原地，可是database已經成功更新
```

### Current Result

```markdown
voucher 更新會畫面不會跳轉
```

### Screenshots

![journal update](https://github.com/user-attachments/assets/fbf202a0-8e9d-46ed-97cc-efa03646bb26)

### Expected Result

```markdown
- 畫面可以跳到更新好的journal或是journal list
```

**Comment by TzuHanLiang** [comment]
關聯 issue #1712， 我改成跳轉至 journal 已經透過 #1737 merge 可以看一下是否還有這個問題

**Comment by Julian0701** [comment]
經測試此問題已修復，轉 won't fix
