### ISSUE TITLE
🐛 [BUG] 日記帳- 刪除journal之後，所有其他journal都會不見

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#1722]
### Searched for similar issues

- [X] YES, I have searched for similar issues.

### Time of occurrence

2024/07/26 11:00

### Device

None

### OS

macOS

### Reproduction URL

https://github.com/CAFECA-IO/iSunFA/tree/develop

### Reproduction steps

```markdown
1. Go to 日記帳清單
2. Click on 刪除journal
3. 整個畫面的journal list 暫時會不見
4. 需要再按一次“即將到來的會計事件”才會有
```

### Current Result

```markdown
目前journal list不會彈出來，可能是畫面移轉到"已上傳的會計事件"，但是頁籤高亮還是在“即將到來的會計事件”
```

### Screenshots

![journal delete](https://github.com/user-attachments/assets/fbeee596-e673-48aa-8228-0150f46b1532)

### Expected Result

```markdown
journal list 顯示？
```

**Comment by Julian0701** [comment]
- take 3 hrs, done
