### ISSUE TITLE
🐛 [BUG] 日記帳- 新增會計傳票，會計項目選擇太少

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1725]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

7/26 12:00

### Device

None

### OS

mac os

_No response_

### Reproduction URL

https://www.isunfa.com/users/accounting

### Reproduction steps

```markdown
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Current Result
大約只有10個左右的會計項目

### Screenshots

![截圖 2024-07-26 下午12 09 37](https://github.com/user-attachments/assets/13c855d3-82a2-4041-84d4-2104b16a0cb4)

### Expected Result

常用的會計項目都需要新增上去

**Comment by TinyMurky** [comment]
現在會出現全部的account
<img width="1280" alt="截圖 2024-07-26 下午1 25 52" src="https://github.com/user-attachments/assets/2eb047ec-2f5a-490e-9f94-b62fd567f6f1">

**Comment by TinyMurky** [comment]
took 2 hours
done
