### ISSUE TITLE
[FEATURE] - balance sheet, income statement sheet detail mapping json

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#1732]
### Summary

balance sheet, income statement sheet detail mapping json

### Tasks

```markdown
- [ ] 將constances/account_sheet_mapping/balance_sheet_mapping.json更正成符合Figma 上 details
- [ ] 將constances/account_sheet_mapping/income_statement_mapping.json符合Figma 上 details
```

**Comment by jing12345678910** [comment]
took 3 hrs
在拿api資料的時候 發現後端來的資料 會計科目順序和設計稿不同 因此協助調整 以下為示意圖
<img width="731" alt="image" src="https://github.com/user-attachments/assets/d82b2455-44a0-4a65-8034-8462c7597bd6">

done
