### ISSUE TITLE
🐛 [BUG]報告 - 點選試試看，可以查看其他公司的報告

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1750]
### Time of occurrence

7/29 12:00 PM

### Device

MacBook Pro

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.com/users/reports/my-reports

### Reproduction steps

1. Go to'報告'
2. Click on '報告'
3. Scroll down to '左右滑動'

### Current Result

沒有登入公司
卻可以以試試看登入的方式
查看到那家公司的報告

### Screenshots
![截圖 2024-07-29 下午2 20 40](https://github.com/user-attachments/assets/a9472d2f-aa29-4621-ace8-f8957ab637d1)

### Expected Result

沒有登入公司
不可以查看到那家公司的報告

**Comment by RexBearIU** [comment]
It takes 1.5 hours.

done
