### ISSUE TITLE
🐛 [BUG] 日記帳-新增日記帳輸入文字和數字空格不是很流暢會有點網頁卡頓

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1766]
### Time of occurrence

7/30 12:00

### OS

macOS

### Reproduction URL

https://isunfa.com/users/accounting

### Reproduction steps

1. Go to '會計'
2. Click on '.新增日記帳'

新增日記帳輸入文字和數字空格不是很流暢會有點網頁卡

### Current Result

新增日記帳輸入文字和數字空格不是很流暢會有點網頁卡
會出現藍色的背景

### Screenshots

![截圖 2024-07-30 上午11 31 43](https://github.com/user-attachments/assets/67956f3c-2e8f-4a65-9fcf-91ab406b765d)

### Expected Result

新增日記帳輸入文字和數字空格是很流暢

**Comment by godmmt** [comment]
- [ ] 檢查樣式是否有造成藍色底色輸入框不一致（藍色底色為瀏覽器內建儲存機制產生的樣式）並修改
- [ ] 檢查流暢度

**Comment by godmmt** [comment]
原先使用 divide-x divide-lightGray3 border border-lightGray3 去分割內部兩個元素
改為從兩個元素各自設定 border

左側輸入框使用 rounded-l-sm border border-lightGray3 
高度也設定在這 46px
input 有內建背景色，記得改變、或者設定透明由父層一起改變

右側設定 rounded-r-sm border border-l-0 border-lightGray3

**Comment by godmmt** [comment]
遇到無法 build 問題

解決步驟
1. delete node_modules folder
2. delete .next folder
3. delete package-lock.json
4. close all terminal
5. open a new terminal
6. `npm install`
7. `npm run build` ok

注意：
要將 prettier-plugin-tailwindcss 更新到 v0.6 以上才會自動把 className 多餘的空格刪除
[參考這裡](https://github.com/CAFECA-IO/iSunFA/issues/300#issuecomment-2225122915)
所以再多這一個步驟
8. terminal 輸入
```
npm install prettier-plugin-tailwindcss@latest --save-dev
```

**Comment by godmmt** [comment]
took 4 hours

done.
