### ISSUE TITLE
🐛 [BUG] 翻譯錯誤

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1772]
### Time of occurrence

7/30 12:00

### OS

macOS

### Reproduction URL

https://www.isunfa.com/users/reports/financials

### Reproduction steps

```markdown
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots
![截圖 2024-07-30 下午3 45 14](https://github.com/user-attachments/assets/47120bfc-e49e-45e4-a769-77adaa81899d)

**Comment by jing12345678910** [comment]
經詢問後端Murky 是因為連不上AI 修改.env即可

**Comment by jing12345678910** [comment]
took 3 hrs
<img width="1289" alt="image" src="https://github.com/user-attachments/assets/59aaf861-2fc4-4811-a653-79aeb3417c6d">

done

**Comment by jing12345678910** [comment]
took 2 hrs
done
