### ISSUE TITLE
🐛 [BUG] 日記帳- 會計項目下拉選單會遭阻擋

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1776]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

7/30 12:00

### OS

macOS

### Reproduction URL

https://isunfa.com/users/accounting

### Reproduction steps

1. Go to '日記帳'

### Current Result

會計項目下拉選單部分選項遭阻擋

### Screenshots

![截圖 2024-07-30 下午2 40 52](https://github.com/user-attachments/assets/816805ec-a339-4263-a7db-459ce3ae8869)

### Expected Result

下拉選單可以順利的全部清楚呈現

**Comment by TzuHanLiang** [comment]
**問題情境描述**:

這一個動態可增刪的 row 列表，每個 row 都包含一個下拉式選單。這些 row 的父容器具有滾動特性，即當 row 列表過長時，用戶可以通過滾動查看更多內容。在每個 row 中，下拉式選單的觸發元素可以打開一個下拉菜單。下拉菜單的定位需要對應觸發元素的位置，並且不應被父容器或視窗的邊界裁剪。

**難點分析**:

1. **動態位置計算**：每個 row 的位置會隨著增刪動作而改變，下拉式選單需要動態計算其顯示位置，以確保其能夠正確對齊到觸發元素。這個動態計算需要考慮 row 在頁面中的相對位置以及父容器的滾動位置。

2. **多重滾動影響**：下拉式選單的位置不僅受到 row 列表滾動的影響，還受到整個視窗滾動的影響。當用戶滾動父容器或頁面時，下拉式選單的位置必須即時更新，以保持正確顯示位置，這增加了對滾動事件監控的複雜性。

3. **視窗尺寸變化**：響應式設計要求下拉式選單在不同的視窗大小下都能正確顯示。當視窗大小改變時，需要重新計算和調整下拉式選單的位置，以防止其超出視窗邊界或被裁剪。

4. **性能問題**：由於下拉式選單的位置需要頻繁更新，特別是在用戶快速滾動或頻繁改變視窗大小時，可能會出現性能問題。需要對位置計算和渲染進行優化，以減少對頁面性能的影響，確保用戶體驗的流暢性。

這些問題使得下拉式選單的實現不僅僅是簡單的樣式和定位，更涉及到如何高效地處理位置計算和事件監控，以確保在各種情況下都能正確、流暢地顯示。

**結論**:

綜合上述難點，我們面臨的主要挑戰是如何在一個動態且滾動的環境中，準確且高效地顯示下拉式選單。由於下拉式選單的選項數量很多，使用者在尋找選項時可能會遇到不便，這也進一步增加了設計的複雜性。因此，我建議暫時不針對這個問題進行詳細的技術實現，而是與設計團隊討論潛在的設計調整，例如考慮其他更簡潔的交互方式或重新設計下拉式選單的顯示和操作方式。這樣的調整不僅能解決當前的技術挑戰，還能改善用戶體驗。

took 2hrs
轉為 won‘t fix，設計如果有調整會需要開新的issue處理
