### ISSUE TITLE
🐛 [BUG] 日記帳- 新增憑證完，填寫事件描述無法送出

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1779]
### Time of occurrence

7/30 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.com/users/accounting

### Reproduction steps

```markdown
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![截圖 2024-07-30 上午11 10 41](https://github.com/user-attachments/assets/1993496c-6cbb-45ed-8442-86238ea03d2e)

### Expected Result

填寫事件可以順利送出 並新增

**Comment by TzuHanLiang** [comment]
took 1hrs
done
