### ISSUE TITLE
🐛 [BUG] 報告- 開啟dev模式網頁會突然crash

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1782]
### Time of occurrence

7/29 12:00

### OS

macOS

### Reproduction URL

https://isunfa.com/users/select-company

### Reproduction steps

```markdown
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Current Result

```markdown
111
```

### Screenshots

![DESCRIPTION](LINK.png)

### Expected Result

```markdown
111
```

**Comment by arealclimber** [comment]
8/9 在 `https://isunfa.com/users/reports/financials/view/${report_id}?report_type=cash-flow` 打開 dev 不斷調整螢幕寬度，不能重現 bug

**Comment by arealclimber** [comment]
8/9 在 `https://isunfa.com/users/reports/financials/view/${report_id}?report_type=${report_type}` 打開 dev 不斷調整螢幕寬度，不能重現 bug
