### ISSUE TITLE
🐛 [BUG] 日記帳-日記帳清單 icon調整

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1804]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

7/30 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.com/users/select-company

### Reproduction steps

icon並非列印而是垃圾桶

### Current Result

icon並非列印而是垃圾桶

**Comment by TzuHanLiang** [comment]
took1hrs
done
