### ISSUE TITLE
🐛 [BUG] 登入- 已被刪除的公司仍會出現在公司選單中。

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1809]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

7/18 12:00

### Device

None

_No response_

### Reproduction URL

https://isunfa.com/users/select-company

### Reproduction steps

1. Go to '登入'
2. Click on '選擇公司..'

### Current Result

已被刪除的公司依然存在

### Screenshots

<img width="673" alt="截圖 2024-08-02 上午11 22 52" src="https://github.com/user-attachments/assets/5aeea7af-6b7c-438e-a992-97f000557c56">

### Expected Result

已刪除的公司不會在列表出現
也無法進入刪除公司的帳戶

**Comment by RexBearIU** [comment]
solve in [#1857](https://github.com/CAFECA-IO/iSunFA/issues/1857)
It takes 1 hour.

done
