### ISSUE TITLE
🐛 [BUG]KYC -KYC 下一步的按鈕狀態與樣式與設計不符。

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1810]
### Time of occurrence

7/30 12:00

### Device

None

### Reproduction URL

https://isunfa.com/users/kyc

### Reproduction steps

```markdown
1. Go to 'KYC'
2. Click on '下一步'
3. Scroll down to '....'
4. See error
```

### Current Result

下一步icon 和設計稿不符

### Screenshots

![截圖 2024-08-01 上午11 29 47](https://github.com/user-attachments/assets/b3f6a8d4-93e1-4842-a6d0-5702cff4b489)

### Expected Result

下一步icon 和設計稿相符

**Comment by godmmt** [comment]
- [x] 樣式已更新

**Comment by godmmt** [comment]
新增 重構 KYC 下一步按鈕邏輯

- [ ] https://github.com/CAFECA-IO/iSunFA/issues/1839

**Comment by godmmt** [comment]
took 0.5 hour

done
