### ISSUE TITLE
🐛 [BUG] KYC-離開頁面是回到上一個歷史紀錄點，需整個離開KYC頁面

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1813]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

7/31 12:00

### Device

None

### Reproduction URL
https://isunfa.com/users/kyc

### Reproduction steps

```markdown
1. Go to 'KYC'
2. Click on '返回鍵'
3. Scroll down to '....'
4. See error
```

### Current Result

回到上一個歷史點

### Screenshots

![截圖 2024-08-02 上午11 57 53](https://github.com/user-attachments/assets/91d11958-4d50-4d85-8d7d-2c83320964eb)

### Expected Result

應該是要整個離開KYC 頁面

**Comment by godmmt** [comment]
took 0.5 hr

done

**Comment by godmmt** [comment]
took 0.5 hour

done
