### ISSUE TITLE
🐛 [BUG]KYC - 試用版不需要KYC，可直接隱藏。

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1815]
### Time of occurrence

7/31 12:00

### Reproduction URL

https://isunfa.com/users/select-company

### Reproduction steps

1. Go to 'KYC'

### Current Result
 
 點選試試看還是會有KYC的功能

### Expected Result

 點選試試看還是不會有KYC的功能

**Comment by TeresaYang00** [comment]
麻煩這兩個按鈕隱藏
![Uploading 截圖 2024-08-02 下午4.38.17.png…]()

**Comment by Julian0701** [comment]
- take 1 hr, done
