### ISSUE TITLE
🐛 [BUG] KYC- 上方進度條為單純顯示使用者目前進行到的步驟，不可點擊icon進行切換，需將此功能移除。

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1816]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

7/30 12:00

### Device

None

### Reproduction URL

https://isunfa.com/users/kyc

### Reproduction steps

1. Go to 'KYC.'
2. Click on '狀態列'

### Current Result

上方進度狀態列是點擊切換步驟 
但設計稿沒有此功能
麻煩移除

### Screenshots

![截圖 2024-08-01 上午11 46 55](https://github.com/user-attachments/assets/75012e07-a554-4f67-98ce-8b6c8e3d8388)

### Expected Result

麻煩移除點擊icon 進行切換功能

**Comment by godmmt** [comment]
took 1 hour

done

**Comment by godmmt** [comment]
took 0.5 hour

done
