### ISSUE TITLE
🐛 [BUG] - KYC - Upload document 上傳失敗

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#1826]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

yesterday 5:00 pm

### Device

None

### OS

macOS

### Reproduction URL

https://www.isunfa.com//users/kyc

### Reproduction steps

```markdown
1. Go to 'kyc'
2. Click on 'Upload document'
3. drag file to 'Upload'
4. See error
```

### Current Result

```markdown
- UI show upload error but api success
```

### Screenshots

![DESCRIPTION](LINK.png)

### Expected Result

```markdown
- UI show success when api success
```

**Comment by RexBearIU** [comment]
It takes 1.5 hours.

done

**Comment by TzuHanLiang** [comment]
took 1hrs 新增限制
done
