### ISSUE TITLE
🐛 [BUG] -非本次alpha版本的功能需隱藏icon

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1863]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

7/29 12:00

### Device

None

### OS

macOS

### Reproduction steps

```markdown
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Current Result

```markdown
尚未隱藏
1.薪資
2.專案
3.分析報告
4.坎入程式碼
5.財務報告 －權益變動報告
```

### Screenshots

![DESCRIPTION](LINK.png)

### Expected Result

```markdown
隱藏
1.薪資
2.專案
3.分析報告
4.坎入程式碼
5.財務報告 －權益變動報告
```

**Comment by TeresaYang00** [comment]
![截圖 2024-08-02 下午4 57 08](https://github.com/user-attachments/assets/1fb6604f-fbfd-4f18-8472-f259ddd3c630)
麻煩隱藏謝謝

**Comment by Julian0701** [comment]
- take 2 hrs, done
