### ISSUE TITLE
🐛 [BUG] KYC- 公司網站為選填之選項，但不填也無法完成驗證

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1866]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

7/31 12:00

### Reproduction URL

https://www.isunfa.com/users/reports/financials

### Reproduction steps

```markdown
1. Go to 'KYC'
2. Click on '公司網址
3. Scroll down to '....'
4. See error
```

### Current Result

文字寫選填
但目前設為必填

### Screenshots

![截圖 2024-08-02 下午12 11 02](https://github.com/user-attachments/assets/d5c39f9d-2f21-4cc8-9fb8-92064e3b1305)

### Expected Result

修改成選填項目

**Comment by Julian0701** [comment]
https://github.com/user-attachments/assets/699b65b5-415c-4cd0-a140-91596a2e9d59

- 此版本已沒有這個錯誤

**Comment by Julian0701** [comment]
https://github.com/user-attachments/assets/699b65b5-415c-4cd0-a140-91596a2e9d59

- 此版本已沒有這個錯誤
