### ISSUE TITLE
🐛 [BUG] 登入頁面- Navbar右邊的Login需與下方登入按鈕同功能，目前點擊是無反應的狀態。

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1874]
### Time of occurrence

7/31 12:00

### Reproduction URL

https://isunfa.com/users/login

### Reproduction steps

```markdown
1. Go to '登入'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Current Result

按鈕無反應

### Screenshots
<img width="801" alt="截圖 2024-08-02 下午3 02 20" src="https://github.com/user-attachments/assets/c489f99f-132e-4927-8853-6d1badc0b169">

### Expected Result
按鈕可以跳出登入相關的功能的提示

**Comment by arealclimber** [comment]
跟 @Luphia , @StrawHo 確認後，暫時先把右上角的 login 按鈕隱藏起來

**Comment by arealclimber** [comment]
- [ ] 在登入頁面只保留一個登入按鈕
- [ ] 登入之後，保留原有的 avatar

**Comment by arealclimber** [comment]
took 1.5 hrs
done
