### ISSUE TITLE
🐛 [BUG] 日記帳- 日記帳清單日期錯誤

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1875]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

7/29 12:00

### Device

None

### Reproduction URL

https://isunfa.com/users/accounting/journal-list

### Reproduction steps

1. Go to '日記帳'
2. Click on '即將到來事件'

### Current Result

日記帳清單日期錯誤

### Screenshots

![截圖 2024-08-02 下午3 11 41](https://github.com/user-attachments/assets/bee4f56f-401e-486f-bd73-38394451773e)

### Expected Result

日記帳清單日期請顯示傳票正確的日期

**Comment by Julian0701** [comment]
- take 1 hr (8/2)
