### ISSUE TITLE
🐛 [BUG] - from/to的翻譯錯誤(原本翻譯"起訖期間" 應該是翻譯為"供應商/客戶")

### ISSUE THREAD

**Issue by jing12345678910** [CAFECA-IO/iSunFA#1878]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

8/2 16:00

### Device

None

### OS

macOS

### Reproduction URL

http://localhost:3000/users/accounting/journal-list

### Reproduction steps

```markdown
1. Go to '日記帳'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Current Result

```markdown
🐛 [BUG] - from/to的翻譯錯誤(原本翻譯"起訖期間" 應該是翻譯為"供應商/買受人")
```

### Screenshots

![DESCRIPTION](LINK.png)

### Expected Result

```markdown
🐛 [BUG] - from/to的翻譯錯誤(原本翻譯"起訖期間" 應該是翻譯為"供應商/買受人")
```

**Comment by jing12345678910** [comment]
![image](https://github.com/user-attachments/assets/30b8439a-4fb3-4cef-b6ad-7d29cd115e71)

**Comment by TeresaYang00** [comment]
![截圖 2024-08-05 上午11 18 08](https://github.com/user-attachments/assets/7ca3c60e-6cc7-45ad-b3e7-42be6e42516a)

**Comment by jing12345678910** [comment]
上傳會計憑證：上傳成功和刪除 也要翻譯

**Comment by jing12345678910** [comment]
<img width="391" alt="image" src="https://github.com/user-attachments/assets/db02d5ea-f47b-47aa-8170-7e99d69008ab">

**Comment by jing12345678910** [comment]
took 1 hrs
<img width="1184" alt="image" src="https://github.com/user-attachments/assets/a841e1b8-97db-4921-b2f5-22269e7550e8">

done
