### ISSUE TITLE
🐛 [BUG] 日記帳- 查看日記帳頁面沒有顯示憑證圖片

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1880]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

7/31 12:00

### Reproduction URL

https://isunfa.com/users/accounting/10000150

### Reproduction steps

```markdown
1. Go to '日記帳'
2. Click on '新增日記帳'
3. Scroll down to '查看日記帳'
4. See error
```

### Current Result

沒有顯示憑證圖片

### Screenshots

![截圖 2024-08-02 下午4 57 08](https://github.com/user-attachments/assets/3984ebca-5d11-4201-84f2-247e08bec8c2)

### Expected Result

```markdown
可以顯示憑證圖片
```

**Comment by TinyMurky** [comment]
![截圖 2024-08-06 下午6 08 57](https://github.com/user-attachments/assets/7f8e2bac-ceac-4c88-b302-b4524fb6544e)

**Comment by TinyMurky** [comment]
目前可以正常顯示了！
took 0 hours
done
