### ISSUE TITLE
🐛 [BUG] 日記帳- 日記帳清單from/to 表格需帶出傳票上的供應商或客戶的資訊

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1887]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

8/2  12:00

### Device

None

### OS

macOS

### Reproduction URL

https://www.isunfa.com/en/users/accounting/journal-list
### Reproduction steps

```markdown
1. Go to '日記帳'
2. Click on '日記帳清單'
3. Scroll down to '....'
4. See error
```

### Current Result

日記帳清單
from / to 欄位無法顯示對應的資料

### Screenshot
目前狀況
![截圖 2024-08-02 下午6 55 45](https://github.com/user-attachments/assets/69aa2e5e-e519-482c-a276-2b280710e8d5)
設計稿
![截圖 2024-08-02 下午6 51 50](https://github.com/user-attachments/assets/23cc2a90-4738-4575-9a9e-25bbd2afe229)

### Expected Result

帶入傳票的供應商／客戶資訊

![截圖 2024-08-05 下午1 58 28](https://github.com/user-attachments/assets/ba61bf36-46ed-4e9d-9df0-547305365468)
在日記帳的清單

**Comment by arealclimber** [comment]
took 1 hr
done
