### ISSUE TITLE
🐛 [BUG]日記帳 - 會計項目欄位太短

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1888]
### Time of occurrence

8/2 12:00

_No response_

### Reproduction URL

https://www.isunfa.com/en/users/select-company

### Reproduction steps

1. Go to '日記帳'
2. Click on '新增日記帳'
3. Scroll down to '會計科目'

### Current Result

會計科目欄位明顯比其他欄位短

### Screenshots

![截圖 2024-08-02 下午7 10 59](https://github.com/user-attachments/assets/4772d6da-6b37-410f-a4c3-407120ee719f)

### Expected Result

會計科目欄位符合比例

**Comment by Julian0701** [comment]
- take 1 hr, done
