### ISSUE TITLE
🐛 [BUG] 日記帳－上傳多張憑證會出現無法刪除憑證和上傳不成功的問題

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1896]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

8/5 12:00

### Reproduction URL

https://isunfa.com/users/accounting

### Reproduction steps

```markdown
1. Go to '日記帳'
2. Click on '.上傳憑證圖片'
3. Scroll down to '....'
4. See error
```

### Current Result

目前上傳多張憑證無法刪除無法上傳成功

### Screenshots

https://github.com/user-attachments/assets/49ec8348-97ba-4508-bf36-ebb3f7e72607

### Expected Result

上傳憑證不會lag可以多張上傳 
刪除可以直接刪除不會錯誤

**Comment by gibbs-shih** [comment]
看起來是重複刪除ocr, 但畫面有lag無法馬上刷新, 故針對已刪除過的ocr, 如果再按刪除, 顯示 RESOURCE_ALREADY_DELETED 提示
![CleanShot 2024-08-06 at 15 31 25](https://github.com/user-attachments/assets/2227bf15-d0e0-447c-94cf-9d81b2f539ac)

**Comment by gibbs-shih** [comment]
經討論後, 針對已刪除過的ocr, 如果再按刪除, 也是要顯示成功提示 !
修改 getOcrByResultId 邏輯
![CleanShot 2024-08-06 at 15 59 56](https://github.com/user-attachments/assets/db44d4ec-105c-4954-9201-331577ca4140)

**Comment by gibbs-shih** [comment]
![CleanShot 2024-08-06 at 16 05 49](https://github.com/user-attachments/assets/b8500311-19d7-431e-bbb2-3805373be88c)

**Comment by arealclimber** [comment]
- [x]  點了刪除之後 disable delete button，避免重複刪除

**Comment by arealclimber** [comment]
https://github.com/user-attachments/assets/f3a03865-dc03-4073-8900-911ff0f0ad00

**Comment by TinyMurky** [comment]
done
