### ISSUE TITLE
🐛 [BUG]日記帳 - 會計分錄不等於總金額

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1898]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

8/2 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://www.isunfa.com/users/reports/financials

### Reproduction steps

1. Go to '日記帳'
2. Click on '新增日記帳.'
3. Scroll down to '會計分錄
'
5. See error

### Current Result

借方加總金額＝貸方加總金額 不等於總金額

### Screenshots
![截圖 2024-08-05 下午4 22 55](https://github.com/user-attachments/assets/dc83d853-b023-4692-8a33-771f2fe87b2d)

### Expected Result

借方加總金額＝貸方加總金額＝不等於總金額

**Comment by arealclimber** [comment]
- 需考慮有多個貸方 / 借方科目的情況
- [ ] 如果貸方總額跟借方總額不等於總金額的話，畫面顯示錯誤
- [ ] 如果貸方總額跟借方總額不等於總金額，disable submit button

**Comment by TinyMurky** [comment]
我在 #1914 修好後端的部分
想請 @TeresaYang00 檢查

**Comment by arealclimber** [comment]
前端畫面調整跟邏輯檢查
took 2.5 hrs
done

**Comment by TinyMurky** [comment]
修復完成
done
