### ISSUE TITLE
[UI]日記帳功能需補充作帳人資訊(Beta)

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#1899]
Alpha版本的日記帳介面目前並無記錄每筆帳是由誰製作而成，後續於Beta版本需補充作帳人資訊。

**Comment by JodieWu** [comment]
完成時間： 5 hr

https://www.figma.com/design/er65BjKRQhYLBDnYPSL3I4/iSunFA-Mockup-(Beta)?node-id=7004-229435&t=dJDxFgwIkWL8JUj1-1
