### ISSUE TITLE
[UI]日記帳流程調整(Beta)

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#1902]
調整Alpha版本日記帳流程。

新增目標：
- 生成日記帳介面需能在 20 秒內判斷資料是否有錯
- 生成日記帳流程需在 1 分鐘內實現產生會計傳票

**Comment by JodieWu** [comment]
完成時間： 8 hr

https://www.figma.com/design/er65BjKRQhYLBDnYPSL3I4/iSunFA-Mockup-(Beta)?node-id=7004-229435&t=8jnwt3d9DWXTFzfE-1
