### ISSUE TITLE
[FEATURE] - Improve accounting options dropdown menu

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1905]
### Summary

改進會計選項下拉選單

### Tasks

需有搜尋功能，UI 有新的 [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=5459-186168&m=dev)，
作法可參考 `src/components/financial_report_section/financial_report_section.tsx`

![CleanShot 2024-08-05 at 17 44 45](https://github.com/user-attachments/assets/19f1b153-45b8-4a1e-813d-039accd3c5d3)

### Dependencies

Frontend Framework

**Comment by Julian0701** [comment]
- take 4.5 hrs, done
