### ISSUE TITLE
🐛 [BUG] 所有- 非alpha版的功能需隱藏

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1907]
### Time of occurrence

8/5 12:00

1. 報告-列印和下載報告功能 需隱藏
2. 儀表板上方 小鈴鐺通知 需隱藏
3. 儀表板 收藏夾 需隱藏
4. 日記帳清單即將到來事件 需屏蔽
5. 書籤列："新增合約"改成"新增KYC"
6. 已完成事件的invoice list 需隱藏
7. 新增日記帳 事件描述功能 需隱藏
8. Account改成Accounting

**Comment by jing12345678910** [comment]
原本：
<img width="1307" alt="image" src="https://github.com/user-attachments/assets/9c5ba8fb-c004-48d3-81d1-48cfc52ec398">
更改後：
<img width="1322" alt="image" src="https://github.com/user-attachments/assets/7bfe3b22-8d81-4441-9834-760f0c5eaf5e">

**Comment by jing12345678910** [comment]
原本：
<img width="1250" alt="image" src="https://github.com/user-attachments/assets/5bcf9444-4b02-44ac-ba11-b1f6ef38bb33">

**Comment by jing12345678910** [comment]
原本：
<img width="1252" alt="image" src="https://github.com/user-attachments/assets/149b2ca7-73a2-43ce-9f4a-5d2b9e910d10">
<img width="1425" alt="image" src="https://github.com/user-attachments/assets/32832d86-e4d3-4588-9b70-ce83443f90c1">
更改後：

**Comment by jing12345678910** [comment]
原本：
<img width="1353" alt="image" src="https://github.com/user-attachments/assets/ba280753-68ee-40e5-b557-2014cdb75450">

**Comment by TeresaYang00** [comment]
![截圖 2024-08-08 下午2 22 17](https://github.com/user-attachments/assets/72d0dfdd-c56f-45b4-a6a3-376c86ca6c5a)

**Comment by jing12345678910** [comment]
原本：
<img width="1230" alt="image" src="https://github.com/user-attachments/assets/bc820f02-4224-4966-be88-98542f122488">

**Comment by jing12345678910** [comment]
原本：
<img width="1233" alt="image" src="https://github.com/user-attachments/assets/36a3894c-46b2-49ef-b536-cd6e8114cd46">
更改後：

**Comment by jing12345678910** [comment]
原本：
<img width="795" alt="image" src="https://github.com/user-attachments/assets/fbe861c5-472f-4f5c-987b-67789d9dd0b7">

**Comment by jing12345678910** [comment]
took 8 hrs
done
