### ISSUE TITLE
[FEATURE] - voucher create 的時候需要檢查credit 和 debit的加總是否和payment相符

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#1914]
### Summary

voucher create 的時候需要檢查credit 和 debit的加總是否和payment相符
![圖片](https://github.com/user-attachments/assets/f64449fd-9a81-471a-8f8b-52cc893c5290)

### Tasks

```markdown
- voucher create 的時候需要檢查credit 和 debit的加總是否和payment相符
```

**Comment by TinyMurky** [comment]
邏輯應該是小於等於 總金額

**Comment by TinyMurky** [comment]
took 3 hours
done

**Comment by TeresaYang00** [comment]
測試沒問題
