### ISSUE TITLE
[FEATURE] - report financial 需要用invoice的時間去find

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#1917]
### Summary

report financial 需要用invoice的時間去

### Tasks

```markdown
- report financial 需要用invoice的時間去find
```

**Comment by gibbs-shih** [comment]
![CleanShot 2024-08-06 at 10 29 17](https://github.com/user-attachments/assets/5e0f0f03-5939-4324-a15e-13890cb727da)
![CleanShot 2024-08-06 at 10 32 22](https://github.com/user-attachments/assets/6db5aac0-b3e4-4914-9b31-01884110e6dd)

**Comment by gibbs-shih** [comment]
測試：
建立一筆 7/31 日記帳
![CleanShot 2024-08-06 at 11 21 05](https://github.com/user-attachments/assets/c3fc133a-634f-4dbc-9236-c850e9840eb2)

**Comment by gibbs-shih** [comment]
產生報表：
![CleanShot 2024-08-06 at 14 15 17](https://github.com/user-attachments/assets/b295c6ff-6634-4f6a-9d9c-ca0fddad12e4)
![CleanShot 2024-08-06 at 14 15 31](https://github.com/user-attachments/assets/c312a4a6-98e2-4405-b806-ed1333247907)


資產負債表
  - 期間 7/31-7/31
  - 期間 8/01-8/01
綜合損益表
  - 期間 7/30-8/02
  - 期間 8/01-8/02
  - 期間 7/31-7/31
現金流量表
  - 期間 7/31-7/31
  - 期間 7/30-8/01
  - 期間 8/01-8/06
  
  
![CleanShot 2024-08-06 at 12 18 23](https://github.com/user-attachments/assets/5a5f0756-b727-4c26-aa92-c2b8e4673e21)

**Comment by gibbs-shih** [comment]
take 3-4 hr
