### ISSUE TITLE
[Bug] 點選生成後除了跳吐司通知，應轉跳到報告列表頁面，確認該報告有在pending中

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1929]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268217319_

# 點選生成後除了跳吐司通知，應轉跳到報告列表頁面，確認該報告有在pending中

目前是留在原頁面

![Image](https://github.com/user-attachments/assets/52f07e61-e568-401c-b1a3-6c9ffbeffb76)

**Comment by jing12345678910** [comment]
took 2 hrs
點選報告生成之後
<img width="1336" alt="image" src="https://github.com/user-attachments/assets/a496791d-cc7e-4723-a2e9-0ab90292f3d0">
會跳轉到報告列表
<img width="1345" alt="image" src="https://github.com/user-attachments/assets/f0a800db-e080-4c70-b366-67637caf923d">

done
