### ISSUE TITLE
[Bug] 日記帳清單與設計不同

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1930]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268217699_

# 與設計不同

![Image](https://github.com/user-attachments/assets/eaf6c499-e3f8-4b2f-9e57-7a9be64e6c8d)

**Comment by godmmt** [comment]
問題位置：日記帳清單

**Comment by TeresaYang00** [comment]
非alpha請先隱藏

**Comment by jing12345678910** [comment]
took 1 hr
done
