### ISSUE TITLE
[Bug] 在創建公司被引導至 KYC 時，原本創建公司的彈窗不會關掉，且會顯示當前為測試版

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1934]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268223083_

# 在創建公司被引導至 KYC 時，原本創建公司的彈窗不會關掉，且會顯示當前為測試版

![Image](https://github.com/user-attachments/assets/bb91e19f-2061-4dee-aadf-2905a3d607e7)

**Comment by jing12345678910** [comment]
took 2 hrs
點"前往KYC"
<img width="1381" alt="image" src="https://github.com/user-attachments/assets/984245d2-acc7-4276-acec-ad38e1cfe0c4">
不會再出現"試用版彈窗"＆"創建公司彈窗"
<img width="1426" alt="image" src="https://github.com/user-attachments/assets/2c3d6a44-20ed-40f8-a7a5-67b49ea3d9ed">

done
