### ISSUE TITLE
[Bug] 報告顯示錯誤訊息

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1935]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268225009_

# 報告顯示錯誤訊息
且沒有Token ID等資訊是否先隱藏

![Image](https://github.com/user-attachments/assets/41bb4abe-d540-4097-9ad5-ed6d71c9a785)

**Comment by jing12345678910** [comment]
took 2 hrs
報告可以正常顯示，並且先把Token資訊隱藏了
<img width="1354" alt="image" src="https://github.com/user-attachments/assets/fd30c2cc-405f-40c6-ac17-d7d94def5b0f">

done
