### ISSUE TITLE
[Bug] 剛上傳的會計事件被分配到了"即將上傳" 而非"已上傳"

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1936]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268226848_

1. 剛上傳的會計事件被分配到了”即將上傳“而非"已上傳"
2. 搜尋欄icon打架
3. checkbox一開始是隱藏的，點選“select” 才會開啟 （請參考報告列表）

![Image](https://github.com/user-attachments/assets/8d8f62a5-0fa5-43a4-8f7d-2b50e3aa6ed8)

**Comment by TinyMurky** [comment]
![截圖 2024-08-07 下午2 25 38](https://github.com/user-attachments/assets/5ef6842d-4607-4a9c-8763-5d03a8c395d4)
took 4 hours
done
