### ISSUE TITLE
[Bug] 點選公司頭像應該回到該公司的dashboard

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1937]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268228974_
            
# 點選公司頭像應該回到該公司的dashboard
目前是回到選擇公司

![Image](https://github.com/user-attachments/assets/44311591-4a06-4e8b-ab7e-eaadb87c9567)

**Comment by jing12345678910** [comment]
took 2 hrs
點選公司頭像
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/d2cf691a-5847-4141-b3f2-5ce180e80cc1">
跳轉到"儀表板"，而不是跳轉到"選擇公司"
<img width="1424" alt="image" src="https://github.com/user-attachments/assets/c2d5563f-351c-4654-a04a-b5b3e8ce4477">

done
