### ISSUE TITLE
[Bug] filter 收入跟支付用詞要統一

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1938]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268232343_
            

# filter 收入跟支付用詞要統一

![Image](https://github.com/user-attachments/assets/80554c2b-ba84-4ac4-816a-4a54ebbc7047)

**Comment by jing12345678910** [comment]
took 1 hr
選單的翻譯 改成"收入＆支付"，和日記帳列表的翻譯統一
<img width="1351" alt="image" src="https://github.com/user-attachments/assets/fb9f0d23-310b-49bb-b058-c4e84b60799a">

done
