### ISSUE TITLE
[Bug] 切換公司，重新點選試試看時，畫面不會跳轉

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1939]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268234805_

# 切換公司，重新點選試試看時，畫面不會跳轉

![Image](https://github.com/user-attachments/assets/9aab1190-f954-47b0-936d-f8709a4d4143)

**Comment by arealclimber** [comment]
took 0.5 hrs
remaining 1 hr

**Comment by arealclimber** [comment]
https://github.com/user-attachments/assets/0d63753a-2d61-472e-b82c-dacfc39f7bae

**Comment by arealclimber** [comment]
took 3 hrs
done
