### ISSUE TITLE
[Bug] 在Dashboard點選損益表，轉跳至報告頁面後不會幫我自動選好是要產出損益表

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1940]
- [x]  選好產出損益表、現金流量表
- [x]  新增 financial report page 跟 component 的 query
- [x]  更改書籤的路徑
- [x]  隱藏其他還沒開發好的選項，包含分析報表、相機掃描儀

-----
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268243138_
            

# 在Dashboard點選損益表，轉跳至報告頁面後不會幫我自動選好是要產出損益表

![Image](https://github.com/user-attachments/assets/b1c1b55d-10bb-4b0a-9c4e-d8270ad79c53)

![Image](https://github.com/user-attachments/assets/ad26ac66-8102-4f3d-a8ca-b448577070ac)

**Comment by arealclimber** [comment]
took 3 hrs
done
