### ISSUE TITLE
[Bug] 用事件描述新增日記帳時，AI無法判斷日期、事件類型、對象及金額

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1941]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268245649_

# 用事件描述新增日記帳時，AI無法判斷日期、事件類型、對象及金額
只把整句話放在描述區

![Image](https://github.com/user-attachments/assets/b3394cde-3c64-431e-a435-ac8900b65a32)

**Comment by TinyMurky** [comment]
目前用Gemini暫時替代辨識系統
等beta開始後再開新的票處理
