### ISSUE TITLE
[Bug] 新增日記帳少了中途離開的提示，設計稿已補上

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1942]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268255775_
            

# 新增日記帳少了中途離開的提示，設計稿已補上

![Image](https://github.com/user-attachments/assets/b10a152d-1a93-46b1-8221-72a028addfc1)

**Comment by TzuHanLiang** [comment]
<img width="1678" alt="Screenshot 2024-08-09 at 2 45 31 PM" src="https://github.com/user-attachments/assets/f5112c79-a289-41a6-8b5b-dd0a3f745cb8">
took 1.5hrs
done
