### ISSUE TITLE
[Bug] 移轉事件表格與設計稿不符

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1943]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268257448_

# 移轉事件表格與設計稿不符

![Image](https://github.com/user-attachments/assets/0f205fd3-01a6-4c9d-b4d9-8f82816fafd6)

**Comment by TeresaYang00** [comment]
已調整設計稿
