### ISSUE TITLE
[Bug] 若在登入的狀態下中途跳轉至“聯絡我們”，再次從官網回到iSunFA 會出現明明已經登入，卻停在登入介面的狀況

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1944]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268278358_

# 登入

1. 若在登入的狀態下中途跳轉至“聯絡我們”，再次從官網回到iSunFA 會出現明明已經登入，卻停在登入介面的狀況
2. ”登入“標題下方說明文字與設計稿不同，容易誤解成按鈕

![Image](https://github.com/user-attachments/assets/c8817f25-4be9-4379-aab9-a18e9e880be7)

**Comment by arealclimber** [comment]
修改之後，如果公司已選擇，則跳轉到 dashboard page，如果已登入但沒選擇公司，則跳轉到 select company page


https://github.com/user-attachments/assets/9d062f5a-6783-4f2d-9d1f-7f5efa16ebcf

**Comment by arealclimber** [comment]
took 2.5 hrs
done
