### ISSUE TITLE
[Bug] 在日記帳頁面如果切換網頁標籤，回去後會莫名轉跳到dashboard

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1946]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268315010_

# 在日記帳頁面如果切換網頁標籤，回去後會莫名轉跳到dashboard

https://github.com/user-attachments/assets/f86e6a03-335a-4ce2-b4a3-3f6b52d07330

**Comment by arealclimber** [comment]
不只是在journal頁面會發生，在report頁面也會發生

https://github.com/user-attachments/assets/a2b00505-8f43-4c8d-a3e6-8f79dc797a96

**Comment by arealclimber** [comment]
停留在 accounting page 之後跟其他 tab 來回切換，一開始會被導向 dashboard page，最後會被導向 login page


https://github.com/user-attachments/assets/e6187ac3-158f-4532-8bfa-c46410a86d15

**Comment by arealclimber** [comment]
took 1 hr
remaining 1.5 hrs

**Comment by arealclimber** [comment]
https://github.com/user-attachments/assets/7c349590-83cf-44c6-a699-01194d35c493

**Comment by arealclimber** [comment]
took 1 hr
done
