### ISSUE TITLE
[Bug] 明明已經註冊過了登出後重新登入又被要求註冊一次

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1947]
_Originally posted by @JodieWu in https://github.com/CAFECA-IO/iSunFA/issues/1893#issuecomment-2268321035_

# 明明已經註冊過了登出後重新登入又被要求註冊一次

![Image](https://github.com/user-attachments/assets/757740f7-1949-49bd-8b5a-90744a21dc9b)

已累積三個密鑰
![Image](https://github.com/user-attachments/assets/d7c4aee3-a9c0-4be6-8d94-0c8081c751b7)

**Comment by TinyMurky** [comment]
08/07 can't reproduce bug
