### ISSUE TITLE
[FEATURE] - Improve new journal form

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/iSunFA#1960]
### Summary

更新「新增日記帳」的表單

### Tasks

[Mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=5459-182125&m=dev)

**Comment by Julian0701** [comment]
- take 5 hrs, remain 5 hrs

**Comment by Julian0701** [comment]
- 以之後產出的 Beta 版為主，目前先不做

**Comment by TeresaYang00** [comment]
已調整設計
