### ISSUE TITLE
🐛 [BUG] 報告-我的報告清單會閃退

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1976]
### Searched for similar issues

- [X] YES, I have searched for similar issues.

### Time of occurrence

8/8 12:00

### OS

macOS

### Reproduction URL

https://isunfa.com/users/reports/my-reports

### Reproduction steps

```markdown
1. Go to '我的報告清單'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Current Result

我的報告會閃退

### Screenshots

https://github.com/user-attachments/assets/b1ae385c-2d4a-454a-b0c1-040b4db631aa

### Expected Result

清單資料可以清楚地顯示

**Comment by jing12345678910** [comment]
![image](https://github.com/user-attachments/assets/793d2e13-9881-4750-83fe-473cb23c9d32)

**Comment by jing12345678910** [comment]
後端Jacky已經把DB加上前綴(全部回傳都是report?status...)，回傳資料已經沒有問題
<img width="1247" alt="image" src="https://github.com/user-attachments/assets/0a458dc0-a06a-4c48-9e76-0ddde864fde1">

**Comment by jing12345678910** [comment]
前端需要優化的是，不需要重複拿api資料

**Comment by jing12345678910** [comment]
took 2 hrs
done
