### ISSUE TITLE
KYC - replace cancel button with back button

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#1987]
設計稿有修改，將原先的「取消」按鈕，改為「上一步」按鈕。

按下「上一步」會回到前一個步驟，並且保留表單使用者輸入的內容，以便於讓使用者在送出表單之前還可以做修改。

第一頁 Basic Info 的「取消」按鈕就直接拔掉。

[Mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup-(Alpha)?node-id=1345-236127&m=dev)

**Comment by TzuHanLiang** [comment]
https://github.com/user-attachments/assets/1d56b22d-9626-4c9d-b8fc-c63debc3468b

took 2.5hrs
done
