### ISSUE TITLE
🐛 [BUG]日記帳 - 上傳憑證已上傳卻顯示進度條0%

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1988]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

8/8 12:00

### Reproduction URL

https://isunfa.com/users/accounting

### Reproduction steps

1. Go to '新增日記帳'
2. Click on '上傳憑證.'

已成功上傳 但進度條為 0%

### Screenshots

![截圖 2024-08-08 下午3 05 25](https://github.com/user-attachments/assets/1d0a8484-436a-427e-ae99-cfd267aa678d)

### Expected Result
已上傳進度條正常顯示完成100%

**Comment by arealclimber** [comment]
- [ ] 圖片上傳成功就顯示成功，不用等 AI 辨識成功
- [ ] 進度條則為 AI 辨識進度

**Comment by TinyMurky** [comment]
took 6 hours
done
目前改成只有在image上傳時失敗時，會回傳進度0%，其他時候(成功)都會是100
![截圖 2024-08-09 下午2 47 55](https://github.com/user-attachments/assets/ab13cef6-9e64-46d0-a713-b97b19d9cf08)

**Comment by TinyMurky** [comment]
目前改成下面這個樣子
<img width="1280" alt="截圖 2024-08-13 下午5 42 26" src="https://github.com/user-attachments/assets/f6e69588-eaa4-4fbd-bd2c-d7c9bbea34a8">
