### ISSUE TITLE
🐛 [BUG]日記帳 - 新增會計科目代號錯誤

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#1989]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

8/8 12:00

### Reproduction URL

https://www.isunfa.com/users/reports/financials

### Reproduction steps

1. Go to '新增日記帳'

### Current Result

會計課目代號和我新增的不同

### Screenshots
我新增的：
![截圖 2024-08-08 下午4 10 18](https://github.com/user-attachments/assets/e2a189f7-7d76-44d2-b753-25a9d1391f73)
顯示的：
![截圖 2024-08-08 下午3 45 20](https://github.com/user-attachments/assets/c48b4755-992a-45c7-b445-a0329478df12)

### Expected Result

會計課目代號和我新增的相同

**Comment by TinyMurky** [comment]
目前後端的部分回傳會包含完整的code
![截圖 2024-08-08 下午6 11 09](https://github.com/user-attachments/assets/5c0da87f-7e20-4129-a40e-b5c4d333a878)

**Comment by TzuHanLiang** [comment]
<img width="1679" alt="Screenshot 2024-08-09 at 2 51 44 PM" src="https://github.com/user-attachments/assets/91105535-bc38-47d6-aed0-91269a1f6e26">
<img width="1679" alt="Screenshot 2024-08-09 at 2 51 47 PM" src="https://github.com/user-attachments/assets/9308ef39-934d-42da-a922-06d3f74e7eeb">
<img width="384" alt="Screenshot 2024-08-09 at 2 52 09 PM" src="https://github.com/user-attachments/assets/fd30e11c-d1c4-4824-abdf-ee85613e6a2a">
<img width="395" alt="Screenshot 2024-08-09 at 2 52 15 PM" src="https://github.com/user-attachments/assets/1b960e48-c3fa-4e0a-86e6-ff5483c7e568">

took 1hrs
done
