### ISSUE TITLE
[UI]iSunFA登入流程修改(Beta)

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#1993]
從Fido登入方式 修改為 Apple或google帳戶登入方式。

**Comment by JodieWu** [comment]
完成時間：4 hr

https://www.figma.com/design/er65BjKRQhYLBDnYPSL3I4/iSunFA-Mockup-(Beta)?node-id=7034-212180&t=BDEJRScN6zllnvOF-1
