### ISSUE TITLE
[UI]iSunFA收費機制調整(Beta)

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#1995]
原有收費機制可參考 #1901 
後續移除信用卡填寫區域，由第三端顯示該部分，iSunFA網站不顯示此區域。
與 @RexBearIU 討論修正目前收費機制。

**Comment by RexBearIU** [comment]
It takes 1 hour to check the payment flow

done

**Comment by StrawHo** [comment]
### 刪除
- 常用支付
- 付款頁面信用卡資訊

### 修改
- 付款頁面只有價格卡片與推薦碼輸入
- 完成付款後從第三方頁面返回平台的頁面新增(需包含Loading,成功與失敗)
- 訂閱狀態更新Module

**Comment by StrawHo** [comment]
LINK:
https://www.figma.com/design/er65BjKRQhYLBDnYPSL3I4/iSunFA-Mockup-(Beta)?node-id=7036-197611&t=a4Ky5ZsO6QWdNNjI-1

總花費時間約4hr。Done!
