### ISSUE TITLE
[DOCS] - DB change for next sprint till 2024/08/16

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#2030]
### Summary

DB change note

### Tasks

- company_kyc add tax serial number with 2 temp fields

**Comment by RexBearIU** [comment]
- User table extract fido related fields to new authentication table
- authentication table
  - id
  - user_id
  - method // fido, Oath
  - provider // fido, apple, google
  - authdata
user_authentication table
- term table
  - id
  - title
  - type
  - language
  - content
  - version
  - effective_date
  - create_at
  - update_at
  - delete_at
  - temp1
  - temp2
- user_term table

**Comment by TinyMurky** [comment]
增加AccountUser
```
model AccountUser {
  id         Int     @id @default(autoincrement())
  isFavorite Boolean @map("is_favorite")
  userId     Int     @map("user_id")
  accountId  Int     @map("account_id")
  createdAt  Int     @map("created_at")
  updatedAt  Int     @map("updated_at")
  deletedAt  Int?    @map("deleted_at")

  user    User    @relation(fields: [userId], references: [id])
  account Account @relation(fields: [accountId], references: [id])
}
```

account增加
```
favoredBy AccountUser[]
```

user增加
```
favoritedAccount AccountUser[]
```

**Comment by RexBearIU** [comment]
It takes 1.5 hours.

done
