### ISSUE TITLE
[FEATURE] - 規劃Asset要實作的API

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#2048]
### Summary

規劃Asset要實作的API

### Tasks

- [ ] 規劃Asset要實作的API, 像是get, post, list 以及他們的interface

**Comment by TinyMurky** [comment]
![圖片](https://github.com/user-attachments/assets/826009ff-7189-47d5-afca-36bb7a5b7db3)

**Comment by TinyMurky** [comment]
![圖片](https://github.com/user-attachments/assets/a9184ec5-5dfe-4a33-ab66-a03679d848f1)

**Comment by TeresaYang00** [comment]
已調整設計
