### ISSUE TITLE
NavBar (mobile)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#206]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/a9beb5fb-ab00-4d15-b9d6-cc356beae89a)

[mockup](https://www.figma.com/file/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?type=design&node-id=533-1538608&mode=dev)

**Comment by Julian0701** [comment]
- take 3 hrs
