### ISSUE TITLE
[FEATURE] - Help 401 report developmenet on navigation from my-reports page to single report page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#2065]
### Summary

幫助 401 報告開發從我的報告頁面導航到單一報告頁面

### Tasks

- [ ] 查找缺少哪些要素導致 404 

### Dependencies

Frontend Framework

**Comment by jing12345678910** [comment]
問題：
從『我的報告』點進『一般營業人銷售額與稅額申報書(401)』後，出現進『Application error: a client-side exception has occurred (see the browser console for more information).』
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/3c6cb9b7-e400-4449-9d1d-fd02125cd4e6">

**Comment by jing12345678910** [comment]
問題：
導入的頁面是http://localhost:3000/users/reports/financials/view/10000194?report_type=401
但是console有錯誤如下：

1. TypeError: Cannot read properties of undefined (reading 'name')
    at L ([reportId]-5852a0aa387780b1.js:1:13544)
    at ad (framework-0995a3e8436ddc4f.js:9:58401)
    at i (framework-0995a3e8436ddc4f.js:9:119366)
    at oO (framework-0995a3e8436ddc4f.js:9:99019)
    at framework-0995a3e8436ddc4f.js:9:98886
    at oF (framework-0995a3e8436ddc4f.js:9:98893)
    at ox (framework-0995a3e8436ddc4f.js:9:95645)
    at oS (framework-0995a3e8436ddc4f.js:9:94200)
    at x (framework-0995a3e8436ddc4f.js:33:1364)
    at MessagePort.T (framework-0995a3e8436ddc4f.js:33:1894)
a6 @ framework-0995a3e8436ddc4f.js:9
a.componentDidCatch.t.callback @ framework-0995a3e8436ddc4f.js:9
lX @ framework-0995a3e8436ddc4f.js:9
uY @ framework-0995a3e8436ddc4f.js:9
e @ framework-0995a3e8436ddc4f.js:9
(anonymous) @ framework-0995a3e8436ddc4f.js:9
oI @ framework-0995a3e8436ddc4f.js:9
oS @ framework-0995a3e8436ddc4f.js:9
x @ framework-0995a3e8436ddc4f.js:33
T @ framework-0995a3e8436ddc4f.js:33

2. TypeError: Cannot read properties of undefined (reading 'name')
    at L ([reportId]-5852a0aa387780b1.js:1:13544)
    at ad (framework-0995a3e8436ddc4f.js:9:58401)
    at i (framework-0995a3e8436ddc4f.js:9:119366)
    at oO (framework-0995a3e8436ddc4f.js:9:99019)
    at framework-0995a3e8436ddc4f.js:9:98886
    at oF (framework-0995a3e8436ddc4f.js:9:98893)
    at ox (framework-0995a3e8436ddc4f.js:9:95645)
    at oS (framework-0995a3e8436ddc4f.js:9:94200)
    at x (framework-0995a3e8436ddc4f.js:33:1364)
    at MessagePort.T (framework-0995a3e8436ddc4f.js:33:1894)
Z @ main-b2ba8e897045e97e.js:1
fn @ main-b2ba8e897045e97e.js:1
componentDidCatch @ main-b2ba8e897045e97e.js:1
a.componentDidCatch.t.callback @ framework-0995a3e8436ddc4f.js:9
lX @ framework-0995a3e8436ddc4f.js:9
uY @ framework-0995a3e8436ddc4f.js:9
e @ framework-0995a3e8436ddc4f.js:9
(anonymous) @ framework-0995a3e8436ddc4f.js:9
oI @ framework-0995a3e8436ddc4f.js:9
oS @ framework-0995a3e8436ddc4f.js:9
x @ framework-0995a3e8436ddc4f.js:33
T @ framework-0995a3e8436ddc4f.js:33

3.<div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex; color: rgb(240, 223, 215); font-family: monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start; margin-top: -1px;"><div class="console-message-stack-trace-wrapper" aria-label="main-b2ba8e897045e97e.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; track: click" role="link" tabindex="-1" title="http://localhost:3000/_next/static/chunks/main-b2ba8e897045e97e.js:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;"><br class="Apple-interchange-newline">main-b2ba8e897045e97e.js:1</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">A client-side exception has occurred, see here for more info: <button class="devtools-link text-button link-style" jslog="Link; context: url; track: click" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">https://nextjs.org/docs/messages/client-side-exception-occurred</button></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: monospace; --source-code-font-size: 11px; --source-code-font-family: monospace; width: 414px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | Z | @ | main-b2ba8e897045e97e.js:1
-- | -- | -- | --
  | fn | @ | main-b2ba8e897045e97e.js:1
  | componentDidCatch | @ | main-b2ba8e897045e97e.js:1
  | a.componentDidCatch.t.callback | @ | framework-0995a3e8436ddc4f.js:9
  | lX | @ | framework-0995a3e8436ddc4f.js:9
  | uY | @ | framework-0995a3e8436ddc4f.js:9
  | e | @ | framework-0995a3e8436ddc4f.js:9
  | (anonymous) | @ | framework-0995a3e8436ddc4f.js:9
  | oI | @ | framework-0995a3e8436ddc4f.js:9
  | oS | @ | framework-0995a3e8436ddc4f.js:9
  | x | @ | framework-0995a3e8436ddc4f.js:33
  | T | @ | framework-0995a3e8436ddc4f.js:33

</span></div></div></div></div><button class="hover-button" aria-label="Understand this error" tabindex="0" jslog="Action; context: explain.console-message.hover; track: click" style="box-sizing: border-box; min-width: var(--width); min-height: var(--width); font-family: var(--default-font-family); font-size: inherit; --width: 24px; align-items: center; background-color: var(--sys-color-cdt-base-container); border-radius: 50%; border: none; box-shadow: rgba(0, 0, 0, 0.15) 0px 1px 3px 1px, rgba(0, 0, 0, 0.3) 0px 1px 2px 0px; color: var(--sys-color-primary); height: var(--width); justify-content: center; margin: 0px; max-height: var(--width); max-width: var(--width); overflow: hidden; padding: 4px 3px 4px 5px; position: absolute; right: 6px; display: block; width: var(--width); orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><devtools-icon role="presentation" name="lightbulb-spark" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 16px; height: 16px; color: var(--sys-color-primary); vertical-align: sub; position: relative; box-sizing: border-box; min-width: 16px; min-height: 16px;"><br class="Apple-interchange-newline">

**Comment by jing12345678910** [comment]
初步判斷可能是因為src/pages/users/reports/financials/view/[reportId].tsx這一頁的問題，傳進report_type參數 但沒有render出來

**Comment by jing12345678910** [comment]
找到src/interfaces/report_type.ts
發現報告類別沒有定義401(如下)
export enum BaifaReportTypeToReportType {
  balance = 'balance_sheet',
  'comprehensive-income' = 'comprehensive_income_statement',
  'cash-flow' = 'cash_flow_statement',
  //  'change-in-equity' = 'change_in_equity_statement'
}

於是補上
export enum ReportTypeToBaifaReportType {
  balance_sheet = 'balance',
  comprehensive_income_statement = 'comprehensive-income',
  cash_flow_statement = 'cash-flow',
  report_401 = 'report-401',
  //  change_in_equity_statement = 'change-in-equity'
}

**Comment by jing12345678910** [comment]
上述這樣修改完之後，從『我的報告』點進『一般營業人銷售額與稅額申報書(401)』，出現『404
This page could not be found.』
<img width="711" alt="image" src="https://github.com/user-attachments/assets/2bf2222d-8133-4012-a5cc-4b2eb7687fae">

**Comment by jing12345678910** [comment]
問題：
導入的頁面是http://localhost:3000/users/reports/financials/view/10000194?report_type=report-401
但是console有錯誤如下：


<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(240, 223, 215); font-family: monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; track: click" role="link" tabindex="-1" title="http://localhost:3000/_next/static/chunks/framework-0995a3e8436ddc4f.js:9" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;"><br class="Apple-interchange-newline">framework-0995a3e8436ddc4f.js:9</button> <devtools-request-link-icon class="resource-links" style="display: inline-block; white-space: nowrap; color: inherit; font-size: inherit; font-family: inherit; box-sizing: border-box; min-width: 0px; min-height: 0px; margin-top: -1px; margin-bottom: -2px;"><button class=" link " title="Click to open the network panel and show request for URL: http://localhost:3000/users/reports/10000194/401-report" jslog="Link; context: request; track: click" style="border: none; background: transparent; margin: 0px; padding: 0px; cursor: pointer;"><devtools-icon name="arrow-up-down-circle" role="presentation" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 16px; height: 16px; color: var(--icon-link); vertical-align: middle; position: relative;"><span style="display: block; width: 16px; height: 16px; background-color: currentcolor; mask: var(--icon-url) center /contain no-repeat; --icon-url: var(--image-file-arrow-up-down-circle);"></span></devtools-icon></button></devtools-request-link-icon> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">GET <button class="devtools-link text-button link-style" jslog="Link; context: network-request; track: click" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">http://localhost:3000/users/reports/10000194/401-report</button> 404 (Not Found)</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(240, 223, 215); font-family: monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: monospace; --source-code-font-size: 11px; --source-code-font-family: monospace; width: 414px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | e | @ | framework-0995a3e8436ddc4f.js:9
-- | -- | -- | --
  | uK | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | (anonymous) | @ | framework-0995a3e8436ddc4f.js:9
  | oI | @ | framework-0995a3e8436ddc4f.js:9
  | oS | @ | framework-0995a3e8436ddc4f.js:9
  | x | @ | framework-0995a3e8436ddc4f.js:33
  | T | @ | framework-0995a3e8436ddc4f.js:33

</span></div>

**Comment by jing12345678910** [comment]
更改src/components/view_financial_section/view_financial_section.tsx

**Comment by jing12345678910** [comment]
build 完 start 後
<img width="744" alt="image" src="https://github.com/user-attachments/assets/9c6ad348-70c7-477e-8484-e9a04e36f667">

導引到的連結是http://localhost:3000/users/reports/financials/view/10000194?report_type=report-401

console有錯誤
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(240, 223, 215); font-family: monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; track: click" role="link" tabindex="-1" title="http://localhost:3000/_next/static/chunks/framework-0995a3e8436ddc4f.js:9" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;"><br class="Apple-interchange-newline">framework-0995a3e8436ddc4f.js:9</button> <devtools-request-link-icon class="resource-links" style="display: inline-block; white-space: nowrap; color: inherit; font-size: inherit; font-family: inherit; box-sizing: border-box; min-width: 0px; min-height: 0px; margin-top: -1px; margin-bottom: -2px;"><button class=" link " title="Click to open the network panel and show request for URL: http://localhost:3000/users/reports/10000194/401-report" jslog="Link; context: request; track: click" style="border: none; background: transparent; margin: 0px; padding: 0px; cursor: pointer;"><devtools-icon name="arrow-up-down-circle" role="presentation" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 16px; height: 16px; color: var(--icon-link); vertical-align: middle; position: relative;"><span style="display: block; width: 16px; height: 16px; background-color: currentcolor; mask: var(--icon-url) center /contain no-repeat; --icon-url: var(--image-file-arrow-up-down-circle);"></span></devtools-icon></button></devtools-request-link-icon> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">GET <button class="devtools-link text-button link-style" jslog="Link; context: network-request; track: click" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">http://localhost:3000/users/reports/10000194/401-report</button> 404 (Not Found)</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(240, 223, 215); font-family: monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: monospace; --source-code-font-size: 11px; --source-code-font-family: monospace; width: 414px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | e | @ | framework-0995a3e8436ddc4f.js:9
-- | -- | -- | --
  | uK | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | uQ | @ | framework-0995a3e8436ddc4f.js:9
  | uq | @ | framework-0995a3e8436ddc4f.js:9
  | (anonymous) | @ | framework-0995a3e8436ddc4f.js:9
  | oI | @ | framework-0995a3e8436ddc4f.js:9
  | oS | @ | framework-0995a3e8436ddc4f.js:9
  | x | @ | framework-0995a3e8436ddc4f.js:33
  | T | @ | framework-0995a3e8436ddc4f.js:33

</span></div>

**Comment by jing12345678910** [comment]
重新拉遠端的develop下來merge

**Comment by jing12345678910** [comment]
我打的api是http://localhost:3000/users/reports/10000194/401-report
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/15350b03-b658-4209-a3c6-dd41e2bbe8db">

---
但是文件要的api是GET `/company/:companyId/report/:reportId`
<img width="1175" alt="image" src="https://github.com/user-attachments/assets/9436cb51-7401-4e4f-aa05-e8cfb4ab443c">

**Comment by jing12345678910** [comment]
_把原本的代碼(由本地端生成報告)_
const fetchReport = async () => {
  if (selectedCompany) {
    const reportData = await generate401Report(
      selectedCompany.id,
      Date.now() / 1000,
      Date.now() / 1000
    );
    setReport401(reportData);
  }
};

_改成(調用api生成報告)_
 const fetchReport = async () => {
      if (selectedCompany && reportId) {
        const companyId = selectedCompany.id;

        try {
          const response = await fetch(
            `http://localhost:3000/company/${companyId}/report/${reportId}`,
            {
              method: 'GET',
              headers: {
                'Content-Type': 'application/json',
              },
            }
          );

          if (!response.ok) {
            throw new Error(`Error fetching report: ${response.statusText}`);
          }

          const reportData = await response.json();
          setReport401(reportData);
        } catch (error) {
          // eslint-disable-next-line no-console
          console.error('Failed to fetch report:', error);
        }
      }
    };

**Comment by jing12345678910** [comment]
把report_401
<img width="895" alt="image" src="https://github.com/user-attachments/assets/b6fbb669-9b1f-4ec9-93fc-e8d2fce0153e">
改名為401-report
<img width="330" alt="image" src="https://github.com/user-attachments/assets/7c488849-697b-42d1-841b-c6fe3b49e536">

**Comment by jing12345678910** [comment]
APIHandler.ts
function APIHandler<Data>(
  apiName: IAPIName,
  options: IAPIInput = {
    header: {},
    body: {},
    params: {},
    query: {},
  },
  triggerImmediately: boolean = false,
  cancel: boolean = false
): IAPIResponse<Data> {
  const apiConfig = APIConfig[apiName];
  if (!apiConfig) throw new Error(`API ${apiName} is not defined`);

  checkInput(apiConfig, options);

  if (apiConfig.useWorker) {
    return useAPIWorker<Data>(apiConfig, options, triggerImmediately, cancel);
  } else {
    return useAPI<Data>(apiConfig, options, triggerImmediately, cancel);
  }
}

**Comment by jing12345678910** [comment]
took 5 hrs
done
