### ISSUE TITLE
app navigator component (mobile)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#207]
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/506860b8-8d0e-4dd5-9ea2-4bf310c91090)

[mockup](https://www.figma.com/file/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?type=design&node-id=533-1538608&mode=dev)

**Comment by Julian0701** [comment]
- take 3 hrs
