### ISSUE TITLE
[UI] iSunFA Beta 報告功能 Wireframe

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#2110]
報告功能 Wireframe。包含財務報告與稅務報告

**Comment by JodieWu** [comment]
完成時間： 5 hr

https://www.figma.com/design/GAcDZhQtnuX6ztMu1adsKm/iSunFA-(Beta)?node-id=11-24401&t=mJsZdzuibH0XvWUb-1
