### ISSUE TITLE
[UI] Module 清單開票

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#2198]
清點須製作的Module並開票

- [ ] #2266
- [ ] #2267
- [ ] #2270
- [ ] #2271
- [ ] #2272
- [ ] #2276 
- [ ] #2277 
- [ ] #2278 
- [ ] #2279 
- [ ] #2280
- [ ] #2281 
- [ ] #2282 
- [ ] #2283 
- [ ] #2284 
- [ ] #2285
- [ ] #2286 
- [ ] #2287

**Comment by StrawHo** [comment]
- [ ] [UI] Dashboard-Module

**Comment by JodieWu** [comment]
完成時間：2 hr
