### ISSUE TITLE
🐛 [BUG] - 新增日記帳頁面 - API Error - api/v1/company/:companyId/ocr 400 Error

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#2204]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

Today 9:00 AM

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.com/users/accounting

### Reproduction steps

```markdown
1. Go to '新增日記帳'
2. 如果已上傳過憑證
3. see error '列出憑證失敗'
4. 如果沒有已上傳過的憑證 '上傳憑證'
5. See error
```

### Current Result

```markdown
'列出憑證失敗'
```

### Screenshots

<img width="1680" alt="Screenshot 2024-08-27 at 12 45 58 PM" src="https://github.com/user-attachments/assets/adaf1c8f-fbba-4985-a9b1-66b097879327">

### Expected Result

```markdown
不會出現 '列出憑證失敗'
```

**Comment by TinyMurky** [comment]
took 5 hours
done
![image](https://github.com/user-attachments/assets/e3b5376c-5def-43c0-b7f0-ceafc7d399c1)
