### ISSUE TITLE
🐛 [BUG] - 創建過的公司，刪除後再創建，會顯示Error Code : 500ISF0009

### ISSUE THREAD

**Issue by jing12345678910** [CAFECA-IO/iSunFA#2241]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

8/30 15:00

### Device

None

### OS

macOS

### Reproduction URL

http://localhost:3000/users/select_company

### Reproduction steps

```markdown
1. 刪除已經創建的公司
2. Go to 'select_company'
3. Click on '創建公司'
4. 輸入被刪除過的公司
```

### Current Result

```markdown
會顯示Error Code : 500ISF0009
```

### Screenshots

![image](https://github.com/user-attachments/assets/212784ff-0fc0-4b5e-8913-d6627e901a22)
因為不顯示Error Code給用戶看，因此前端先改成如下這樣
![image](https://github.com/user-attachments/assets/5d683a77-355f-4a59-bccb-f21509112001)

### Expected Result

```markdown
顯示明確訊息讓用戶知道為什麼無法創建公司
```

**Comment by RexBearIU** [comment]
It takes 2 hours.

done
