### ISSUE TITLE
[Presentation] iSunFA Beta WF 簡報

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#2251]
w35 目標完成 iSunFA Beta wireframe，需確保以下事項：
1. 提供 3 個 UX 特色亮點
2. 解決 5 個以上用戶訪談發現的問題
3. 預想 5 個以上用戶實際導入 iSunFA 可能遇到的問題並提供設計解決方案

針對上述項目製作會議簡報

**Comment by JodieWu** [comment]
部分完成 4 hr

https://www.figma.com/slides/wquDadvtyxH4hXg9jecdSE/iSunFA-Beta-Release?node-id=1-38&t=dv5i1zJF7fwyLIlx-1

**Comment by StrawHo** [comment]
### 改善的Pain Point 

- 搜尋會計科目的方式-調整下拉式選單選擇傳票會計科目的方式...
- Dashboard資訊-調整更符合記帳士所需的工作資訊與功能

### 五個情境的部分：

- 記帳士在使用iSunFA的過程會遇到不熟悉系統的問題，這時候可以使用AI小幫手，AI小幫手會針對用戶目前處於的頁面以及所遇到的問題提供最佳解答與指南協助。
- 記帳士想了解目前他還有哪些任務未完成，這時候可以查看Dashboard任務進度來確定還有哪些公司有未開立傳票，也可以直接開啟指定公司的帳本，來查看該公司有哪些新上傳的憑證或者是哪些憑證未開立傳票。
- 記帳士想要調整會計相關的設定不知道iSunFA系統的設定內容將會計相關參數放置在哪部分以及能修改的部分又有哪些？在這次Beta版本，iSunFA的設定分類成三種「一般設定」、「會計設定」、「對象設定」。記帳士可根據其需求更容易找到設定的參數在哪，不會在設定裡迷路，在「會計設定」中除了會計相關參數設定，還多了指定情境使用使用預設科目

**Comment by JodieWu** [comment]
完成時間： 5 hr

https://www.figma.com/slides/wquDadvtyxH4hXg9jecdSE/iSunFA-Beta-Release?node-id=1-38&t=Vc1YqeoNZ6IMstAx-1
