### ISSUE TITLE
[FEATURE] - Include missing internationalization

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#2260]
### Summary

補上 i18n

### Tasks

- ~接續 #2130 檢查 24/274 個檔案(components)，然後把標註缺漏的翻譯檔補上~
- 將附有以下標注的檔案補上缺漏的翻譯檔
```tsx
ToDo: (20240902 - Shirley) i18n
or
ToDo: (20240902 - Shirley) 整個 i18n
```

### Dependencies

Frontend Framework

**Comment by jing12345678910** [comment]
took 3 hrs
已經把『 ToDo: (20240902 - Shirley) i18n 』 ＆ 『 ToDo: (20240902 - Shirley) 整個 i18n 』清掉Todo且補上翻譯
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/14e013df-7a5b-4e41-998f-cd234a9f6dd3">

done
