### ISSUE TITLE
[Meeting] Beta Release

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#2293]
[會議連結](https://github.com/CAFECA-IO/EventReport/blob/main/meeting/20240904_isunfa_beta.md)

**Comment by StrawHo** [comment]
### 後續補充設計

- 記帳士個人 KYC
- Landing page Redesign
- 互動式報告
- 個人資料設定補充返回角色選擇(預覽功能畫面)
- 填寫用戶資訊時提醒用戶儲存資料中
