### ISSUE TITLE
[FEATURE] - Set up ipfs node in cafeca.local-002

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#2303]
Set up ipfs node in cafeca.local-002

**Comment by RexBearIU** [comment]
Transfer to Murky due to resign.

**Comment by TinyMurky** [comment]
目前架好且測試完成本機可以用

https://github.com/user-attachments/assets/2600fcca-5a02-4e81-9b1e-665c6f2d3080

**Comment by TinyMurky** [comment]
發現檔案只是存在memory
需要在peerHost pin
先移轉到下一張票
- #3437
