### ISSUE TITLE
研究 : SVG Sprite 搭配 use

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#2333]
嘗試看看這個：https://kurtextrem.de/posts/svg-in-js#svg-sprites--using-use

看能否解決 svg 在 jsx 程式碼中過長的困擾

**Comment by godmmt** [comment]
在處理 #2319 的時候，發現專案中有太多 svg elements 都是有使用偽類的屬性

所以就再研究看看
看還有沒有辦法可以解決svg 在 jsx 程式碼中過長的困擾

研究的過程有看到 SVG Sprite
好像可以 (?)
所以就花一些時間研究

**Comment by godmmt** [comment]
- https://kurtextrem.de/posts/svg-in-js

**Comment by godmmt** [comment]
拿 iSunCoin 測試

有成功一個
但是過程中因為當初的 SVG tag 已有被污染了
開發人員會為了調整樣式因此可能會刪除部分 `fill` 屬性，所以要再修改，沒辦法秒切換，要花時間嘗試。

註解的部分是原本的地球 icon
下方是使用 `use` 
![截圖 2024-09-10 下午6 31 34](https://github.com/user-attachments/assets/ecaef481-6ba4-41d4-b9e4-4322a7ff6e9e)

**Comment by godmmt** [comment]
- [ ] 明天在 iSunFA 拿幾個例子嘗試看看
- [ ] 先確認跟主管這方法是否 ok
- [ ] 還想確認是否有必要這樣做，因為這整個專案處理下來是個工程，並且 iSunFA 目前 `run dev` 真的好慢（但也可能是電腦太慢的問題）

**Comment by godmmt** [comment]
# `<use>` 搭配 `<symbol>`
查資料後發現，
如果設計稿提供的 SVG 中沒有 `<symbol>` 標籤，
有以下方式處理（最佳解是**手動加上 `<symbol>` 標籤**）：


### 方法 1：將 `id` 屬性加在 `<svg>` 上（正確但不推薦）
可以直接在 SVG 的 `<svg>` 標籤上加上 `id` 屬性，然後用 `<use>` 來引用該 SVG：

```html
<svg id="globe" width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" clip-rule="evenodd" d="省略" fill="currentColor"/>
</svg>
```

然後，你可以像這樣引用它：

```html
<svg className="w-6 h-6 text-blue-500">
  <use href="#globe" />
</svg>
```

這樣雖然可行，但這不是最推薦的做法，因為每次你用 `<use>` 來引用 SVG 時，原始的 SVG 元素必須存在於 DOM 中。如果你的 SVG 很大或需要多次引用，這樣會讓你的 DOM 較為冗長。

### 方法 2：使用 `<symbol>`（推薦的做法）
通常，將 SVG 內容放入 `<symbol>` 標籤是更好的做法，因為這樣可以避免重複的 DOM 元素出現在頁面中。你可以手動將設計師提供的 SVG 包裝在 `<symbol>` 中，這樣只需要定義一次，並可以多次使用。

**步驟 1：將 SVG 轉換為 `<symbol>`**

你可以將設計師提供的 SVG 改成這樣：

```html
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="globe" width="32" height="32" viewBox="0 0 32 32" fill="none">
    <path fill-rule="evenodd" clip-rule="evenodd" d="省略" fill="currentColor"/>
  </symbol>
</svg>
```

**步驟 2：使用 `<use>` 來引用**

然後你可以用 `<use>` 來引用它，並且可以多次重複使用：

```jsx
<svg className="w-6 h-6 text-blue-500">
  <use href="#globe" />
</svg>
```

### 方法 3：直接內嵌 SVG（適合不需要多次使用的情況）
如果這個 SVG 不會在多處重複使用，你可以直接內嵌原始的 SVG 程式碼，並使用 TailwindCSS 或其他 CSS 工具來樣式化：

```jsx
<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-6 h-6 text-blue-500">
  <path fill-rule="evenodd" clip-rule="evenodd" d="省略" fill="currentColor" />
</svg>
```

這種方法最簡單，不需要改動設計師的原始程式碼，但如果 SVG 很大或需要多次使用，這可能會導致程式碼冗長。

### 結論
- **加 `id` 屬性**：可行但不推薦，因為每次都會在 DOM 中保留重複的 SVG 元素。
- **使用 `<symbol>`**：最推薦的方法，可以讓你定義一次 SVG，並在需要的地方重複使用，節省 DOM 空間。
- **內嵌 SVG**：適合不需要多次使用的情況，簡單但可能增加程式碼體積。

如果你需要讓 SVG 更具可重複性和靈活性，最好是手動將設計師的 SVG 包裝進 `<symbol>` 中。如果不需要重複使用或 SVG 比較小，內嵌的方法也完全可以使用。

**Comment by godmmt** [comment]
今天再打開專案，圖案卻顯示不出來。

代表我用的方法，沒有實驗出一個穩定性結果，所以不採取此方式。

**Comment by godmmt** [comment]
- 0910: took 3.5 hours
- 0911: took 1.5 hours

Total time: 5

done.

**Comment by godmmt** [comment]
疑惑：不懂這種為了實作而去「研究」的工作單，應該放在哪一個 Label ？

是 enhancement 嗎
還是 documentation？
但我也沒有產出一份「文件」

實在好困惑 😵😵😵

**Comment by Luphia** [comment]
是 document，可作為 KM
