### ISSUE TITLE
[UI] Mockup - AI Helper各功能畫面

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#2371]
AI Helper在功能畫面協助 Mockup
@JodieWu :主要功能 記帳與資產等 會發生的常見問題
@StrawHo : Dashboard setting Report 會發生的常見問題

**Comment by StrawHo** [comment]
Dashboard 常見問題:
如何建立新的公司(帳簿)?
Dashboard有使用說明嗎?
如何連結我的行事曆?
如何創建新角色?

Report 常見問題:
如何產生報表?
資產負債表的「展開」是什麼功能?
在iSunFA上的報表可以匯出嗎?

Setting 常見問題:
如何新增會計科目?
刪除帳號後可以復原嗎?
公司資訊可以編輯修改嗎?

**Comment by JodieWu** [comment]
### Add New Voucher 常見問題:

- AI如何幫助我建立傳票?
- 如何附上憑證?
- 如何建立週期性傳票?
- 如何新增會計科目？



### Voucher list 常見問題:

- 我要如何匯出傳票
- 我要如何刪除傳票
- 我要如何刪除尚未開立的週期性傳票
- 我想修改傳票內容

### Asset list常見問題:

- 如何新增資產?
- 如何報廢資產?
- 可以刪除資產嗎?

### Payable/Receivable list常見問題:

- 如何新增應收付帳款
- 如何為應收付帳款沖賬

### Upload Certificate常見問題:

- 如何上傳憑證
- 手機掃描憑證該如何操作
- 如何新增稅務資料
- 要如何刪除憑證
- 如何為憑證開立傳票

**Comment by StrawHo** [comment]
### 常見問題建立&Ai Helper Module 建立

@StrawHo 約4hr。
@JodieWu 約4hr。
total 約8hr

LINK:
https://www.figma.com/design/qSOAuNX7hxVQaKD51ghONu/iSunFA-Mockup-(Beta)?node-id=1-478&t=oaouLP4TufRJ9fKU-1

Done!
