### ISSUE TITLE
Monthly sales block

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/iSunFA#238]
![截圖 2024-04-17 上午11 05 25](https://github.com/CAFECA-IO/iSunFA/assets/114177573/d0ac40d4-db19-49f7-a196-271567aa4fc2)

**Comment by Julian0701** [comment]
- take 5 hrs
<img width="903" alt="image" src="https://github.com/CAFECA-IO/iSunFA/assets/114177573/31aaf967-347c-498b-b906-2fa5f518ad72">

- RWD 未完成
- 樣式和設計稿有出入

**Comment by TeresaYang00** [comment]
設計已更改 不用再執行
