### ISSUE TITLE
Project - Report detail page

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/iSunFA#243]
![截圖 2024-06-17 上午11 57 18](https://github.com/CAFECA-IO/iSunFA/assets/114177573/0fa3d10e-dda4-4358-808d-76eb3fff8eb4)

ISFMK00060

**Comment by Julian0701** [comment]
- take 1 hr, remain 4 hrs

**Comment by TeresaYang00** [comment]
已不用執行
