### ISSUE TITLE
🐛 [BUG] -報告畫面無法顯示出現登入的畫面

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#2723]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

10/7 13:00

### Device

None

### Reproduction URL

https://isunfa.com/users/reports/financials/view/10000043?report_type=comprehensive-income

### Reproduction steps

```markdown
1. Go to '我的報告'
2. Click on '報告'
3. Scroll down to '....'
4. See error
```

### Current Result

```markdown
出現登入畫面
```

### Screenshots

![截圖 2024-10-07 下午3 25 36](https://github.com/user-attachments/assets/9aab999f-4148-4892-9251-6284410d1c56)

### Expected Result

```markdown
正常產生報告畫面
```

**Comment by godmmt** [comment]
### 排查報告相關元件

- src/pages/users/reports/financials/view/[reportId].tsx

**Comment by godmmt** [comment]
dev branch run build & start

選擇公司頁面
這支 API 失敗 : GET http://localhost:3000/api/v1/company 500 (Internal Server Error)

```
{
    "powerby": "iSunFA v0.8.2+34",
    "success": false,
    "code": "500ISF0009",
    "message": "Prisma related error",
    "payload": null
}
```

**Comment by godmmt** [comment]
原因是 DB 有改

所以需要執行

$ npx prisma generate 
$ npx prisma migrate reset

再重新 run build & run start

**Comment by godmmt** [comment]
userCtx return 

isAuthLoading: false 
selectedCompany: {id: 10000000, name: '1234', taxId: '1234', tag: 'all', imageFileId: 10000001, …}

**Comment by godmmt** [comment]
API REPORT_GET_BY_ID return 

data (reportFinancial) :  undefined 

isLoading (getReportFinancialIsLoading): undefined

**Comment by godmmt** [comment]
API REPORT_GET_BY_ID return 

data (reportFinancial) :  undefined 

isLoading (getReportFinancialIsLoading): true

**Comment by godmmt** [comment]
API REPORT_GET_BY_ID return 

data (reportFinancial) :  {company: {…}, reportType: 'balance_sheet', preDate: {…}, curDate: {…}, details: Array(91), …}company: {id: 10000000, code: '1234', name: '1234'}curDate: {from: 1728316800, to: 1728403199}details: Array(91)0: {code: '', name: '資產', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}1: {code: '', name: '流動資產', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}2: {code: '1100', name: '現金及約當現金', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}3: {code: '1110', name: '透過損益按公允價值衡量之⾦融資產－流動', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}4: {code: '1120', name: '透過其他綜合損益按公允價值衡量之金融資產－流動', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}5: {code: '1136', name: '按攤銷後成本衡量之金融資產－流動', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}6: {code: '1139', name: '避險之⾦融資產－流動', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}7: {code: '1170', name: '應收帳款淨額', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}8: {code: '1180', name: '應收帳款－關係⼈淨額', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}9: {code: '1210', name: '其他應收款－關係⼈', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}10: {code: '130X', name: '存貨', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}11: {code: '1470', name: '其他流動資產', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}12: {code: '1476', name: '其他金融資產－流動', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}13: {code: '1479', name: '其他金融資產－其他', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}14: {code: '11XX', name: '流動資產合計', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}15: {code: '', name: '非流動資產', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}16: {code: '1510', name: '透過損益按公允價值衡量之⾦融資產－非流動', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}17: {code: '1517', name: '透過其他綜合損益按公允價值衡量之⾦融資產－非流動', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}18: {code: '1535', name: '按攤銷後成本衡量之金融資產－非流動', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}19: {code: '1550', name: '採用權益法之投資', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}20: {code: '1600', name: '不動產、廠房及設備', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}21: {code: '1755', name: '使⽤權資產', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}22: {code: '1780', name: '無形資產', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}23: {code: '1840', name: '遞延所得稅資產', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}24: {code: '1900', name: '其他非流動資產', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}25: {code: '1920', name: '存出保證⾦', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}26: {code: '1990', name: '其他非流動資產－其他', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}27: {code: '15XX', name: '非流動資產合計', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}28: {code: '1XXX', name: '資產總計', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}29: {code: '', name: '負債及權益', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}30: {code: '', name: '負債', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}31: {code: '', name: '流動負債', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}32: {code: '2120', name: '透過損益按公允價值衡量之金融負債－流動', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}33: {code: '2126', name: '避險之⾦融負債－流動', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}34: {code: '2170', name: '應付帳款', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}35: {code: '2180', name: '應付帳款－關係⼈', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}36: {code: '2200', name: '其他應付款', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}37: {code: '2201', name: '應付薪資', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}38: {code: '2206', name: '應付員⼯紅利', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}39: {code: '2207', name: '應付董監事酬勞', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}40: {code: '2213', name: '應付設備款', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}41: {code: '2216', name: '應付股利', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}42: {code: '2230', name: '本期所得稅負債', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}43: {code: '2300', name: '其他流動負債', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}44: {code: '2320', name: '一年或一營業週期內到期長期負債', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}45: {code: '2399', name: '其他流動負債－其他', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}46: {code: '21XX', name: '流動負債合計', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}47: {code: '', name: '非流動負債', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}48: {code: '2530', name: '應付公司債', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}49: {code: '2540', name: '長期借款', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}50: {code: '2541', name: '銀行長期借款', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}51: {code: '2570', name: '遞延所得稅負債', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}52: {code: '2580', name: '租賃負債－非流動', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}53: {code: '2600', name: '其他非流動負債', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}54: {code: '2640', name: '淨確定福利負債-非流動', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}55: {code: '2645', name: '存入保證金', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}56: {code: '2670', name: '其他非流動負債－其他', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}57: {code: '25XX', name: '非流動負債合計', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}58: {code: '2XXX', name: '負債總計', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}59: {code: '', name: '權益', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}60: {code: '', name: '歸屬於⺟公司業主之權益', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}61: {code: '', name: '股本', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}62: {code: '3110', name: '普通股股本', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}63: {code: '3100', name: '股本合計', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}64: {code: '', name: '資本公積', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}65: {code: '3210', name: '資本公積－發行溢價', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}66: {code: '3211', name: '資本公積－普通股股票溢價', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}67: {code: '3213', name: '資本公積－轉換公司債轉換溢價', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}68: {code: '3230', name: '資本公積－實際取得或處分子公司股權價格與帳面價值差額', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}69: {code: '3235', name: '資本公積－認列對子公司所有權權益變動數', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}70: {code: '3250', name: '資本公積－受贈資產', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}71: {code: '3251', name: '資本公積－受領股東贈與', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}72: {code: '3252', name: '資本公積－其他受贈資產', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}73: {code: '3260', name: '資本公積－採用權益法認列關聯企業及合資股權淨值之變動數', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}74: {code: '3270', name: '資本公積－合併溢額', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}75: {code: '3273', name: '資本公積－限制員工權利股票', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}76: {code: '3200', name: '資本公積合計', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}77: {code: '', name: '保留盈餘', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}78: {code: '3310', name: '法定盈餘公積', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}79: {code: '3320', name: '特別盈餘公積', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}80: {code: '3350', name: '未分配盈餘（或待彌補虧損）', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}81: {code: '3300', name: '保留盈餘合計', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}82: {code: '', name: '其他權益', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}83: {code: '3400', name: '其他權益合計', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}84: {code: '3500', name: '庫藏股票', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}85: {code: '31XX', name: '歸屬於⺟公司業主之權益合計', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}86: {code: '36XX', name: '非控制權益', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}87: {code: '3XXX', name: '權益總計', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}88: {code: '3X2X', name: '負債及權益總計', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}89: {code: '3998', name: '預收股款（權益項下）之約當發行股數', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}90: {code: '3999', name: '母公司暨子公司所持有之母公司庫藏股股數（單位：股）', curPeriodAmount: 0, curPeriodPercentage: 0, curPeriodAmountString: '0', …}length: 91[[Prototype]]: Array(0)general: (19) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]otherInfo: {assetLiabilityRatio: {…}, assetMixRatio: {…}, dso: {…}, inventoryTurnoverDays: {…}}preDate: {from: 1696694400, to: 1696780799}reportType: "balance_sheet"[[Prototype]]: Object 


isLoading (getReportFinancialIsLoading): false

**Comment by godmmt** [comment]
refactor redirect logics in user context #2731

**Comment by godmmt** [comment]
took 6 hours

done

**Comment by godmmt** [comment]
一起修復 #2727

**Comment by godmmt** [comment]
took 6 hours

done

**Comment by godmmt** [comment]
took 6.5 hours

done
