### ISSUE TITLE
🐛 [BUG] 已登入公司情況，會跳試用版

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#2727]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

10/7 13:00

### Device

None

### Reproduction URL

https://isunfa.com/users/reports/my_reports

### Reproduction steps

```markdown
1. Go to '任一介面'
2. Click on '.試用結束'
3. Scroll down to '....'
4. See error
```

### Current Result

```markdown
亂跳試用結束
```

### Screenshots

![截圖 2024-10-04 下午3 56 24](https://github.com/user-attachments/assets/bddf3f9c-f6c4-4a08-9cf1-bc1f2b849e61)

### Expected Result

```markdown
登入公司的情況，不會跳試用版 適用結束
```

**Comment by godmmt** [comment]
與 #2723 一起修復
