### ISSUE TITLE
🐛 [BUG] - iSunFA 無法寄信到 contact 

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#2798]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

10/15 14:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.com

### Reproduction steps

```markdown
1. 到 isunfa landing page 的最底下填寫資料之後送出寄信
```

### Current Result

1. 成功寄信的情況下，在 isunfa 會顯示失敗畫面，但是收信人信箱可以收到信
2. 收信人信箱有誤

### Screenshots

![DESCRIPTION](LINK.png)

### Expected Result

1. 寄信成功時要顯示成功畫面，可能要修改的地方：API response 應該改成 success = true，payload 可能要改
2. 收信人應改成 `REACT_APP_RECEPIENT_EMAIL`，可能要修改的地方：`REACT_APP_RECEPIENT_EMAIL` 環境變數沒有被用到

**Comment by Julian0701** [comment]
![image](https://github.com/user-attachments/assets/5beb0671-227e-4a2d-88cc-a2846513605f)

錯誤的原因是 `statusMessage` 不符合 `formatApiResponse` 的規範，所以成功的回應被當成錯誤處理

**Comment by Julian0701** [comment]
![image](https://github.com/user-attachments/assets/50461c55-86fb-487c-b045-f4f8dc5663ed)
修改收件地址

- take 1.5 hrs, done
