### ISSUE TITLE
[FEATURE] - DB schema modification till next sprint ~2024/11/01

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#2811]
### Summary

record db schema future changes

### Tasks

record db schema future changes

**Comment by RexBearIU** [comment]
model UserActionLog {
add -> user User @relation(fields: [userId], references: [id])
}

**Comment by TinyMurky** [comment]
```
model Account {
 canBeRecursive Boolean @map("can_be_recursive) @default(false)
}
```

**Comment by RexBearIU** [comment]
model Certificate {
 voucherCertificates VoucherCertificate[]
}
typo voucherCertificate's'

**Comment by RexBearIU** [comment]
model account_setting {
add createat 
updateat
deleteAt}

**Comment by RexBearIU** [comment]
model role {
type // company, system
}
model company {
delete tag
}
model admin {
add tag
add order
}

**Comment by RexBearIU** [comment]
add todo table

export interface ITodo {
  id: number;
  title: string;
  content: string;
  type: string;
  time: number;
  status: string;
  createdAt: number;
  updatedAt: number;
}

**Comment by RexBearIU** [comment]
userSetting {
language delete String?
}

**Comment by RexBearIU** [comment]
news {
add imageId 

relation file
}

**Comment by TinyMurky** [comment]
lineItem 與 lineItem關聯表

model revertLineItems (或是 associateLineiems){
  id: INT
  debit: boolean
  lineItemBeRevertedId : INT
 lineItemReverterId  (或是別的名稱) : INT
 amount Int or float
 associateVoucherId (一對多, 一個
 
  createdAt: Int
  updatedAt: Int
 deleteAt: int |null
}

**Comment by TinyMurky** [comment]
model event

monthsOfYears改成 Int[] (原本是string[])

**Comment by RexBearIU** [comment]
Finish migration
