### ISSUE TITLE
🐛 [BUG] - 清單的日期偏左

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#2812]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

10/16 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.com/users/reports/my_reports

### Reproduction steps

```markdown
1. Go to 報告／會計'
2. Click on '....'
3. Scroll down to '....'
4. See error
日曆排列偏左
```

### Current Result

日曆排列偏左

### Screenshots
![截圖 2024-10-15 下午3 32 01](https://github.com/user-attachments/assets/3f580b62-c1a5-48c7-8255-e185131f99e5)

### Expected Result

日曆排列置中

**Comment by Julian0701** [comment]
- take 0.5 hr, done

**Comment by TeresaYang00** [comment]
**報告**的清單沒調整到 
![截圖 2024-10-17 上午10 30 36](https://github.com/user-attachments/assets/dcd327f6-eb64-4be3-8019-890e9c6dd1dd)
