### ISSUE TITLE
🐛 [BUG] - OCR 建立 certificate 出現constrain failed, journal imageUrl無法正常出現

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#2889]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

2024/10/22

### Device

None

### OS

Linux

### Reproduction URL

http://localhost:3000

### Reproduction steps

```markdown
1. 建立OCR之後用OCR建立voucher
2. journal url 要正常顯示
```

### Current Result

```markdown
1. OCR 建立 certificate 出現constrain failed
2. journal imageUrl無法正常出現
```

### Screenshots

![DESCRIPTION](LINK.png)

### Expected Result

```markdown
1. OCR 建立 certificate 要正常建立
2. journal imageUrl要正常顯示
```

**Comment by TinyMurky** [comment]
took 2 hours
done

**Comment by RexBearIU** [comment]
took 2 hours
done
