### ISSUE TITLE
[Docs] missing API

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#2952]
- [ ] [API 文件](https://github.com/CAFECA-IO/iSunFA/wiki/API-v2#createrole) 缺 select role 
- [ ] [getStatusInfo](https://github.com/CAFECA-IO/iSunFA/wiki/API-v2#getstatusinfo) 要換成 v2 版

**Comment by RexBearIU** [comment]
besides, need to add user_role test
