### ISSUE TITLE
Salary - SalaryBookkeepingPage (ISFMK00039) (ISFMK00023)

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#296]
- [x] SalaryBookkeepingPage (ISFMK00039) (ISFMK00023)
- [x] SalaryBookkeepingForm

[Mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=507-104681&t=W4aRIT4IqrGmuDEa-4)

[Component Diagram](https://lucid.app/lucidchart/412189bb-3c75-42af-b76f-bcdf34ed9453/edit?view_items=nHJF_bALTsxy&invitationId=inv_d702461a-348d-422c-9a52-b5a34a44162d)

**Comment by Julian0701** [comment]
- take 3 hrs, remain 5 hrs

**Comment by Julian0701** [comment]
- take 3 hrs, desktop done

**Comment by Julian0701** [comment]
- take 1 hr, mobile done
- all done
