### ISSUE TITLE
Salary - SalaryListPage (ISFMK00067)

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#298]
- [ ] SalaryListPage (ISFMK00067)
- [ ] SalaryRecordList

外框 for #299

[Mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1898-149826&t=W4aRIT4IqrGmuDEa-4)

[Component Diagram](https://lucid.app/lucidchart/412189bb-3c75-42af-b76f-bcdf34ed9453/edit?view_items=nHJF_bALTsxy&invitationId=inv_d702461a-348d-422c-9a52-b5a34a44162d)

**Comment by godmmt** [comment]
related: #1435

**Comment by TeresaYang00** [comment]
已更改設計
