### ISSUE TITLE
[FEATURE] - [UI] Normal Setting Page

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/iSunFA#3013]
### Summary

Normal Setting 主頁

### Tasks

- [ ] User settings
- [ ] Notice settings（訂閱除外）
- [ ] Company settings
- [ ] Account settings

### Additional Notes
![image](https://github.com/user-attachments/assets/bb2d719f-bbff-4643-9e42-5a2474e91ca8)

**Comment by TzuHanLiang** [comment]
took 5hrs
done
