### ISSUE TITLE
[FEATURE] - [UI] Client/Supplier Setting Page

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/iSunFA#3034]
### Summary

Client/Supplier Setting 主頁

### Tasks

-

### Additional Notes
![image](https://github.com/user-attachments/assets/830420ce-0d78-4c85-a19a-f39b6abcab77)

**Comment by jing12345678910** [comment]
took 5 hrs
詳[PR3242](https://github.com/CAFECA-IO/iSunFA/pull/3242)
done
