### ISSUE TITLE
[FEATURE] - [UI] Add/Edit New Client/Supplier Modal

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/iSunFA#3036]
### Summary

新增/編輯 New Client/Supplier

### Tasks

-

### Additional Notes
![image](https://github.com/user-attachments/assets/fa93eab1-673c-4cc9-a889-feb783f2b4c9)

**Comment by jing12345678910** [comment]
took 2 hrs
詳PR[3242](https://github.com/CAFECA-IO/iSunFA/pull/3242)
done
