### ISSUE TITLE
KYC - UploadDocumentStep (ISFMK00058)

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#305]
UploadDocumentStep (ISFMK00058)

[iSunFA Component Diagram](https://lucid.app/lucidchart/412189bb-3c75-42af-b76f-bcdf34ed9453/edit?viewport_loc=-7427%2C4049%2C2865%2C1483%2C0_0&invitationId=inv_d702461a-348d-422c-9a52-b5a34a44162d)

**Comment by godmmt** [comment]
- [ ] 電腦版
- [ ] 手機版

**Comment by godmmt** [comment]
處理 UI 的部分

status 和功能先不用處理

**Comment by godmmt** [comment]
包含拖曳功能

這部分可參考日記帳上傳

**Comment by TzuHanLiang** [comment]
took 7hrs
done

**Comment by TzuHanLiang** [comment]
took 1hrs
done
