### ISSUE TITLE
KYC - Modal - Submitted

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#306]
Your Application Has Been Submitted

[iSunFA Component Diagram](https://lucid.app/lucidchart/412189bb-3c75-42af-b76f-bcdf34ed9453/edit?viewport_loc=-7427%2C4049%2C2865%2C1483%2C0_0&invitationId=inv_d702461a-348d-422c-9a52-b5a34a44162d)

**Comment by godmmt** [comment]
https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1345-243584&t=9OvAmCUtniBCoxSq-4

**Comment by TzuHanLiang** [comment]
took 1hrs
done
