### ISSUE TITLE
[Fix] update company api

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#3229]
除了第一間以外的公司無法變更標籤 tag

**Comment by godmmt** [comment]
![Image](https://github.com/user-attachments/assets/2cdb717a-6027-4502-96fa-bd1d7b1c74d1)
![Image](https://github.com/user-attachments/assets/f977f1ce-de47-4e40-83c4-499e36683b8f)
![Image](https://github.com/user-attachments/assets/7ec2877d-7025-4a73-8dc6-dce22ae94747)

**Comment by godmmt** [comment]
@RexBearIU 幫你連結到我那個分支的 PR 囉

**Comment by RexBearIU** [comment]
It takes 1 hour.

The error is due to the mismatch of function input = =
