### ISSUE TITLE
[Fix] src/pages/users/reports/financials/view/[reportId].tsx

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#3397]
協助 Anna 找出此頁面的 Bug 原因

目前無法正確渲染頁面
network 看起來有瘋狂在打這個 api `REPORT_GET_BY_ID`

**Comment by godmmt** [comment]
- [ ] 先整理程式碼，將 dev 環境中有出現的 React 警告或錯誤都一一修正

**Comment by godmmt** [comment]
大部分都修正後，還有遇到這個錯誤是

```
Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at rh (framework-0e8d27528ba61906.js:9:40163)
    at framework-0e8d27528ba61906.js:9:103383
    at oD (framework-0e8d27528ba61906.js:9:106133)
    at oO (framework-0e8d27528ba61906.js:9:99081)
    at framework-0e8d27528ba61906.js:9:98888
    at oF (framework-0e8d27528ba61906.js:9:98895)
    at oS (framework-0e8d27528ba61906.js:9:93934)
    at x (framework-0e8d27528ba61906.js:33:1364)
    at MessagePort.T (framework-0e8d27528ba61906.js:33:1894)
rh @ framework-0e8d27528ba61906.js:9
(anonymous) @ framework-0e8d27528ba61906.js:9
oD @ framework-0e8d27528ba61906.js:9
oO @ framework-0e8d27528ba61906.js:9
(anonymous) @ framework-0e8d27528ba61906.js:9
oF @ framework-0e8d27528ba61906.js:9
oS @ framework-0e8d27528ba61906.js:9
x @ framework-0e8d27528ba61906.js:33
T @ framework-0e8d27528ba61906.js:33Understand this errorAI
7
```

**Comment by godmmt** [comment]
# 研究

**`html2canvas`** 並不支援 **SSR**（伺服器端渲染），因為它依賴於瀏覽器環境中的 `window` 和 `document` 來進行 DOM 操作和渲染畫面。這些 API 在伺服器端環境中無法使用，因此在 Next.js 的 **Pages Router** 或 **App Router** 中，直接在伺服器端執行會導致錯誤。

### 如何讓 `html2canvas` 在 Next.js 中正常運行

你可以使用 **動態載入** 和 **停用 SSR** 來讓 `html2canvas` 只在客戶端執行。

#### 1. **動態載入 `html2canvas`**

將使用 `html2canvas` 的邏輯包裹在動態載入的元件中，並停用 SSR：

```jsx
import dynamic from 'next/dynamic';

const HtmlToCanvasComponent = dynamic(() => import('./HtmlToCanvasComponent'), { ssr: false });

export default function Page() {
  return (
    <div>
      <h1>HTML to Canvas</h1>
      <HtmlToCanvasComponent />
    </div>
  );
}
```

#### 2. **在 `HtmlToCanvasComponent` 中使用 `html2canvas`**

將所有與 `html2canvas` 相關的邏輯放入 `useEffect`，以確保它只在瀏覽器中執行：

```jsx
import { useEffect } from 'react';
import html2canvas from 'html2canvas';

export default function HtmlToCanvasComponent() {
  useEffect(() => {
    const captureElement = document.getElementById('capture');

    if (captureElement) {
      html2canvas(captureElement).then((canvas) => {
        document.body.appendChild(canvas);
      });
    }
  }, []);

  return (
    <div>
      <div id="capture" style={{ width: '300px', height: '200px', backgroundColor: 'lightblue' }}>
        <h2>Capture this content</h2>
      </div>
    </div>
  );
}
```

### 小結
1. **`html2canvas` 不支援 SSR**，因為它依賴於瀏覽器環境。
2. 需要透過 **動態載入** 並 **停用 SSR** 來讓它只在客戶端執行。
3. 確保所有的 DOM 操作都在 `useEffect` 中執行，以避免 hydration 問題。

**Comment by godmmt** [comment]
# 研究

根據這些步驟修改 `view_financial_section.tsx`

### 檔案中觀察到的重點

1. **`html2canvas`** 被直接引入：
   ```tsx
   import html2canvas from 'html2canvas';
   ```

2. **`react-pdf` 的樣式檔案**也被直接引入：
   ```tsx
   import 'react-pdf/dist/esm/Page/AnnotationLayer.css';
   import 'react-pdf/dist/esm/Page/TextLayer.css';
   ```

這兩個函式庫的直接引入會導致在 Next.js 頁面伺服器端渲染時發生錯誤，因為它們依賴於瀏覽器 API。

---

### 修改建議

#### 1. **將 `html2canvas` 動態載入並停用 SSR**

將與 `html2canvas` 有關的邏輯封裝在動態載入的元件中，讓它僅在瀏覽器環境執行：

- **建立一個專門的 `HtmlToCanvasComponent.tsx`：**

```tsx
import { useEffect } from 'react';
import html2canvas from 'html2canvas';

export default function HtmlToCanvasComponent() {
  useEffect(() => {
    const captureElement = document.getElementById('capture');

    if (captureElement) {
      html2canvas(captureElement).then((canvas) => {
        document.body.appendChild(canvas);
      });
    }
  }, []);

  return (
    <div id="capture">
      <h2>Capture this content</h2>
    </div>
  );
}
```

- **在 `view_financial_section.tsx` 中動態載入：**

```tsx
import dynamic from 'next/dynamic';

const HtmlToCanvasComponent = dynamic(() => import('./HtmlToCanvasComponent'), { ssr: false });

export default function Page() {
  return (
    <div>
      <h1>View Financial Section</h1>
      <HtmlToCanvasComponent />
    </div>
  );
}
```

---

#### 2. **調整 `react-pdf` 的樣式引入方式**

樣式檔案本身並不依賴於 SSR，但要確保 `react-pdf` 元件的渲染僅在瀏覽器中執行。將 `react-pdf` 元件也進行動態載入：

- **建立 `PDFViewer.tsx`：**

```tsx
import { useEffect, useState } from 'react';
import { Document, Page } from 'react-pdf';

export default function PDFViewer({ file }) {
  const [numPages, setNumPages] = useState(null);

  const onDocumentLoadSuccess = ({ numPages }) => {
    setNumPages(numPages);
  };

  return (
    <Document file={file} onLoadSuccess={onDocumentLoadSuccess}>
      {Array.from(new Array(numPages), (el, index) => (
        <Page key={`page_${index + 1}`} pageNumber={index + 1} />
      ))}
    </Document>
  );
}
```

- **在 `view_financial_section.tsx` 中動態載入 `PDFViewer`：**

```tsx
import dynamic from 'next/dynamic';
import 'react-pdf/dist/esm/Page/AnnotationLayer.css';
import 'react-pdf/dist/esm/Page/TextLayer.css';

const PDFViewer = dynamic(() => import('./PDFViewer'), { ssr: false });

export default function Page() {
  return (
    <div>
      <h1>View Financial Section</h1>
      <PDFViewer file="/path/to/pdf/file.pdf" />
    </div>
  );
}
```

---

### 小結

1. **`html2canvas`** 和 **`react-pdf`** 不支援 SSR，需使用 `dynamic` 動態載入並停用 SSR。
2. 確保所有的 DOM 操作與 PDF 文件的顯示邏輯都只在客戶端執行，避免伺服器端出錯。

**Comment by godmmt** [comment]
<img width="1440" alt="截圖 2024-11-28 下午4 31 16" src="https://github.com/user-attachments/assets/c6644fed-30ec-4c8a-be5d-051605db6eac">

**Comment by godmmt** [comment]
# 結論 

先研究到目前這一個步驟
想說先止損
明天會再跟 @jing12345678910  討論

**Comment by godmmt** [comment]
took 3 hours

done

**Comment by TinyMurky** [comment]
在 Next.js 中，當出現 **"不能 hydrate 的錯誤"**（如 `Error: Hydration failed`），通常是因為伺服端渲染（SSR）和用戶端渲染（CSR）之間的 HTML 或狀態不一致，以下是一些可能原因和解法：

---

### 1. **伺服端與用戶端渲染內容不一致**
   - **原因**：
     - 在伺服端生成的 HTML 與用戶端重新渲染的內容不同。
     - 例如，某些動態內容在伺服端生成時缺失（如依賴瀏覽器 API 或動態資料）。
   - **解法**：
     - 確保伺服端和用戶端渲染邏輯一致。
     - 使用 `useEffect` 或 `useState` 處理需要在用戶端執行的動態內容。例如：
       ```tsx
       import { useEffect, useState } from 'react';

       const MyPage = () => {
         const [isClient, setIsClient] = useState(false);

         useEffect(() => {
           setIsClient(true);
         }, []);

         return (
           <div>
             {isClient ? <p>Client-only content</p> : <p>Loading...</p>}
           </div>
         );
       };

       export default MyPage;
       ```

---

### 2. **使用動態日期/時間**
   - **原因**：
     - 伺服端生成的 HTML 包含動態時間戳，而用戶端渲染時會生成不同的時間戳。
   - **解法**：
     - 將與時間相關的內容移至用戶端執行：
       ```tsx
       import { useState, useEffect } from 'react';

       const MyPage = () => {
         const [currentTime, setCurrentTime] = useState('');

         useEffect(() => {
           setCurrentTime(new Date().toLocaleString());
         }, []);

         return <p>{currentTime || 'Loading time...'}</p>;
       };

       export default MyPage;
       ```

---

### 3. **Props 傳遞異常**
   - **原因**：
     - `getServerSideProps` 或 `getStaticProps` 傳遞的 props 與用戶端初始化的狀態不一致。
   - **解法**：
     - 確保伺服端返回的 props 結構正確且不包含非序列化內容（如函數、`undefined` 或 Symbol）。

---

### 4. **hydration 和 re-render 的 key 錯誤**
   - **原因**：
     - React 中 `key` 不一致會導致重新渲染問題，特別是對於列表渲染。
   - **解法**：
     - 為列表項目分配穩定的 `key`：
       ```tsx
       const items = [{ id: 1, name: 'Item A' }, { id: 2, name: 'Item B' }];
       return (
         <ul>
           {items.map(item => (
             <li key={item.id}>{item.name}</li>
           ))}
         </ul>
       );
       ```

---

### 5. **環境差異（如 window 或 document）**
   - **原因**：
     - 伺服端渲染時無法使用 `window` 或 `document`，導致用戶端 hydration 不匹配。
   - **解法**：
     - 僅在用戶端執行相關代碼：
       ```tsx
       import { useEffect, useState } from 'react';

       const MyComponent = () => {
         const [width, setWidth] = useState(0);

         useEffect(() => {
           setWidth(window.innerWidth);
         }, []);

         return <p>Window width: {width}</p>;
       };

       export default MyComponent;
       ```

---

### 6. **狀態或副作用導致的重繪**
   - **原因**：
     - 頁面內部的狀態（如 `useState` 或 `useContext`）初始化與伺服端渲染的內容不一致。
   - **解法**：
     - 初始狀態應與伺服端返回的值一致，或者處理狀態初始化邏輯。

---

### 7. **避免 React 服務端不支持的屬性**
   - **原因**：
     - 某些屬性或元素在伺服端和用戶端的渲染方式不同（如 `<input>` 的 `value` 屬性）。
   - **解法**：
     - 確保伺服端和用戶端對於這些元素的渲染值一致。

---

如果你的問題是特定於 **Page API**，可能需要檢查伺服端和 API 返回的數據，確保數據格式和處理邏輯不影響伺服端渲染的輸出。

**Comment by godmmt** [comment]
- [ ] Fix calling api method
- [ ] Fix other React warning and error
- [ ] Remove NavBar component (belongs to Alpha ver)

**Comment by godmmt** [comment]
took 5 hours

Total time : 8 hours

done
