### ISSUE TITLE
[Interview] 內部測試

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#3418]
- [ ] #3542
- [ ] #3543

### 測試內容

本次內部測試分為兩種類型使用者進行使用者內部測試試驗，一種為具有會計背景相關使用者(偏向此次beta版本的TA)，另一種為非會計相關背景使用者，並且提供以下任務進行內部測試，測試中記錄其操作流程、正確性、所需時間等，並針對其操作流程提出詢問，測試完成後會請使用者填寫易用性評估來計算本次產品易用性分數。

**Comment by StrawHo** [comment]
為台灣陽光雲建立一個在12/31即將發生的「年度會議」到代辦清單中（Goal: 登入/創建角色/創建公司/新增 Todo list 流程是否順暢）
查看最新的系統更新對你目前的工作有什麼影響（Goal: 測試使用者可否找到系統更新資訊位置）
今日台灣陽光雲多了三筆支出（提供三張憑證），麻煩協助建檔（Goal: 使用者可否順利上傳憑證並將資料登打進系統）
公司在12/15需要繳房租了，麻煩開立一張傳票來記錄此事。（Goal: 使用者是否可以順利建立應付帳款傳票）
接續上個任務，剛剛收到Luphia通知，房租已經繳了，麻煩開立另一張傳票紀錄此事（Goal: 使用者是否可以順利銷帳）
公司今日接到了一個大客戶「台積電」，麻煩協助將此客戶建檔。（Goal: 使用者是否可以順利新增客戶/供應商資料）
公司有一台資產編號A-000010的Macbook要報廢，請協助紀錄此事件（Goal: 使用者是否知道在哪裡修改資產狀態）
陽光雲為了增加品牌可信度，決定在自己的官網公布財報，工程師需要相關程式碼，請協助完成此任務。（Goal: 使用者是否知道在哪裡複製內嵌程式碼）
查看公司11月份的資產負債表。（Goal: 使用者是否知道在哪裡查看報表）
公司需要另一個專案（BAIFA）的獨立帳本，請協助建立。（Goal: 使用者是否能順利回到儀表板並建立新帳本）

**Comment by StrawHo** [comment]
初始心態調查問卷:
LINK:
https://forms.gle/EhMhwd4t3kp5orND8

**Comment by StrawHo** [comment]
### 使用者測試任務情境 (將任務調整成由簡單到困難)
因 Jodie已有設計部分任務流程，將從其任務流程進行調整。(因部分功能尚未完善。)

1. 請使用者建立兩家公司(A公司與B公司)，並且能夠切換不同公司。（Goal: 登入/創建角色/創建公司/切換公司)

2. 查看最新的系統更新對你目前的工作有什麼影響（Goal: 測試使用者可否找到系統更新資訊位置）

3. A公司為了增加品牌可信度，決定在自己的官網公布財報，工程師需要相關程式碼，請協助完成此任務。（Goal: 使用者是否知道在哪裡複製內嵌程式碼）

4. 公司今日接到了一個大客戶「台積電」，麻煩協助將此客戶建檔。（Goal: 使用者是否可以順利新增客戶/供應商資料）

5. 分別將A ， B 兩個公司的憑證進行上傳，上傳過程中須注意錯誤排除與正確性 (Goal: 使用者是否可以順利分別在不同公司新增憑證，與發生錯誤測試者會如何應對等問題)

6. A公司在12/15需要繳房租了，麻煩開立一張傳票來記錄此事。（Goal: 使用者是否可以順利建立應付帳款傳票)

7. 接續上個任務，剛剛收到老闆通知，房租已經繳了，麻煩開立另一張傳票紀錄此事（Goal: 使用者是否可以順利銷帳）

8. 查看公司11月份的資產負債表。（Goal: 使用者是否知道在哪裡查看報表）

9. 公司有一台資產編號A-000010的Macbook要報廢，請協助紀錄此事件（Goal: 使用者是否知道在哪裡修改資產狀態）

**Comment by StrawHo** [comment]
內部測試時間預計於下周一12/9 安排執行。
使用者內部測試時間估計約20~30min，SUS問卷填寫時間約10~15分鐘。
共有四位受測者，預計總共測試時間一人約45min ，約3hr左右。
後續整理受測記錄與分析相關內部測試資料預估約2hr。

**Comment by StrawHo** [comment]
- [ ] [UX] Beta內部測試-Anna
- [ ] [UX] Beta內部測試-Elena
