### ISSUE TITLE
[Review] 產品驗收

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#3419]
驗收產品確認以下事項：

1. ＵＩ是否與設計稿吻合
2. 尋找產品中的Bug

**Comment by JodieWu** [comment]
### 登入頁面

<img width="580" alt="截圖 2024-12-04 上午10 27 01" src="https://github.com/user-attachments/assets/6bb7cbf4-0e54-4466-bfcd-08d89391eb62">

<img width="580" alt="截圖 2024-12-04 上午10 27 18" src="https://github.com/user-attachments/assets/982d374c-468e-4589-8b34-c92dc90cf4af">

同意條款標題bug
內文是置左不是置中

### Dashboard

<img width="1184" alt="截圖 2024-12-04 上午10 29 20" src="https://github.com/user-attachments/assets/0eb844b7-07a6-454d-b1fd-26b1bf16c050">

按鈕為「邀請碼」，非「程式碼」
---
<img width="409" alt="截圖 2024-12-04 上午10 30 15" src="https://github.com/user-attachments/assets/a19b41cd-9ab8-4422-91d8-7add6cc4ec36">

第二格為「統一編號」，格子中的placeholder為「請輸入公司統編」
---
<img width="407" alt="截圖 2024-12-04 上午10 36 16" src="https://github.com/user-attachments/assets/c9bc6e1d-13ba-462e-93d9-7b45f7db3077">

To do list 的選擇日期下半部會被切掉，且只能選擇今日以前的日期，無法選擇未來日期
---
<img width="1159" alt="截圖 2024-12-04 上午10 36 48" src="https://github.com/user-attachments/assets/e0b257a8-6b0b-40fb-92da-7e573457a018">

分享按鈕沒有作用

---
<img width="572" alt="截圖 2024-12-04 上午10 37 09" src="https://github.com/user-attachments/assets/b5b913c6-2750-406b-bf7a-fb459151eaa2">

已新增了今日的待辦事項，但跳回Dashboard之後沒有顯示，重新整理也沒用

---

**Comment by JodieWu** [comment]
# 設計端

- [ ] **連結公司跟切換公司的Motion很薄弱，不容易注意到有被執行**

<img width="1178" alt="截圖 2024-12-04 上午11 08 43" src="https://github.com/user-attachments/assets/1aeee06f-f377-4a38-b0fd-78c1ac38a08f">

---

**Comment by JodieWu** [comment]
部分完成： 4 hr

**Comment by JodieWu** [comment]
# Component

- [ ] **只要Tab旁邊有新資料數量的Tag時，若筆數為”0“ 則直接隱藏Tag，不需顯示0的Tag**

<img width="1244" alt="截圖 2024-12-05 下午1 15 39" src="https://github.com/user-attachments/assets/41156a01-13a4-4311-8065-12558a454dfa">

<img width="1194" alt="截圖 2024-12-05 下午1 15 49" src="https://github.com/user-attachments/assets/d831b7dd-8634-497f-9032-a98bd2bce1d8">

<img width="1177" alt="截圖 2024-12-05 下午1 16 00" src="https://github.com/user-attachments/assets/04aaf1c0-fe4f-403e-8696-dc391d2b2951">

---

# Voucher

- [ ] **建立傳票與傳票清單中的「傳票類型」命名不同，應一律都是「支出、收入、轉帳」**

<img width="593" alt="截圖 2024-12-05 下午1 11 03" src="https://github.com/user-attachments/assets/d7f4ac42-c379-4a3e-a7df-602774904c46">

<img width="164" alt="截圖 2024-12-05 下午1 11 15" src="https://github.com/user-attachments/assets/69155f9c-35d0-49cc-afec-a4ed717b354f">

---

# Setting

- [ ] **這裡Switch全部打開後，如果我跳轉其他頁面再回來，又會自己被關起來**

<img width="566" alt="截圖 2024-12-05 下午1 34 15" src="https://github.com/user-attachments/assets/ef778c63-2837-4135-92c8-450ed36facad">

---

- [ ] **突然出現簡體字**

<img width="583" alt="截圖 2024-12-05 下午1 35 47" src="https://github.com/user-attachments/assets/1fdef578-52e9-4bc5-9c73-593f02b9d2c4">

---

- [ ] **已先選擇好國家，但在輸入數字時，下拉選單還是會被打開**
- [ ] ** 如果前面保存過一次，重新輸入資料的話，保存按鈕還是成Disable狀態，無法二次修改（保存）**

<img width="579" alt="截圖 2024-12-05 下午1 37 37" src="https://github.com/user-attachments/assets/8f332b84-54fb-48ed-b153-2f8c3d02cd26">

---

- [ ] **工作標籤應該是置中不是置左**

<img width="693" alt="截圖 2024-12-05 下午1 43 10" src="https://github.com/user-attachments/assets/2c1175f8-cbe8-4c5c-8639-3f2e3408dfca">

---

# 設計端

- [ ] **這邊還沒填寫就有美國國旗感覺有點怪，然後如果我第一個選了台灣，其他地方好像也不會幫我自動選成台灣**
- [ ] **如果我寫完沒有按保存，轉跳去其他畫面，好像少了警告語**
- [ ] **使用者名稱旁邊多了一個編輯符號，但底下已經可編輯**

<img width="667" alt="截圖 2024-12-05 下午1 20 50" src="https://github.com/user-attachments/assets/43099ce6-ed43-4599-94c8-c8e45b5dbe15">

---

- [ ] **登入時間少了“時間”**

<img width="397" alt="截圖 2024-12-05 下午1 22 26" src="https://github.com/user-attachments/assets/d12b0b07-81ff-4ec1-8f90-f87eea584e71">

---

- [ ] **這裡看起來會讓我以為沒有公司，可考慮把清單往外放，少包一層，或是拿掉新增公司的按鈕，這裡只允許設定公司詳細資料（另外儀表板中的公司管理是否也考慮整合，一開始以為那邊是管理公司的地方）**

<img width="587" alt="截圖 2024-12-05 下午1 31 34" src="https://github.com/user-attachments/assets/9a51f175-61e0-45ba-a282-414e6781d28d">

---

**Comment by TinyMurky** [comment]
https://github.com/user-attachments/assets/547f9cdf-7cc3-4c78-b18f-23544f97b11d

更新User Setting的時候，成功根新之後會被彈出來

可能原因，前端在成功之後重西Get Setting, Get 到undefined

![image](https://github.com/user-attachments/assets/5d220df1-766c-41fb-a617-8ff24d427e64)

**Comment by TeresaYang00** [comment]
隱私權條款和服務條款無法點選超連結

![截圖 2024-12-09 下午7 34 08](https://github.com/user-attachments/assets/20967ce7-dcef-44dc-8e8e-35df177fb4c8)
