### ISSUE TITLE
🐛 [BUG] - 下拉選單收合問題

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3474]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/5 12:00

### Reproduction URL

https://isunfa.tw/users/asset

### Reproduction steps

1. Go to '資產清單'
2. Click on '類型'

### Current Result

似乎大部分的Dropdown都有收合困難的問題，要收起來必須精準的按到箭頭icon
dropdown下拉後，右邊的箭頭會朝上

### Screenshots

![截圖 2024-12-05 下午12 05 08](https://github.com/user-attachments/assets/2d8ef191-59b9-4573-bcc7-5f496acc687e)

### Expected Result

似乎大部分的Dropdown都有收合困難的問題，要收起來必須精準的按到箭頭icon
dropdown下拉後，右邊的箭頭會朝上

**Comment by TzuHanLiang** [comment]
took 1.5hrs
done
