### ISSUE TITLE
🐛 [BUG] - 分享按鈕沒作用

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3477]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/5 12:00

### Reproduction URL

https://isunfa.tw/users/todo_list_page

### Reproduction steps

1. Go to '儀表板'
2. Click on '待辦事項.'

### Current Result

分享和刪除目前無反應

### Screenshots

![截圖 2024-12-05 下午2 58 50](https://github.com/user-attachments/assets/a9115e0d-54c0-4e6f-90a0-607c56972a3f)

### Expected Result

可以分享到社群 及 可以刪除此事件

**Comment by godmmt** [comment]
已經開過票了 https://github.com/CAFECA-IO/iSunFA/issues/2980

**Comment by godmmt** [comment]
無法刪除事件

經排查可能與後端 api 有關
有開在這張票 : https://github.com/CAFECA-IO/iSunFA/issues/3588

**Comment by godmmt** [comment]
took 0.5 hour

done

排查完畢
並且都已另外有 issue 處理
