### ISSUE TITLE
🐛 [BUG] - 手機拍照無法正確上傳

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3478]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/5 12:00

_No response_

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '會計'
2. Click on '上傳憑證'
3. Scroll down to '手機作為掃描器'

### Current Result

掃描qrcode 後無法有效上傳

### Screenshots

![截圖 2024-12-05 下午3 13 25](https://github.com/user-attachments/assets/382975a6-8e4e-4b86-ab92-775889d6be1e)

### Expected Result

可以有效使用qrcode上傳圖片

**Comment by TzuHanLiang** [comment]
duplicated with #3509 @TeresaYang00
