### ISSUE TITLE
🐛 [BUG] - 上傳更新發票後，發票數量數字未變更

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3480]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/5 12:00 

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to ' '
2. Click on '上傳憑證'
3. Scroll down to '無憑證的發票/有憑證的發票'

### Current Result

目前發票上傳數字都不會變動

### Screenshots

![截圖 2024-12-05 下午3 18 21](https://github.com/user-attachments/assets/4e4b6296-dc0d-471b-b50e-4dfe708c8468)

### Expected Result

可以依照上傳發票的數量 變動數字

**Comment by TzuHanLiang** [comment]
https://github.com/user-attachments/assets/8d2ab0fa-d7d7-4f7b-aed0-fa7751fe6147

took1hrs
done

**Comment by TzuHanLiang** [comment]
<img width="1673" alt="Screenshot 2024-12-24 at 3 26 34 PM" src="https://github.com/user-attachments/assets/fca4911f-c1f9-4b48-921a-7bf6e09eda2a" />
