### ISSUE TITLE
🐛 [BUG] - 發票列表 選擇發票類型新增全部

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3482]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/5 12:00

### Device

None

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '上傳憑證 '
2. Click on '類型'

### Current Result

選擇類型無法跑出『全部』類型

### Screenshots

![DESCRIPTION](LINK.png)

### Expected Result

選擇類型可以跑出只有那一類的發票 
及新增全部的選項

**Comment by TzuHanLiang** [comment]
took 1hrs
done
