### ISSUE TITLE
🐛 [BUG] - 發票列表多了一個不明意義的欄位

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3484]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/5 12:00

### Device

None

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '上傳憑證'
2. Click on '發票列表'
3. Scroll down to '新增傳票'

### Current Result

新增傳票 右邊有selesct 的按鍵但文字不正確

### Screenshots

![截圖 2024-12-09 上午10 12 57](https://github.com/user-attachments/assets/0401f661-40f9-41a4-b1d1-7cbdca1ee5c4)

### Expected Result

新增傳票 右邊有select 可以選擇 （請參照設計稿）

**Comment by TzuHanLiang** [comment]
took 1hrs
done
