### ISSUE TITLE
🐛 [BUG] - 上傳發票新增資訊功能異常

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3486]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/5 12:00

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '發票'
2. Click on '新增發票'

### Current Result

1.改動總額，不會自動幫我計算稅前金額
2.發票類型格式格子有斷裂
3.新的交易對象是按下儲存才會跳出是否要新增到客戶/供應商

### Screenshots
![截圖 2024-12-05 下午4 52 14](https://github.com/user-attachments/assets/bfc52d35-dbdf-4648-9834-51be3d299dce)

### Expected Result

1.改動總額，會自動幫我計算稅前金額 反之亦然
2.發票類型格式格子有斷裂
3.新的交易對象是按下儲存才會跳出是否要新增到客戶/供應商

**Comment by TzuHanLiang** [comment]
took 1hrs
done

**Comment by TzuHanLiang** [comment]
took 2hrs
remain 1hrs

**Comment by TzuHanLiang** [comment]
took 5hrs
（大改）
done
