### ISSUE TITLE
🐛 [BUG] - 發票號碼的placeholder 並非為０

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3489]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/5 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

```markdown
1. Go to '發票列表'
2. Click on '新增發票'
3. Scroll down to '....'
4. See error
```

### Current Result

發票號碼的placeholder 並非為０

### Screenshots

![截圖 2024-12-05 下午6 40 00](https://github.com/user-attachments/assets/f5b8b836-1b2d-43e5-a223-a72fe135c5d2)
設計稿
![截圖 2024-12-09 下午6 48 55](https://github.com/user-attachments/assets/428db1e0-e377-4cd6-bb67-c948dab8fcea)

### Expected Result

發票號碼的placeholder 並非為０

**Comment by TzuHanLiang** [comment]
took 1hrs
done
