### ISSUE TITLE
🐛 [BUG] - 上傳發票After-Tax 是 inline 不會換行

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3499]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/6 12:00

### Device

None

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '發票列表'
2. Click on '金額'

### Current Result

after tax 是不會換行

### Screenshots

<img width="307" alt="截圖 2024-12-06 上午10 58 24" src="https://github.com/user-attachments/assets/49e51fb3-8674-41e3-8cc6-2b85d9fc647a">

### Expected Result

after tax 是不會換行

**Comment by TzuHanLiang** [comment]
took 1hrs
done
