### ISSUE TITLE
🐛 [BUG] - 公司統編需內建搜尋功能

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3501]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/6 12:00

### Device

None

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to ' 發票列表 '
2. Click on '交易對象 '

### Current Result

- 交易對象的place holder 為 ID Number 跟 Name (同設計稿) 不是N/A
 -也少了協助搜尋功能（打統編出現公司抬頭，或打公司抬頭出現統編）

### Screenshots
![截圖 2024-12-06 上午11 33 12](https://github.com/user-attachments/assets/78a6bae0-2f53-49ee-825a-2900b863ecb9)

### Expected Result

- 交易對象的place holder 為 ID Number 跟 Name (同設計稿) 不是N/A
- 也少了協助搜尋功能（打統編出現公司抬頭，或打公司抬頭出現統編）

**Comment by TzuHanLiang** [comment]
took  4hrs
(共用component邏輯修改導致找bug花了點時間）
done

https://github.com/user-attachments/assets/ed058843-741c-4543-b2b4-dabfb2878151
