### ISSUE TITLE
🐛 [BUG] - 上傳發票無法編輯名稱

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3502]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/6 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '上傳憑證'
2. Click on '發票列表'

### Current Result

上傳發票需要編輯憑證名稱，無法更改

### Screenshots

![截圖 2024-12-06 上午11 35 46](https://github.com/user-attachments/assets/fc517aa2-6c0a-4e8f-aa38-4d0b07994a1f)

### Expected Result

上傳發票需要編輯憑證名稱，可以更改編輯

**Comment by TzuHanLiang** [comment]
took 1hrs
remain 1hrs

**Comment by TzuHanLiang** [comment]
took 1hrs
remain 1hre

**Comment by TzuHanLiang** [comment]
took 1hrs
done
