### ISSUE TITLE
🐛 [BUG] - 上傳發票縮圖排版錯誤

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3503]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/5 12:00

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '發票列表'
2. Click on '縮圖模式'

### Current Result

縮圖統一至左，並非置中分散

### Screenshots

![截圖 2024-12-06 上午11 44 06](https://github.com/user-attachments/assets/13df1e43-e198-4940-a9af-f5bd03f93cd3)

### Expected Result

縮圖統一至左，並非置中分散

**Comment by TzuHanLiang** [comment]
took 1hrs
done
