### ISSUE TITLE
🐛 [BUG] - 發票清單和設計稿不一致

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3504]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/6 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

```markdown
1. Go to '發票列表'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Current Result

清單和設計稿不一致

### Screenshots
<img width="822" alt="截圖 2024-12-06 下午1 49 54" src="https://github.com/user-attachments/assets/88d20e7d-c2aa-41f6-8ddd-3165d6d3a9ff">

設計稿
![截圖 2024-12-06 下午2 00 11](https://github.com/user-attachments/assets/de582e19-d3c9-415f-9c1b-415f7263ba4e)

### Expected Result

清單設計和設計稿一致

**Comment by TzuHanLiang** [comment]
took 1hrs
done

**Comment by TzuHanLiang** [comment]
took 2hrs
done
