### ISSUE TITLE
🐛 [BUG] -新增傳票的選擇發票上傳，上傳發票點選刪除鍵無效

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3510]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/6 12:00

### OS

macOS

### Reproduction URL

https://isunfa.tw/cn/users/accounting/add_new_voucher

### Reproduction steps

```markdown
1. Go to '新增傳票'
2. Click on '選擇發票'
3. Scroll down to '....'
4. See error
```

### Current Result

新增傳票的選擇發票上傳，上傳發票點選刪除鍵無效

### Screenshots
![截圖 2024-12-06 下午2 27 16](https://github.com/user-attachments/assets/6ecbe45b-6a2b-49f6-964b-8177280b4cae)
<img width="108" alt="截圖 2024-12-06 下午2 34 51" src="https://github.com/user-attachments/assets/0b49cb8f-4582-4e1a-a2a5-40c5b1bf1dc6">

### Expected Result

新增傳票的選擇發票上傳，上傳發票點選刪除鍵無效

**Comment by TzuHanLiang** [comment]
took 1hrs
done
