### ISSUE TITLE
🐛 [BUG] - 新增傳票會計科目只有資產科目

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3511]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/6

### Reproduction URL

https://isunfa.tw/cn/users/accounting/add_new_voucher

### Reproduction steps

```markdown
1. Go to '新增傳票'
2. Click on '會計科目'
3. Scroll down to '....'
4. See error
```

### Current Result

新增傳票會計科目只有資產科目

### Screenshots

![截圖 2024-12-06 下午2 36 33](https://github.com/user-attachments/assets/6be856ef-c228-4a57-9422-e17a0d134de6)

### Expected Result

新增傳票會計科目只有資產科目，需要跑出所有的會計科目

**Comment by Julian0701** [comment]
- take 1 hr, done
