### ISSUE TITLE
🐛 [BUG] - 新增傳票按下保存後無傳票紀錄，沒有儲存成功

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3512]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/6 12:00

### Reproduction URL

https://isunfa.tw/cn/users/accounting/add_new_voucher

### Reproduction steps

```markdown
1. Go to '新增傳票'
2. Click on '會計科目.'
3. Scroll down to '保存.'
4. See error
```

### Current Result

無法保存登打的會計傳票分錄

### Screenshots

![截圖 2024-12-06 下午2 40 19](https://github.com/user-attachments/assets/ae7e51b3-dcd0-43f9-a37d-292bcca21e8a)

### Expected Result

可以順利保存會計分錄

**Comment by Julian0701** [comment]
在傳票列表的類型補上「全部」選項，讓傳票可以完整顯示出來
也請 Murky 調整了 API query
<img width="1336" alt="image" src="https://github.com/user-attachments/assets/567e0648-0633-4519-a237-b571c0a4e360" />

**Comment by Julian0701** [comment]
- take 3 hrs, done
