### ISSUE TITLE
🐛 [BUG] - 新增傳票裡找不到從憑證上傳的發票

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3513]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/6 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/cn/users/accounting/add_new_voucher

### Reproduction steps

```markdown
1. Go to '新增傳票'
2. Click on '選擇發票'
3. Scroll down to '....'
4. See error
```

### Current Result

找不到已經從憑證上傳區上傳的發票

### Screenshots

![截圖 2024-12-06 下午2 59 45](https://github.com/user-attachments/assets/8592c251-b6e4-48cd-82cc-eb3915639241)

<img width="625" alt="截圖 2024-12-06 下午3 00 30" src="https://github.com/user-attachments/assets/25a8f384-fd63-4617-b174-bfa525a4fe93">

### Expected Result

找得到已經從憑證上傳區上傳的發票

**Comment by TzuHanLiang** [comment]
took 1hrs
done
