### ISSUE TITLE
🐛 [BUG] - 上傳完畢後，左下應顯示幾份文件上傳成功、幾份文件上傳失敗（同 Design System）

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3514]
### Searched for similar issues

- [x] YES, I have searched for similar issues.

### Time of occurrence

12/6 12:00

### Reproduction URL

https://isunfa.tw/cn/users/accounting/add_new_voucher

### Reproduction steps

1. Go to '新增傳票'
2. Click on '上傳發票'

### Current Result

上傳完畢後，左下應顯示幾份文件上傳成功、幾份文件上傳失敗（同 Design System）
 上傳完了無法按確認？
 少了手機掃描上傳的功能

### Screenshots

![截圖 2024-12-06 下午3 04 55](https://github.com/user-attachments/assets/9eb2fca6-96e3-4d71-a0a2-2b4958cfbf2f)

### Expected Result

-上傳完畢後，左下應顯示幾份文件上傳成功、幾份文件上傳失敗（同 Design System）
 -上傳完了無法按確認？
 -少了手機掃描上傳的功能`

**Comment by TzuHanLiang** [comment]
要在這邊新增「手機掃描上傳的功能」畫面涉及功能及資料，比較花時間，單這一個花了3-4hrs（一開始作法太複雜，後來用共用組件解決）
其他兩個問題約1hr

took 5hrs
done
