### ISSUE TITLE
🐛 [BUG] 新增傳票頁面部分翻譯有遺漏

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3515]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/6 12:00

### Reproduction URL

https://isunfa.tw/cn/users/accounting/add_new_voucher

### Reproduction steps

```markdown
1. Go to '新增傳票'
2. Click on 選擇發票.'
3. Scroll down to '....'
4. See error
```

### Current Result

左右鍵切換上方突然出現英文

### Screenshots

![截圖 2024-12-06 下午3 10 18](https://github.com/user-attachments/assets/8b403914-c963-4b91-ad2d-16e71ed831ac)

![截圖 2024-12-06 下午3 09 57](https://github.com/user-attachments/assets/72cbb007-17a8-46bb-8840-e1283953daca)

### Expected Result

左右鍵切換上方突然出現英文

**Comment by TzuHanLiang** [comment]
took 1hrs
done
