### ISSUE TITLE
🐛 [BUG] - 新增資產無法輸入資訊欄位

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3517]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/6 12:00

### Reproduction URL

https://isunfa.tw/users/accounting/add_new_voucher

### Reproduction steps

1. Go to '新增傳票'
2. Click on '會計科目.'
3. Scroll down to '1602 土地成本'

### Current Result

數量
總價
殘值
取得日期
折舊開始日期

滑到下方會出現一大片空白
也無法保存

上述欄位皆無法輸入

### Screenshots

![截圖 2024-12-06 下午3 35 03](https://github.com/user-attachments/assets/0fc4b075-5c0c-4d04-88b6-1ab3aadd348d)

### Expected Result

數量
總價
殘值
取得日期
折舊開始日期
數量
總價
殘值
取得日期
折舊開始日期

上述欄位皆可輸入資訊

並依照設計稿 調整排版

**Comment by Julian0701** [comment]
這個錯誤是之前測試 `react-focus-lock` 所產生的，現已移除
