### ISSUE TITLE
🐛 [BUG] - 未新增資產除變紅字外，也要有吐司通知（如設計稿）

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3518]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/6 12:00

### Reproduction URL

https://isunfa.tw/users/accounting/add_new_voucher

### Reproduction steps

1. Go to '新增傳票'
2. Click on '會計科目'
3. Scroll down to '1602 土地成本'

### Current Result

未新增資產除變紅字外，也要有吐司通知（如設計稿）

### Screenshots

![截圖 2024-12-06 下午3 48 27](https://github.com/user-attachments/assets/1828af8a-f72d-41d6-a25c-41904a550642)

### Expected Result

未新增資產除變紅字外，也要有吐司通知（如設計稿）

**Comment by Julian0701** [comment]
- take 1 hr, done
