### ISSUE TITLE
🐛 [BUG] 選擇沖銷項目出現API錯誤

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3519]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/6 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/add_new_voucher

### Reproduction steps

1. Go to '沖銷項目'

### Current Result

選擇沖銷項目 API 錯誤

### Screenshots

<img width="674" alt="截圖 2024-12-06 下午3 58 56" src="https://github.com/user-attachments/assets/693b30e3-647f-4bf5-8325-28ce2a235169">

### Expected Result

選擇沖銷項目可以正常沖銷

**Comment by Julian0701** [comment]
- take 2 hrs, done
- 調整 API Calling，目前沒看到此錯誤重現
