### ISSUE TITLE
🐛 [BUG] -發票列表已上傳憑證無故消失

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3533]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '上傳憑證'
2. Click on '發票列表'

### Current Result

已上傳成功的憑證會在發票列表消失

### Screenshots

https://github.com/user-attachments/assets/db4a8701-0ab6-4cab-8060-64bdd3e6cc2c

### Expected Result

已上傳成功的憑證會出現在發票列表

**Comment by TzuHanLiang** [comment]
took 1hrs
done
