### ISSUE TITLE
🐛 [BUG] - 資產列表翻譯有問題

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3534]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Reproduction URL

https://isunfa.tw/en/users/asset

### Reproduction steps

1. Go to '資產管理'
2. Click on ''

### Current Result

資產管理顯示單位的地．英文版會突然跑出『中文』

### Screenshots

![截圖 2024-12-09 上午11 41 57](https://github.com/user-attachments/assets/a9b0e6a9-f54b-480d-9620-953b53c4c340)

### Expected Result

資產管理顯示單位的地．英文版會正確顯示出『英文』

**Comment by Julian0701** [comment]
- take 2 hrs, done
- 調整翻譯檔
