### ISSUE TITLE
🐛 [BUG] - 會計科目設定，需準確的按到箭頭icon才能收回，不好點按

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3535]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Reproduction URL

https://isunfa.tw/users/setting/accounting_setting

### Reproduction steps

1. Go to '參數設定'
2. Click on '會計設定'

### Current Result

此處選單打開後，需準確的按到箭頭icon才能收回，不好點按

### Screenshots

![截圖 2024-12-09 上午11 57 28](https://github.com/user-attachments/assets/8668334b-1079-4d7e-9be6-eddc1fe32f34)

### Expected Result

此處選單打開後，不需準確的按到箭頭icon才能收回

**Comment by Julian0701** [comment]
- take 5 hrs, done
- 檢查和測試花了比預期更長的時間
