### ISSUE TITLE
🐛 [BUG] - 客戶和供應商頁面翻譯出現錯誤

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3536]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/setting/counterparty

### Reproduction steps

1. Go to '參數設定'
2. Click on '客戶供應商管理'

### Current Result

中文版頁面，突然出現“刪除英文”
營業稅號翻譯需改成統一編號

### Screenshots

![截圖 2024-12-09 下午12 02 26](https://github.com/user-attachments/assets/1667d49a-2936-43e3-9b12-79899a32dcd0)

### Expected Result

中文版頁面，突然出現“刪除英文”
營業稅號翻譯改成統一編號

**Comment by jing12345678910** [comment]
<img width="446" alt="image" src="https://github.com/user-attachments/assets/203e745d-7200-4483-b6d4-24a58ea84d76">

**Comment by jing12345678910** [comment]
<img width="1244" alt="image" src="https://github.com/user-attachments/assets/51a92d87-fd79-4bbc-8d46-7ab39bbe68c5">

**Comment by jing12345678910** [comment]
原本：
<img width="1124" alt="image" src="https://github.com/user-attachments/assets/f69e420d-fd37-4a68-8c1d-4f50c29b9608">
改好了：

**Comment by jing12345678910** [comment]
took 5 hrs
done
