### ISSUE TITLE
🐛 [BUG] - 客戶供應商沒有統編與抬頭的校正機制

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3537]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Reproduction URL

https://isunfa.tw/users/setting/counterparty

### Reproduction steps

1. Go to '參數設定'
2. Click on '客戶供應商管理'
3. Scroll down to '交易夥伴設定'

### Current Result

沒有統編與抬頭的校正機制，如：輸入統編，自動填寫抬頭，輸入抬頭自動填寫統編（若輸入錯誤或是該對象無統編則例外）

### Screenshots

![截圖 2024-12-09 下午2 04 10](https://github.com/user-attachments/assets/9836f605-56c0-4aa6-bcb1-ecddd0c6ee88)

### Expected Result

應有統編與抬頭的校正機制，如：輸入統編，自動填寫抬頭，輸入抬頭自動填寫統編（若輸入錯誤或是該對象無統編則例外）

**Comment by jing12345678910** [comment]
要改成下拉選單，用選的和自己打都可以

**Comment by jing12345678910** [comment]
- [X] 下拉選單，用選的

https://github.com/user-attachments/assets/dc3fc11f-9577-4a18-a0d4-72084b0e7810

**Comment by jing12345678910** [comment]
- [X] 下拉選單，但是不選，繼續自己輸入

https://github.com/user-attachments/assets/cd0bd735-0ed9-443e-b202-8b21c28c7c4e

**Comment by jing12345678910** [comment]
took 3 hrs 
done
