### ISSUE TITLE
🐛 [BUG] - 客戶供應商已填必填欄位仍無法保存

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3538]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Reproduction URL

https://isunfa.tw/users/setting/counterparty

### Reproduction steps

1. Go to '參數設定'
2. Click on '客戶/供應商'

### Current Result

必填欄位都填了 但還是無法直接按保存按鈕 需特地重新選擇一次合作伙伴類型才可以

### Screenshots

![截圖 2024-12-09 下午2 06 20](https://github.com/user-attachments/assets/eb97580f-f30b-496e-bf12-d56b1ac93eac)

### Expected Result

必填欄位都填了 可以直接按保存按鈕

**Comment by jing12345678910** [comment]
統編要改成非必填

**Comment by jing12345678910** [comment]
- [X] 查詢「搜尋台灣公司公開資訊」的公開api
- [X] 串接上述api
- [X] 搜尋內容改為下拉選單

**Comment by jing12345678910** [comment]
因為還做了上述的內容，故花比較多點數
took 8 hrs
done
