### ISSUE TITLE
🐛 [BUG] 報表格子不整齊

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3540]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### OS

macOSrsion

### Reproduction URL

https://isunfa.tw/users/reports/financials/balance_sheet

### Reproduction steps

1. Go to '報表'
2. Click on '資產負債表'

### Current Result

細項分類格式 格子不整齊

### Screenshots

![截圖 2024-12-09 下午2 44 03](https://github.com/user-attachments/assets/6cf87e39-14b3-47c5-8936-b433f47c678a)

### Expected Result

細項分類格式 格子線對齊

**Comment by jing12345678910** [comment]
改好了：
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/80017c09-3493-433f-aed6-94f5ab167837">
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/29bfe5a7-f34b-4159-8a4a-195a0b737a2e">

**Comment by jing12345678910** [comment]
took 2 hrs
done
