### ISSUE TITLE
[UX]Beta內部測試-Murky

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#3544]
測試資訊請參考 https://github.com/CAFECA-IO/iSunFA/issues/3418

**Comment by StrawHo** [comment]
測試紀錄(Murky)
內部測試任務LINK:
https://www.figma.com/slides/7fIphWOYgbRyzi8VpgBLoH/Beta-Test?node-id=1-25&t=xwm02crqfB1ymJIL-1

一:請建立以下兩家公司資訊。
花費時間約1分鐘。操作上無任何問題。

二、請查看是否有更新的系統資訊。
花費時間約24秒。 會點擊服務條款與版本號放置位置，後續有回到Dashboard查看最新消息。

三、iSunCloud為了增加品牌可信度，決定在自己的官網公布財報，對方需要相關程式碼，協助提供。
花費時間約1分24秒，過程中忘記先綁定公司，所以無法生成程式碼，此部分與設計流程不符需調整，設計流程為使用者如未綁定公司沒辦法點擊報告相關功能。

四、漢堡王接到大客戶「台積電」，麻煩協助將此客戶建檔。
花費時間約1分18秒。能夠順利切到對應公司並且點擊設定進行建立客戶資訊。

五、請分別將iSuncloud ， 漢堡王 兩間公司的12月憑證進行上傳。
花費時間約1分鐘29秒。可以順利切換公司並且上傳不同公司的憑證。

六、iSunCloud在12/15需要繳房租了，麻煩開立一張傳票來記錄此事。
花費時間約2分鐘5秒。目前版本是需要先新增交易對象的，所以與設計稿流程並不符合(後續須調整)。

七、剛剛收到老闆通知，房租已經繳了，麻煩開立另一張傳票紀錄此事。
此任務無測試。

八、查看iSuncloud公司11月份的資產負債表。
花費時間約39秒。操作上無問題。

九、iSuncloud有一台資產編號A-000010的Macbook要報廢，請協助紀錄此事件。
此任務無測試，因無法建立資產且資產清單目前為空值。
--

總結
使用者本身為有會計背景與專業知識人士且使用過iSunFA平台，對於平台功能熟悉，在內部測試環節上並無操作問題。
在建立傳票上的習慣是會去以文字的方式做搜尋，但這也有影響到使用者在找尋到他想要的會計科目的時間，後續針對文字搜尋方式是否要做篩選優化可以是下一步考慮調整的方向。

SUS File LINK:

[iSunFA 會計軟體易用性評估表 - Murky.pdf](https://github.com/user-attachments/files/18107352/iSunFA.-.Murky.pdf)


測試時間約25min，整理記錄時間約15 min，總花費時間約 40min。

**Comment by JodieWu** [comment]
二、請查看是否有更新的系統資訊。
花費時間約24秒。 會點擊服務條款與版本號放置位置，後續有回到Dashboard查看最新消息。

**可新增版本號連結到最新版本更新資訊文章**

三、iSunCloud為了增加品牌可信度，決定在自己的官網公布財報，對方需要相關程式碼，協助提供。
花費時間約1分24秒，過程中忘記先綁定公司，所以無法生成程式碼，此部分與設計流程不符需調整，設計流程為使用者如未綁定公司沒辦法點擊報告相關功能。

**或是點擊後直接跳彈窗提示，可能更清楚**
