### ISSUE TITLE
🐛 [BUG] - 更新User Setting的時候，成功更新之後會被彈出來

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#3546]
### Searched for similar issues

- [X] YES, I have searched for similar issues.

### Time of occurrence

2024/12/9

### Device

None

### OS

Linux

### Reproduction URL

https://isunfa.tw/users/setting/general

### Reproduction steps

```markdown
1. 前往 `https://isunfa.tw/users/setting/general`
2. 更新User Setting
3. 成功更新之後被跳轉
```

### Current Result

```markdown
1. 前往 `https://isunfa.tw/users/setting/general`
2. 更新User Setting
3. 成功更新之後被跳轉
```

### Screenshots

https://github.com/user-attachments/assets/547f9cdf-7cc3-4c78-b18f-23544f97b11d

更新User Setting的時候，成功更新之後會被彈出來

可能原因：前端在 Post 的時候使用 `<form>`上傳，導致頁面重新刷新而喪失 user Auth

![image](https://github.com/user-attachments/assets/5d220df1-766c-41fb-a617-8ff24d427e64)

### Expected Result

```markdown
希望可以單在同一個頁面並且get到結果
```

**Comment by TzuHanLiang** [comment]
took 0.5hrs
remain test

**Comment by TzuHanLiang** [comment]
test success
done

**Comment by TzuHanLiang** [comment]
took 1hrs
remain 1hrs

**Comment by TzuHanLiang** [comment]
took 3hrs
done
