### ISSUE TITLE
🐛 [BUG] - 嵌入程式碼複製成功少了吐司通知

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3547]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Reproduction URL

https://isunfa.tw/users/reports/tax/business_tax

### Reproduction steps

1. Go to '報表'
2. Click on '嵌入程式碼'

### Current Result

複製成功少了吐司通知

### Screenshots

![截圖 2024-12-09 下午2 55 41](https://github.com/user-attachments/assets/1e84e899-2c1e-497d-88d4-a2acd4bf29cc)

### Expected Result

複製成功需要跳吐司通知

**Comment by jing12345678910** [comment]
- [ ] 右下角為「關閉」，而非「取消」

**Comment by jing12345678910** [comment]
- [X] 複製成功需要跳吐司通知

<img width="1430" alt="image" src="https://github.com/user-attachments/assets/1ea0f45c-7d00-4a6a-9f00-becaedb17152">

**Comment by jing12345678910** [comment]
took 5 hrs
done
