### ISSUE TITLE
🐛 [BUG] 儀表板 待處理任務數字 須可以跳轉到對應畫面

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3549]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Reproduction URL

https://isunfa.tw/users/dashboard

### Reproduction steps

1. Go to '儀表板'
2. Click on '待處理任務'

### Current Result

數字需直接跳轉到需要處理的畫面

### Screenshots

![截圖 2024-12-09 下午3 49 39](https://github.com/user-attachments/assets/c85c7666-c266-44d4-8a5f-98c4602d39f8)

### Expected Result

數字需直接跳轉到需要處理的畫面

**Comment by godmmt** [comment]
經與設計師討論後
這個數字不會連結出去
