### ISSUE TITLE
🐛 [BUG] - 上傳發票的更新資料數量tag，若筆數為”0“ 則直接隱藏Tag，不需顯示0的Tag

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3559]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '上傳憑證'
2. Click on '發票列表'

### Current Result

只要Tab旁邊有新資料數量的Tag時，若筆數為”0“ 則直接隱藏Tag，不需顯示0的Tag

### Screenshots

<img width="783" alt="截圖 2024-12-09 下午7 32 44" src="https://github.com/user-attachments/assets/77f1115d-11ae-4763-8548-8cb9d6e66da2">

### Expected Result

只要Tab旁邊有新資料數量的Tag時，若筆數為”0“ 則直接隱藏Tag，不需顯示”0“ 的Tag

**Comment by TzuHanLiang** [comment]
took 1hrs
done

**Comment by TzuHanLiang** [comment]
took 0.5hrs fixed
