### ISSUE TITLE
🐛 [BUG] - Side Menu 固定寬度為280 px，無論中文英文，無論子選單還是母選單

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3560]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '側邊欄位'

### Current Result

Side Menu 固定寬度為280 px，無論中文英文，無論子選單還是母選單

### Screenshots

<img width="867" alt="截圖 2024-12-09 下午7 36 18" src="https://github.com/user-attachments/assets/c60bed74-7aa8-4087-95fa-f296e63f151a">

### Expected Result

Side Menu 固定寬度為280 px，無論中文英文，無論子選單還是母選單

**Comment by godmmt** [comment]
已經開過票了 https://github.com/CAFECA-IO/iSunFA/issues/3556
