### ISSUE TITLE
🐛 [BUG] - 儀表板公司頭像，顯示的文字並非公司名，排版不正確

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3561]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/dashboard

### Reproduction steps

1. Go to '儀表板'
2. Click on '我的公司列表.'
3. Scroll down to '.'

### Current Result

依照設計稿排版 應該是不只能顯示3家公司
公司縮圖呈現每家公司的名稱而非『公司』

### Screenshots

![截圖 2024-12-09 下午8 06 11](https://github.com/user-attachments/assets/d8dfc461-6e3c-4b9e-874c-7020f1947640)

### Expected Result

依照設計稿排版 應該是不只能顯示3家公司
公司縮圖呈現每家公司的名稱而非『公司』

**Comment by godmmt** [comment]
@TeresaYang00 
這不是 bug
是設計稿有更新
並且之前已經開過票了 https://github.com/CAFECA-IO/iSunFA/issues/3551
所以你這張 bug 可以 wont fix

**Comment by godmmt** [comment]
之前已經開過票了 https://github.com/CAFECA-IO/iSunFA/issues/3551
