### ISSUE TITLE
🐛 [BUG] - 上傳憑證 More options 應該是點按觸發，不是hover

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3562]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '上傳發票'
2. Click on '發票列表'

### Current Result

More options 應該是點按觸發，不是hover

### Screenshots

https://github.com/user-attachments/assets/71b80711-d9b6-4280-bf1a-3379134d78a4

### Expected Result

More options 應該是點按觸發，不是hover

**Comment by TzuHanLiang** [comment]
took 1hrs
done

**Comment by TzuHanLiang** [comment]
took 0.5hrs done
