### ISSUE TITLE
🐛 [BUG] - 上傳發票 Select畫面應該在我轉跳到其他地方後就要恢復原狀

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3563]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '上傳發票'
2. Click on '發票列表'

### Current Result

Select畫面應該在我轉跳到其他地方後就要恢復原狀

### Screenshots

https://github.com/user-attachments/assets/5eaefab3-ab84-474c-9211-d83dda06bf40

### Expected Result

Select畫面應該在我轉跳到其他地方後就要恢復原狀

**Comment by TzuHanLiang** [comment]
took 1hrs
done
