### ISSUE TITLE
🐛 [BUG] - 上傳發票QRcode 手機的「掃描器」應該也是藍色的字且具有超連結

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3564]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

```markdown
1. Go to '上傳發票'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Current Result

上傳發票QRcode 手機的「掃描器」應該也是藍色的字且具有超連結

### Screenshots

![截圖 2024-12-09 下午8 21 29](https://github.com/user-attachments/assets/e11bae1b-ce32-4011-a450-e7cfcca94a1a)

### Expected Result

上傳發票QRcode 手機的「掃描器」應該也是藍色的字且具有超連結

**Comment by TzuHanLiang** [comment]
took 1hrs
done

**Comment by TzuHanLiang** [comment]
took 0.5 done
