### ISSUE TITLE
🐛 [BUG] - 通知設定開關打開，跳轉其他頁面再回來，又會自己被關起來

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3565]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/setting/general

### Reproduction steps

```markdown
1. Go to '參數設定'
2. Click on '一般設定'
3. Scroll down to '通知設定'
4. See error
```

### Current Result

通知設定開關打開，跳轉其他頁面再回來，又會自己被關起來

### Screenshots

![截圖 2024-12-09 下午8 27 49](https://github.com/user-attachments/assets/a809d7fa-1cef-4a78-9f28-fc015955c81c)

### Expected Result

通知設定開關打開，跳轉其他頁面再回來，不會自己被關起來

**Comment by TzuHanLiang** [comment]
took 0.5hrs
done
