### ISSUE TITLE
🐛 [BUG] - 帳戶設定突然出現簡體字

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3566]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/setting/general

### Reproduction steps

1. Go to '參數設定'
2. Click on '一般設定'
3. Scroll down to '刪除此帳戶'

### Current Result

刪除此帳戶 突然變成簡體字

### Screenshots

![截圖 2024-12-09 下午8 32 40](https://github.com/user-attachments/assets/510a1f81-4f8d-43e3-8970-9654cb39e2fd)

### Expected Result

刪除此帳戶 變成符合當下設定的語言文字

**Comment by TzuHanLiang** [comment]
took 1hrs
done
