### ISSUE TITLE
🐛 [BUG]  一般設定已先選擇好國家，但在輸入電話數字時，國家下拉選單還是會被打開

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3567]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/setting/general

### Reproduction steps

```markdown
1. Go to '參數設定'
2. Click on '一般設定'
3. Scroll down to '....'
4. See error
```

### Current Result

```markdown
已先選擇好國家，但在輸入數字時，下拉選單還是會被打開
```

### Screenshots

![DESCRIPTION](LINK.png)

### Expected Result

```markdown
已先選擇好國家，但在輸入電話數字時，下拉選單會自動先跳轉選擇的國家
如要改成其他國家電話號碼 用戶再自行調整
```

**Comment by TzuHanLiang** [comment]
took 1 hrs
done
