### ISSUE TITLE
🐛 [BUG] -一般設定裡用戶名稱未能修改儲存成功

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3568]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/setting/general

### Reproduction steps

```markdown
1. Go to '參數設定'
2. Click on '一般設定'
3. Scroll down to '....'
4. See error
```

### Current Result

```markdown
一般設定裡用戶名稱未能修改儲存成功
```

### Screenshots

![截圖 2024-12-09 下午8 54 16](https://github.com/user-attachments/assets/2f28f18f-3663-46a8-8e2e-121441599bef)

### Expected Result

```markdown
一般設定裡用戶名稱未能修改儲存成功
```

**Comment by TzuHanLiang** [comment]
took 1hrs
done

**Comment by TzuHanLiang** [comment]
https://github.com/user-attachments/assets/413aa0ac-4d98-40a9-a472-a6ea33265f47

took 1hrs
done
