### ISSUE TITLE
🐛 [BUG] 公司列表的工作標籤排版問題

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3584]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/10 12:00

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.tw/users/setting/general

### Reproduction steps

1. Go to '參數設定'
2. Click on '一般設定'
3. Scroll down to '公司設定'
4. 點選 '查看所有公司'

### Current Result

工作標籤應該是置中不是置左

### Screenshots

![截圖 2024-12-10 下午3 49 19](https://github.com/user-attachments/assets/327404d3-37fe-4305-a1d2-a0b753763ede)

### Expected Result

工作標籤應該是置中不是置左

**Comment by TzuHanLiang** [comment]
took 1hrs
done
