### ISSUE TITLE
🐛 [BUG] 隱私權和服務條款需有超連結

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3585]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/10 12:00

### Device

None

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.tw/users/setting/general

### Reproduction steps

1. Go to '左側欄位下方'
2. Click on '隱私權政策和服務條款'

### Current Result

隱私權和服務條款未有超連結

### Screenshots
![截圖 2024-12-10 下午4 30 39](https://github.com/user-attachments/assets/0b16dc08-9811-4194-84fc-3ab89f235d02)

### Expected Result

隱私權和服務條款需有超連結

**Comment by godmmt** [comment]
已經修過了
