### ISSUE TITLE
[Fix]  ToDoListPage - deleteTodo 刪除事件功能

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#3588]
# connect deleteTodo api - Internal service error

### API : [deleteTodo](https://github.com/CAFECA-IO/iSunFA/wiki/API-v2#deletetodo)

之前功能是 OK 的 : https://github.com/CAFECA-IO/iSunFA/issues/2979

doc path : 
`src/components/beta/todo_list_page/todo_list_page_body.tsx`

- [x] 詢問後端

**Comment by TinyMurky** [comment]
這個錯誤是因為如果todo list 只剩下一個的時候，被刪除的話他不會從畫面上消失，但是已經刪除成功了，所以再刪一次會出現找不到要刪哪個的錯誤

https://github.com/user-attachments/assets/3021768e-c125-4530-bcfc-abb6bba8cadf

**Comment by godmmt** [comment]
took 1 

done
