### ISSUE TITLE
🐛 [BUG] - 新增交易夥伴的時候，沒有「統一編號」與「交易夥伴公司抬頭」的校正機制

### ISSUE THREAD

**Issue by jing12345678910** [CAFECA-IO/iSunFA#3592]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/11 11:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/setting/counterparty

### Reproduction steps

```markdown
1. Go to '參數設定'
2. Click on '客戶/供應商管理'
3. Scroll down to '新增客戶/供應商'
4. See error
```

### Current Result

```markdown
這兩個欄位，沒有連動
```

### Screenshots

<img width="437" alt="image" src="https://github.com/user-attachments/assets/68087ed5-2fea-4b73-a8a7-3f16ada5809d">

### Expected Result

```markdown
這兩個欄位，應該要連動，資料來源是「台灣的所有公司資料」
```

**Comment by jing12345678910** [comment]
查詢到的公開api：

1. https://www.opendata.vip/tool/company
    打的方式：https://opendata.vip/data/company?keyword=52414797
    response：
    ```
    {"source":{"keyword":"52414797"},"output":[{"Business_Accounting_NO":"52414797","Company_Status_Desc":"核准設立","Company_Name":"台灣陽光雲有限公司","Capital_Stock_Amount":12000000,"Paid_In_Capital_Amount":0,"Responsible_Name":"馬建英","Company_Location":"臺北市信義區信義路5段150巷2號13樓之6","Register_Organization_Desc":"臺北市政府","Company_Setup_Date":"1051108","Change_Of_Approval_Data":"1121211","Revoke_App_Date":"","Case_Status":"","Case_Status_Desc":"","Sus_App_Date":"","Sus_Beg_Date":"","Sus_End_Date":""}]}
    ```

2. https://data.gcis.nat.gov.tw/od/rule
    打的方式：https://data.gcis.nat.gov.tw/od/data/api/6BBA2268-1367-4B42-9CCA-BC17499EBE8C?$format=json&$filter=Company_Name%20like%20%E5%8F%B0%E7%81%A3%E7%A9%8D%E9%AB%94%E9%9B%BB%E8%B7%AF%E8%A3%BD%E9%80%A0%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8%20and%20Company_Status%20eq%2001&$skip=0&$top=1
    response：
    ```
    [{"Business_Accounting_NO":"22099131","Company_Name":"台灣積體電路製造股份有限公司","Company_Status":"01","Company_Status_Desc":"核准設立","Capital_Stock_Amount":280500000000,"Paid_In_Capital_Amount":259327332420,"Responsible_Name":"魏哲家","Register_Organization":"05","Register_Organization_Desc":"國家科學及技術委員會新竹科學園區管理局","Company_Location":"新竹科學園區新竹市力行六路8號","Company_Setup_Date":"0760221","Change_Of_Approval_Data":"1130911"}]
    ```

**Comment by jing12345678910** [comment]
1. 先打

https://data.gcis.nat.gov.tw/od/data/api/6BBA2268-1367-4B42-9CCA-BC17499EBE8C?$format=json&$filter=Company_Name%20like%20%E5%8F%B0%E7%81%A3%E7%A9%8D%E9%AB%94%E9%9B%BB%E8%B7%AF%E8%A3%BD%E9%80%A0%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8%20and%20Company_Status%20eq%2001&$skip=0&$top=1
試試看，

2. 出錯：

console
![image](https://github.com/user-attachments/assets/6387e04a-8dc8-4463-bd5f-8376524d8aee)

network
![image](https://github.com/user-attachments/assets/468e8cda-aafb-416d-9db5-54d9a39ba348)

3. 結論：
`const response = await fetch(apiUrl);`
錯誤是`Failed to load resource: net::ERR_FAILED`

這段代碼中的問題來自於 CORS（跨來源資源共享） 限制。由於 fetch 請求被瀏覽器的安全策略限制，無法從 http://localhost:3000/ 向 https://data.gcis.nat.gov.tw/ 發送跨來源請求。>> 好像是我沒辦法打到外面的api
方法：
使用代理伺服器
配置一個後端代理伺服器，讓前端請求通過自己的後端轉發到目標 API。
範例：在 Node.js 後端中新增一個 API 路徑，用於轉發請求。
```
const express = require('express');
const axios = require('axios');
const app = express();

app.get('/api/proxy', async (req, res) => {
  const { companyName } = req.query;
  const apiUrl = `https://data.gcis.nat.gov.tw/od/data/api/6BBA2268-1367-4B42-9CCA-BC17499EBE8C?$format=json&$filter=Company_Name%20like%20${encodeURIComponent(
    companyName
  )}%20and%20Company_Status%20eq%2001&$skip=0&$top=1`;

  try {
    const response = await axios.get(apiUrl);
    res.json(response.data);
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch data' });
  }
});

app.listen(3001, () => {
  console.log('Proxy server running on http://localhost:3001/');
});
```
前端將請求改為代理路徑：
`const apiUrl = `/api/proxy?companyName=${encodedName}`;`

**Comment by TinyMurky** [comment]
![image](https://github.com/user-attachments/assets/88b39858-44b3-413b-87c8-2eacadbeb6e2)

**Comment by TinyMurky** [comment]
took 2 hours
done

**Comment by jing12345678910** [comment]
https://github.com/user-attachments/assets/a9727c99-a30e-402d-b58b-1d855aca3bb8
