### ISSUE TITLE
🐛 [BUG] - 資產負債表科目的餘額，和點開「詳細資訊」裡面的明細金額加總，不符

### ISSUE THREAD

**Issue by jing12345678910** [CAFECA-IO/iSunFA#3600]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/11 16:00

### Device

None

### OS

macOS

### Reproduction URL

http://localhost:3000/users/reports/financials/balance_sheet

### Reproduction steps

```markdown
1. Go to '報表'
2. Click on '資產負債表'
3. Click on '細項分類格式'
4. Click on '展開'
5. Click on '詳細資訊'
6. See error
```

### Current Result

```markdown
庫存現金的餘額，顯示為1,001,333，但是點開裡面的詳細資訊，加總不是這個金額
```

### Screenshots

<img width="1004" alt="image" src="https://github.com/user-attachments/assets/71a723b5-8878-40c5-84cd-7a35327dbde2">
<img width="911" alt="image" src="https://github.com/user-attachments/assets/af5a4462-591d-4da5-87a9-9852d6705e75">

### Expected Result

```markdown
庫存現金的餘額，顯示為1,001,333，但是點開裡面的詳細資訊，加總也要是1,001,333才對
```

**Comment by TinyMurky** [comment]
目前修復成為子科目也可以正常顯示
![image](https://github.com/user-attachments/assets/115ed550-3edb-4347-9363-dc26f355eb58)

**Comment by TinyMurky** [comment]
took 2 hours
done

**Comment by jing12345678910** [comment]
測試：
<img width="855" alt="image" src="https://github.com/user-attachments/assets/927b8c1b-b8c7-4136-ae88-275fffeca679" />

<img width="908" alt="image" src="https://github.com/user-attachments/assets/a9dec0f5-89be-4a64-9015-8f36fc9a33f6" />
結果：外層餘額和彈窗的明細，已經對上了

**Comment by jing12345678910** [comment]
took 2 hours
done
