### ISSUE TITLE
🐛 [BUG] - 資產負債表選擇期間選定為單一時間點 

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3607]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/11 18:00

### Device

None

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.tw/users/reports/financials/balance_sheet

### Reproduction steps

1. Go to '報表'
2. Click on '資產負債表'

### Current Result

資產負債表選擇期間選定為 『一段期間』

### Screenshots

![截圖 2024-12-11 下午6 46 07](https://github.com/user-attachments/assets/8b98f749-7d9c-458b-bf29-634f0afa9b71)

### Expected Result

資產負債表選擇期間選定為單一時間點

**Comment by jing12345678910** [comment]
改好了：

https://github.com/user-attachments/assets/748486c6-75e5-4e66-b587-d9bc78505dfd

**Comment by jing12345678910** [comment]
took 5 hrs
done
