### ISSUE TITLE
🐛 [BUG] 憑證上傳檔案限制異常

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3613]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/12 12:00

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '會計'
2. Click on '上傳發票'

### Current Result

憑證上傳檔案限制異常,檔案大小未超過限制，卻無法上傳發票

### Screenshots

![截圖 2024-12-05 下午6 09 18](https://github.com/user-attachments/assets/fa9c6a1c-20a2-430c-a73d-0ad224de8510)

### Expected Result

憑證上傳檔案限制異常
1.畫面與後端統一限制最大 4MB
2.錯誤訊息應顯示：檔案大小超過 4 MB 上限

**Comment by TzuHanLiang** [comment]
took 1hrs
done
