### ISSUE TITLE
🐛 [BUG] - 資產清單 API 出現異常 

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3618]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/12 12:00

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.tw/users/asset

### Reproduction steps

1. Go to '資產管理'
2. Click on '資產清單'

### Current Result

api出現異常

### Screenshots

![截圖 2024-12-12 下午5 23 55](https://github.com/user-attachments/assets/4513b5f6-d037-43cf-b86d-aa46edd1a445)

### Expected Result

可以顯示資產清單裡的資訊

**Comment by arealclimber** [comment]
造成 List asset API 錯誤的原因有

1. 後端的 type, status query 缺少 All 
2. 後端的 type 期望是 account code，前端給的是 account name

**Comment by arealclimber** [comment]
1. 後端的 type, status query 缺少 All ✅ 

> 造成 List asset API 錯誤的原因有
> 
> 1. 後端的 type, status query 缺少 All
> 2. 後端的 type 期望是 account code，前端給的是 account name

**Comment by arealclimber** [comment]
https://github.com/user-attachments/assets/b3be732c-df62-4c43-a5ba-40b5ca9e59af

**Comment by Julian0701** [comment]
- take 3 hrs, done
- 調整前端顯示
