### ISSUE TITLE
🐛 [BUG] - 上傳發票之後，圖片縮圖模糊和比例不正確

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3619]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/12 12:00

### Device

None

### OS

macOS

### Browser Version

chrome

### Reproduction URL

https://isunfa.tw/users/accounting/add_new_voucher

### Reproduction steps

1. Go to '會計'
2. Click on '上傳發票'

### Current Result

```markdown
上傳發票之後，圖片縮圖模糊和比例不正確
```

### Screenshots

![截圖 2024-12-12 下午5 02 21](https://github.com/user-attachments/assets/292a433b-9264-442d-a581-60f187ef3a04)

此為上傳原圖
![截圖 2024-12-11 下午6 46 07](https://github.com/user-attachments/assets/7599cda4-5a85-49ad-9db6-d296c5199241)

### Expected Result

上傳發票之後，圖片縮圖清楚和比例正確

**Comment by TzuHanLiang** [comment]
took 3hrs
remain 跟設計師確認

**Comment by TzuHanLiang** [comment]
<img width="870" alt="Screenshot 2024-12-18 at 4 37 33 PM" src="https://github.com/user-attachments/assets/d902cc5e-1751-4dc1-9ee8-c7e25f1a9046" />
<img width="1257" alt="Screenshot 2024-12-18 at 4 38 30 PM" src="https://github.com/user-attachments/assets/e5b435de-5a12-47b5-903f-e12e59caeb34" />

更新傳票裡面的發票thumbnail

**Comment by TzuHanLiang** [comment]
<img width="1025" alt="Screenshot 2024-12-18 at 4 39 25 PM" src="https://github.com/user-attachments/assets/a1241e8f-c861-4560-8e64-99d0ae427608" />
<img width="1680" alt="Screenshot 2024-12-18 at 4 40 28 PM" src="https://github.com/user-attachments/assets/16742168-eb8f-4855-8fe7-a3db198b4d74" />
<img width="1680" alt="Screenshot 2024-12-18 at 4 41 30 PM" src="https://github.com/user-attachments/assets/0aa38b2f-b4b1-49ed-a24d-7b9219d0b8f4" />

**Comment by TzuHanLiang** [comment]
<img width="603" alt="Screenshot 2024-12-18 at 4 43 59 PM" src="https://github.com/user-attachments/assets/90b73df3-b543-4b49-93a0-0675b7714eea" />
took 2hrs
done
