### ISSUE TITLE
🐛 [BUG] - 發票名稱修改 ，調整文字名稱沒辦法全部完整看到

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3626]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/13 12:00

### Device

None

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.com/users/select-company

### Reproduction steps

1. Go to '發票列表'
2. Click on '上傳發票.'

### Current Result

發票圖片名稱修改功能
可以修改但是調整中的時候字沒辦法全部完整看到

### Screenshots

https://github.com/user-attachments/assets/3100c0a7-3419-4a6a-947f-0254efcb2e03

### Expected Result

發票圖片名稱修改功能
可以修改但是調整中的時候字可以清楚完整看到

**Comment by TzuHanLiang** [comment]
https://github.com/user-attachments/assets/5e163c1b-1475-4377-b914-aefedb97f800

took 1.5hrs
done
