### ISSUE TITLE
🐛 [BUG] - 資產負債表報表跑版錯位問題

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3631]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/13 12:00

### Device

None

_No response_

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/reports/financials/balance_sheet

### Reproduction steps

1. Go to '報表'
2. Click on '資產負債表'

### Current Result

如圖片和設計稿說明

### Screenshots

![截圖 2024-12-13 下午2 07 50](https://github.com/user-attachments/assets/b215e4f1-d304-4e1b-98c4-da2adad0ff9f)
![截圖 2024-12-13 下午2 04 33](https://github.com/user-attachments/assets/7a552b62-91b4-4a4d-a806-b31eabd8e8da)
![截圖 2024-12-13 下午2 03 01](https://github.com/user-attachments/assets/67248cda-9545-48f8-8e7a-abc2be1aa12a)
![截圖 2024-12-13 下午2 00 58](https://github.com/user-attachments/assets/8ecdd929-4d6f-4325-99cf-fe204b9570f9)
![截圖 2024-12-13 下午1 58 36](https://github.com/user-attachments/assets/297e0781-e75b-49af-b463-3da51441d319)

### Expected Result

如圖片和設計稿說明

**Comment by jing12345678910** [comment]
第一個問題：
已經都改成用統一的「沒有資料的圖示」了
<img width="1203" alt="image" src="https://github.com/user-attachments/assets/a442a2c5-8231-45c6-b7db-7784dbc68f84" />
<img width="1204" alt="image" src="https://github.com/user-attachments/assets/25652fd1-bb7e-4632-9e0a-fb6c2befc049" />

**Comment by jing12345678910** [comment]
第四個問題
設計稿的子科目代碼，是和父層科目的代碼，在不同欄位沒錯
<img width="1461" alt="image" src="https://github.com/user-attachments/assets/988d267e-4c99-4e7b-810f-c49731a9bb9d" />

**Comment by jing12345678910** [comment]
第五個問題：
搜尋ACCOUNTING_ACCOUNT已經搜不到了，會計科目的翻譯都補好了
<img width="1458" alt="image" src="https://github.com/user-attachments/assets/53dcc8ff-de32-4b2a-b476-e6473344c337" />

**Comment by jing12345678910** [comment]
第六個問題：
列高調整好了
<img width="1203" alt="image" src="https://github.com/user-attachments/assets/68fe1bf8-6f49-44ee-ae96-86b18327ef65" />

**Comment by jing12345678910** [comment]
第七個問題：
「項目彙總格式」和「細項分類格式」的欄位寬度，都調整一樣了
<img width="1275" alt="image" src="https://github.com/user-attachments/assets/936667c7-8c47-46a6-ba35-de6753f2f5e1" />

**Comment by jing12345678910** [comment]
took 5 hrs
done
