### ISSUE TITLE
🐛 [BUG] - 損益表版面的問題

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3632]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/13 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/reports/financials/income_statement

### Reproduction steps

1. Go to '報表'
2. Click on '損益表'

### Current Result

如圖上解釋

### Screenshots

![截圖 2024-12-13 下午2 34 00](https://github.com/user-attachments/assets/7bdeca11-5bef-494e-84b6-e5d310766147)
![截圖 2024-12-13 下午2 22 03](https://github.com/user-attachments/assets/a8f3b067-02a5-484a-adc5-7bb56b909df0)

### Expected Result

如圖上解釋

**Comment by jing12345678910** [comment]
第一個問題：設計稿是有的
<img width="513" alt="image" src="https://github.com/user-attachments/assets/85e2dbc6-0c84-4e75-9e1a-a275625385c7" />

**Comment by jing12345678910** [comment]
第二個問題：

- 字體大小調整一樣了

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/4c734890-b968-48ee-b6fd-7fc3132e5a9f" />

- 欄位寬度也都調整為相同

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/d13e9cf0-8b37-4a99-85c1-59b2b6efb980" />

**Comment by jing12345678910** [comment]
took 5 hrs
done
