### ISSUE TITLE
🐛 [BUG]會計新增傳票，選擇發票的時候，發票名稱跑版

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3634]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/13 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/add_new_voucher

### Reproduction steps

1. Go to '會計'
2. Click on '新增傳票'
3. Scroll down to '選擇發票'

### Current Result

如圖片說明

### Screenshots
![截圖 2024-12-13 下午3 13 49](https://github.com/user-attachments/assets/cc8f9605-3f64-4233-99a8-d7ec23f5de50)

除了跑版還會重複名稱

### Expected Result

如圖片說明

**Comment by TzuHanLiang** [comment]
took 1hrs
done
