### ISSUE TITLE
🐛 [BUG] - 發票列表的稅額和點進去實際呈現的稅額不一致

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3650]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/16  12:00

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '上傳憑證'
2. Click on '發票列表'

### Current Result

新上傳的發票尚未輸入任何資訊的情況 
會先跑出Taxable 0% 在列表上
但點進去會預設是 應稅金額 5%

### Screenshots

![截圖 2024-12-16 下午3 15 50](https://github.com/user-attachments/assets/68a346df-00ea-453a-9861-667cb29c6814)

![截圖 2024-12-16 下午3 16 17](https://github.com/user-attachments/assets/8b713abd-f2e5-4176-bed4-7f3a75418092)

### Expected Result

新上傳的發票尚未輸入任何資訊的情況 
會先跑出Taxable 0% 在列表上
但點進去會預設是 應稅金額 5%

**Comment by TzuHanLiang** [comment]
https://github.com/user-attachments/assets/3c104a3c-7b51-4a92-a30f-f5346c2dc1d3

took 1hrs
done
