### ISSUE TITLE
🐛 [BUG] -會計設定應稅率並無影響上傳發票的預設值

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3651]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/16 12:00

### OS

macOS

### Browser

chrome

### Reproduction URL

https://isunfa.tw/users/setting/accounting_setting

### Reproduction steps

1. Go to '一般設定'
2. Click on '會計設定'

### Current Result

會計設定應稅率並無影響上傳發票的預設值

### Screenshots
![截圖 2024-12-16 下午3 34 33](https://github.com/user-attachments/assets/4de7bf67-57c5-478c-b99c-1265d224f103)

### Expected Result

會計設定應稅率並 需影響上傳發票的預設值

**Comment by TzuHanLiang** [comment]
took 1hrs
done

**Comment by TzuHanLiang** [comment]
https://github.com/user-attachments/assets/458a7248-d089-4740-a85d-32244f22d0a9
