### ISSUE TITLE
🐛 [BUG] - 發票列表上傳發票無法上傳

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3658]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/17 12:00

### OS

macOS

### Browsers

 Chrome

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '會計'
2. Click on '發票列表'

### Current Result

目前已先確認上傳圖片小於4MB

### Screenshots

https://github.com/user-attachments/assets/dd29f586-75ec-4663-aff1-fbd748f9f6d9

### Expected Result

目前已先確認上傳的圖片小於4MB 
應是要可以正常上傳

**Comment by TinyMurky** [comment]
took 3 hours
done
主要花在架設server swarm 在local
