### ISSUE TITLE
[UI] 新增與調整 Team 功能頁面

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#3661]
- 訂閱是以團隊，並非以帳號。(與Figma相同)

 - 新增新的管理員階級
目前管理員階級分為: Owner>Admin>Editer>Viewer。

- 團隊資訊需綁定銀行帳戶，並由Owner進行銀行帳戶的新增。

- 新增被邀請至團隊之通知

**Comment by StrawHo** [comment]
根據後續會議討論
新增了調整的頁面與修改現有的團隊建立流程。

參考:
https://github.com/CAFECA-IO/EventReport/blob/main/meeting/20241218_isunfa_team&Sub.md

**Comment by StrawHo** [comment]
12/18 進度
- 已新增被受邀至團隊通知
- 調整帳本名稱&Module
- 建立帳本流程調整
- 新增轉移帳本彈窗
- 建立團隊彈窗
- 團隊名單調整

剩餘部分
建立團隊第三步驟(與訂閱相關看有無需要調整或直接省略)
團隊資訊page

LINK:
https://www.figma.com/design/qSOAuNX7hxVQaKD51ghONu/iSunFA-Mockup-(Beta)?node-id=5-12192&t=CJGFiLSWT4O0VYNJ-1

花費時間約5hr，預計剩餘部分約2~3hr完成。

**Comment by TeresaYang00** [comment]
# Canva 與 Figma：團隊與訂閱方案比較

## 比較表

| **功能/方案**             | **Canva**                                                                                          | **Figma**                                                                                              |
|----------------------------|----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
| **免費方案**               | 基本設計功能，允許邀請他人編輯或查看設計，但團隊功能有限。                                          | 支援團隊在 3 個活躍檔案上協作，草稿檔案數量無限制。                                                   |
| **適用對象**               | 個人及小型團隊，快速創建視覺內容。                                                                 | 個人或小型設計團隊，需要協作但檔案需求少的團隊。                                                     |
|                            |                                                                                                    |                                                                                                       |
| **付費方案 - Pro / 專業版**| 每人每月 $12.99，包含超過 1 億高級素材、100GB 雲端儲存、自訂品牌套件、背景移除及設計尺寸調整等工具。   | 每人每月 $12，提供無限制的檔案數量、共享元件庫及進階檔案管理工具。                                     |
| **適用對象**               | 需要高級素材與協作工具的中型團隊。                                                                 | 中型設計團隊，注重元件重用與團隊效率提升。                                                           |
|                            |                                                                                                    |                                                                                                       |
| **付費方案 - Enterprise / 組織版** | 每人每月 $30，提供進階品牌管理、工作流程工具和進階權限設定。                                        | 每人每月 $45，包含強大的安全性、進階管理功能及跨部門協作的需求。                                      |
| **適用對象**               | 大型企業與需要品牌一致性管理的團隊。                                                               | 大型專業設計團隊或對安全性與管理有高要求的企業。                                                     |
|                            |                                                                                                    |                                                                                                       |
| **協作功能**               | 即時協作、多用戶編輯、評論功能和分享連結。                                                          | 支援多用戶即時編輯、版本歷史記錄、評論功能及與 FigJam 的無縫整合。                                     |
| **其他特色**               | 簡化社群貼文、簡報、海報、名片等內容的創建。                                                       | 提供專業的 UI/UX 設計與原型製作工具，適合完整設計流程的協作。                                         |

## 總結

- **Canva** 適合尋求簡單易用、快速產出視覺內容的團隊，如行銷或教育團隊。其範本豐富，介面直觀，適合非專業設計人員使用。
- **Figma** 則專注於專業設計協作，特別是 UI/UX 設計團隊。其即時協作、元件重用及與 FigJam 的整合，使其成為進階設計工作流程的強大工具。

### 推薦

**Comment by StrawHo** [comment]
LINK:
https://www.figma.com/design/qSOAuNX7hxVQaKD51ghONu/iSunFA-Mockup-(Beta)?node-id=5-12192&t=kKpc6HDrmMCE9DIm-1

花費時間約2.5hr Done!
