### ISSUE TITLE
[FEATURE] - 傳票清單的分頁功能

### ISSUE THREAD

**Issue by jing12345678910** [CAFECA-IO/iSunFA#3685]
### Summary

[FEATURE] - 傳票清單的分頁功能

### Tasks

第一頁：
<img width="1469" alt="image" src="https://github.com/user-attachments/assets/911f57b9-c532-415b-8f7b-4f7427eb6c4a" />
第二頁：
<img width="1465" alt="image" src="https://github.com/user-attachments/assets/b8fa9bbb-ece2-4219-985c-d6c998c38879" />
api 回傳16筆資料，但是畫面上，兩個分頁的顯示資料相同～

**Comment by Julian0701** [comment]
- take 5 hrs, done
- 順便修正了借貸方的順序
