### ISSUE TITLE
🐛 [BUG] 會計分錄借和貸方金額少了千分位逗號

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3714]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/23 12:00

### OS

macOS

### Browsers

Chrome

### Reproduction URL

https://isunfa.com/users/select-company

### Reproduction steps

1. Go to '會計'
2. Click on '. 新增傳票'
3. Scroll down to '借方／貸方'

### Current Result

數字需要有千分位逗號

### Screenshots

![截圖 2024-12-20 下午2 59 32](https://github.com/user-attachments/assets/c610100c-65c5-4299-9dee-217ea111f6cb)

### Expected Result

數字需要有千分位逗號

**Comment by TzuHanLiang** [comment]
took 1hrs
done

**Comment by TzuHanLiang** [comment]
<img width="1358" alt="Screenshot 2024-12-26 at 3 39 12 PM" src="https://github.com/user-attachments/assets/e596d33a-7b8a-46c3-ae4e-3ae3cdd182d8" />
