### ISSUE TITLE
🐛 [BUG] - 開方環境中 公司建立的account還是會被其他公司看到

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#3716]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

2024/12/20

### Device

None

### OS

Linux

### Reproduction URL

https://isunfa.tw/users/setting/accounting_setting

### Reproduction steps

```markdown
1. 這個錯誤只會在 isunfa.tw 觸發，自己build的環境沒有
2. 創兩個公司，在A公司 的`https://isunfa.tw/users/setting/accounting_setting`頁面新增會計科目
3. 切換到B公司，`https://isunfa.tw/users/setting/accounting_setting`頁面會有相同科目
4. 推測原因是因為切換公司之後 accountAPI沒有刷新
```

### Current Result

```markdown
2. 創兩個公司，在A公司 的`https://isunfa.tw/users/setting/accounting_setting`頁面新增會計科目
3. 切換到B公司，`https://isunfa.tw/users/setting/accounting_setting`頁面會有相同科目
```

### Screenshots

![DESCRIPTION](LINK.png)

### Expected Result

```markdown
希望不要看到別的公司的account
```

**Comment by TinyMurky** [comment]
took 3 hours
發現問題是因為 進入accounting setting的時候沒有重call api

**Comment by Julian0701** [comment]
- take 1 hr, done
