### ISSUE TITLE
🐛 [BUG] - 憑證上傳列表 選擇發票類型 的排版問題

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3718]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/23 12:00

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

```markdown
1. Go to '會計'
2. Click on '憑證列表'
3. Scroll down to '發票類型'
4. See error
```

### Current Result

顯示兩行字 開頭有些看不到

### Screenshots

![截圖 2024-12-20 下午3 09 27](https://github.com/user-attachments/assets/2dd52cc8-6e7f-46d4-adbe-6c037fdadb29)

### Expected Result

顯示單行即可,從開頭的文字開始顯示超出範圍的字，以...顯示幾可

**Comment by TzuHanLiang** [comment]
took 1hrs
done

**Comment by TzuHanLiang** [comment]
https://github.com/user-attachments/assets/d553d642-a5b0-457d-a3e6-5f0a55bba85e
