### ISSUE TITLE
🐛 [BUG] -三大報表排版問題

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3722]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/23 12:00

### OS

macOS

### Browser Version

_No response

### Reproduction URL

https://isunfa.tw/users/setting/accounting_setting

### Reproduction steps

1. Go to '報表 '

### Current Result

報表跑版 報表標題列可以置中對齊

### Screenshots

![截圖 2024-12-20 下午4 17 39](https://github.com/user-attachments/assets/e3981359-f43b-481f-ac7c-db08ce84cf38)

![截圖 2024-12-20 下午4 13 39](https://github.com/user-attachments/assets/c27b136a-d2ed-4863-8f6a-b1e4d39d9a42)
![截圖 2024-12-20 下午4 09 48](https://github.com/user-attachments/assets/13bcadbb-2bdb-4e21-8998-e58b97a9e337)
![截圖 2024-12-20 下午4 05 44](https://github.com/user-attachments/assets/640b3503-ecbf-456a-bf4b-e547bc9c8471)
ogs

### Expected Result

報表沒有跑版 和標題列三種報表是一致

**Comment by jing12345678910** [comment]
第一個問題：表頭是否要置中？
根據設計稿，「代號」和「會計項目」應該是置左
<img width="697" alt="image" src="https://github.com/user-attachments/assets/7e93378e-185f-46c6-9c5a-154c5e238521" />
我將三張報表表頭都調整為一致（「代號」和「會計項目」應該是置左、「日期」和「百分比」置中）
資產負債表：

- [X] 項目匯總格式

- [X] 細項分類格式

損益表：
- [X] 項目匯總格式
- [X] 細項分類格式

現金流量表：
- [X] 項目匯總格式
- [X] 細項分類格式

**Comment by jing12345678910** [comment]
第二個問題：
現金流量表的表格直線有對齊了
<img width="1134" alt="image" src="https://github.com/user-attachments/assets/69693772-8ab6-440d-9c81-5d897f2b3f42" />

**Comment by jing12345678910** [comment]
took 2 hrs
done
