### ISSUE TITLE
🐛 [BUG] - 手機上傳的圖片 看不到圖片預覽

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3724]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/23 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

1. Go to '會計'
2. Click on '憑證列表'

### Current Result

手機上傳的發票，上傳成功，但圖片縮圖看不到

### Screenshots

![截圖 2024-12-20 下午4 34 08](https://github.com/user-attachments/assets/71cd3023-8586-47f4-ac87-c9772075ee1c)

### Expected Result

手機上傳的發票，上傳成功，可以看到圖片的縮圖

**Comment by TinyMurky** [comment]
# 後端方案：
- 後端在產生Room 的時候要產生Public key
- RoomList 要改成Singleton
- 多一個api, room/key 可以拿到 public key, delete room 的時候一起delete key

**Comment by TinyMurky** [comment]
took 5 hours

拿到public key 的 APIName: `APIName.ROOM_GET_PUBLIC_KEY_BY_ID`
這個api不用登入就可以用了

回傳的格式，payload整體就是 JsonWebKey，不用特別去取出中間的一段文字 (加到`formData`的時候還是用`JSON.stringfy()` 壓成string好了)
```json
{
  "powerby": "iSunFA v0.8.5+223",
  "success": true,
  "code": "200ISF0000",
  "message": "Success",
  "payload": {
    "key_ops": [
      "encrypt"
    ],
    "ext": true,
    "kty": "RSA",
    "n": "hkHfaJLKKcfrzn-unxAM1kCRScbmJ6Sj2yMKRgP-0i7CRy6Who3LyWa3Dbq_vW6z_bcJPAwJVm7h-j90tDDPbK9z04q2lBsNPTg8yncH8FVgT0ySWplTPUWQaX-3zLvLjeGU-7dEGqU2A6zuXLw5APQ1qcYHkM7K7IVM37qhVAn8GB7lNBjGgrUyCSjxHgzN8_BBNIdwJxVlixI57a3TyyudxJEyY__5gXEbhVCtYfe9kkYw83piZEAGVeJUZ6HNR09PFp4fe5HXTLSo4SU10ps1Z3X_QnPk0Y24zT1IqpMPvd9ZH4s26mYy86Qzh9qCFZDiV0BIQLZyUOoSEO_XmQ",
    "e": "AQAB",
    "alg": "RSA-OAEP-256"
  }
}
```

**Comment by TzuHanLiang** [comment]
took 2hr 修改前端

**Comment by TinyMurky** [comment]
創新company之後可以正常用手機上傳

**Comment by TzuHanLiang** [comment]
took1hrs
test
success
done
