### ISSUE TITLE
🐛 [BUG] 會計設定的主科目的icon 無法顯示

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3730]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/24 12:00

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/setting/accounting_setting

### Reproduction steps

1. Go to ' 參數設定 '
2. Click on '會計設定'

### Current Result

icon 無法顯示

### Screenshots

![Uploading 截圖 2024-12-24 下午1.38.29.png…]()

### Expected Result

icon 可以清楚顯示

**Comment by Julian0701** [comment]
- take 10 min, done
