### ISSUE TITLE
🐛 [BUG] - 貨幣選擇圖片故障

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3748]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/9 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/setting/accounting_setting

### Reproduction steps

1. Go to '...參數設定'
2. Click on '.貨幣設定'

### Current Result

看不到圖片 可以把歐元選項換成美金

### Screenshots

![截圖 2024-12-24 下午6 48 18](https://github.com/user-attachments/assets/ca0ccb6a-f9f7-4b79-9d54-111f73fff8bd)

### Expected Result

看不到圖片 可以把歐元選項換成美金

**Comment by Julian0701** [comment]
- take 1 hr, done
