### ISSUE TITLE
🐛 [BUG] - 上傳憑證編輯資訊少了刪除鍵

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3769]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/26 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

```markdown
1. Go to '會計'
2. Click on '上傳憑證'
3. Scroll down to '....'
4. See error
```

### Current Result

```markdown
憑證完成上傳上傳未轉成傳票的情況 
在編輯畫面 並未有刪除鍵
```

### Screenshots

![截圖 2024-12-25 下午5 23 27](https://github.com/user-attachments/assets/96d69ad5-af77-4256-b044-3eddfb439d85)
![截圖 2024-12-25 下午5 28 04](https://github.com/user-attachments/assets/317d1df3-7f69-4f19-84ba-74478159c1c3)

### Expected Result

```markdown
當未上傳傳票的情況 
在編輯畫面 並未有刪除鍵
```

**Comment by TzuHanLiang** [comment]
took1hrs
done

**Comment by TzuHanLiang** [comment]
<img width="1468" alt="Screenshot 2024-12-26 at 3 49 30 PM" src="https://github.com/user-attachments/assets/4cc1922e-09ce-4c36-af56-e8a600771f7d" />
