### ISSUE TITLE
🐛 [BUG] 新建交易夥伴之自創的公司，需完整顯示公司名稱和代碼

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3770]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/26 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

```markdown
1. Go to '會計'
2. Click on '憑證列表'
3. Scroll down to '....'
4. See error
```

### Current Result

```markdown
在上傳憑證資訊 新建客戶／供應商
自編代碼（統編）的公司 實際沒有在政府登記下的
自編代碼之公司 ，公司名稱顯示會不見

但憑證列表會出現，公司名稱而代碼不見
```

### Screenshots
![截圖 2024-12-26 上午10 44 04](https://github.com/user-attachments/assets/afb666f1-3095-4612-a1ac-234ae0ab8688)

大胃王拉麵 不是真的有這間公司 是我自創的 統編也是自編的
![截圖 2024-12-25 下午6 03 59](https://github.com/user-attachments/assets/ccbfd61c-e51c-416e-8e01-d2ca3bc1daf2)

![截圖 2024-12-25 下午5 03 33](https://github.com/user-attachments/assets/12cf4406-f2d6-4bb1-88f5-78cc8592d4cb)

### Expected Result

```markdown
希望代碼和公司名稱都可以清楚顯示
```

**Comment by TzuHanLiang** [comment]
took 1hrs
done

**Comment by TzuHanLiang** [comment]
https://github.com/user-attachments/assets/fe1f9170-4a22-483a-9a98-d4a2500c3f61
