### ISSUE TITLE
🐛 [BUG] - 上傳憑證未填發票編號 是不行的

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3780]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/26 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/certificate_list

### Reproduction steps

```markdown
1. Go to '會計'
2. Click on '上傳憑證 '
3. Scroll down to '....'
4. See error
```

### Current Result

```markdown
只要沒登打發票編號的憑證 
儲存會有出現異常
```

### Screenshots

Uploading 螢幕錄影 2024-12-26 下午5.00.12.mov…

### Expected Result

```markdown
只要沒登打發票編號的憑證 
儲存可正常
```

**Comment by TinyMurky** [comment]
- #3779

**Comment by TinyMurky** [comment]
took 0 hours
done
