### ISSUE TITLE
[Test]產品測試20241227

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#3788]
以張祐輔案例測試產品

**Comment by JodieWu** [comment]
<img width="309" alt="截圖 2024-12-27 下午1 34 50" src="https://github.com/user-attachments/assets/d5acec96-f23e-4f09-b27c-c7de948e3f97" />

時間無法點選

---

<img width="551" alt="截圖 2024-12-27 下午2 34 08" src="https://github.com/user-attachments/assets/63e85f66-48f4-48e5-bda5-fb3716df19c6" />

資料登打到一半突然被登出了，想了解自動登出的機制是什麼

---

<img width="1144" alt="截圖 2024-12-27 下午2 37 10" src="https://github.com/user-attachments/assets/21ffe4bd-4e88-440f-80b9-b16acffbc2db" />

這裡幫我把交易對象欄寬也改為100% (Fill) 自動填滿

---
<img width="1149" alt="截圖 2024-12-27 下午2 46 09" src="https://github.com/user-attachments/assets/e8a34718-8d09-4da6-93a4-4d5a33d4bb3e" />

日期與金額排序無法使用，且不應該存在兩個可同時選擇的狀態。

---

**Comment by godmmt** [comment]
新增事件的時間無法點選

已開單: https://github.com/CAFECA-IO/iSunFA/issues/3818

**Comment by Julian0701** [comment]
- #3830
- #3831

**Comment by godmmt** [comment]
資料登打到一半突然被登出了，想了解自動登出的機制是什麼

已開單: https://github.com/CAFECA-IO/iSunFA/issues/3842
