### ISSUE TITLE
🐛 [BUG] 傳票列表排版問題

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3812]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/27 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/voucher_list

### Reproduction steps

```markdown
1. Go to '會計'
2. Click on '傳票列表'
3. Scroll down to '....'
4. See error
```

### Current Result

```markdown
- 會計科目應是置左對齊
- 清單有交易對象，但新增傳票時沒有此欄位，需調整設計稿
- 清單標題列高度不對，設計稿為60px
- 清單個欄位寬度不對，請依設計稿
```

### Screenshots

<img width="1089" alt="截圖 2024-12-26 下午1 49 32" src="https://github.com/user-attachments/assets/ec13970b-9a49-49ed-bb5e-d35cffedc64b" />

### Expected Result

```markdown
- 會計科目應是置左對齊
- 清單有交易對象，但新增傳票時沒有此欄位，需調整設計稿
- 清單標題列高度不對，設計稿為60px
- 清單個欄位寬度不對，請依設計稿
```

**Comment by Julian0701** [comment]
- take 1 hr, done
