### ISSUE TITLE
🐛 [BUG] - 傳票詳細頁面資訊出現未翻譯

### ISSUE THREAD

**Issue by TeresaYang00** [CAFECA-IO/iSunFA#3813]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/27 12:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/10000064

### Reproduction steps

```markdown
1. Go to '會計'
2. Click on '傳票列表'
3. Scroll down to '傳票詳細資訊'
4. See error
```

### Current Result

```markdown
傳票詳細資料頁面，發票無法正常顯示，內容出現英文
```

### Screenshots

![截圖 2024-12-25 下午6 25 24](https://github.com/user-attachments/assets/ac1a0103-d7c4-4249-b27f-d0bc99423d65)

### Expected Result

```markdown
傳票詳細資料頁面，發票無法正常顯示，內容出現英文
```

**Comment by Julian0701** [comment]
- take 1 hr, done
