### ISSUE TITLE
[Test] 產品測試 20241230

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#3821]
依照張佑輔案例進行產品測試

**Comment by JodieWu** [comment]
<img width="570" alt="截圖 2024-12-30 上午11 42 23" src="https://github.com/user-attachments/assets/0ca71bd1-5b80-46f8-aa50-c2c0a0ffaff7" />

兩個數字顛倒了

---

https://github.com/user-attachments/assets/e3a488cb-2824-4fea-9336-6f62efb39492


https://github.com/user-attachments/assets/d8edea9a-26e8-462c-83cd-f0b5fccf3773


在新增或修改稅務資料後，保存都會出現錯誤提示
重新整理後資料有被正確保存

---

<img width="1143" alt="截圖 2024-12-30 上午11 54 07" src="https://github.com/user-attachments/assets/8449849a-3e69-4867-b505-c0e826a33d38" />

若沒有輸入發票號碼，但其他項目都填寫完成了，清單前方的警示符號不會消失，可是發票號碼為非必填資訊

---

<img width="1148" alt="截圖 2024-12-30 上午11 58 53" src="https://github.com/user-attachments/assets/05213af1-2681-4aba-9163-7c4b64872e5a" />

剛新增完稅務資料的憑證，在清單上不會顯示新增完的資料，前方警示也不會消失，很像填寫失敗，但重新整理後就會好

---

<img width="1089" alt="截圖 2024-12-30 下午12 08 58" src="https://github.com/user-attachments/assets/cc54e1e2-c0ca-4a34-9453-bc17ff106efb" />

傳票清單的預設排序，應該為傳票日期由近到遠。

---

**Comment by JodieWu** [comment]
完成時間： 8 hr

**Comment by Julian0701** [comment]
- [#3867](https://github.com/CAFECA-IO/iSunFA/issues/3867) 
- [#3868](https://github.com/CAFECA-IO/iSunFA/issues/3868) 
- [#3869](https://github.com/CAFECA-IO/iSunFA/issues/3869) 
- [#3870](https://github.com/CAFECA-IO/iSunFA/issues/3870)

**Comment by Julian0701** [comment]
> 此確認視窗應該是在按下確認新增傳票後出現。 資產與傳票需同時新增，所以在傳票還沒送出去之前，都不會新增任何資產，只是編輯資產資料

新增資產的流程是之前和 @arealclimber 討論過的，因為資產是綁在傳票之下，所以在這裡先將資產存入 DB 會比較方便後續操作
詳細討論結果[見此](https://github.com/CAFECA-IO/EventReport/blob/main/meeting/20241205_isunfa_create_assets.md)

**Comment by Julian0701** [comment]
> 最後一項應為傳票，不是憑證，且傳票號碼連過去的頁面是壞掉的

![image](https://github.com/user-attachments/assets/0b4115ef-35f7-4230-b5e8-adbe38ced433)
這邊是後端給的 voucher id 有誤，要請 @arealclimber 幫忙調整

**Comment by TeresaYang00** [comment]
> <img width="455" alt="截圖 2024-12-30 下午3 10 37" src="https://github.com/user-attachments/assets/08abfd30-a6fb-4d6d-a3b7-1f907b1ad667" />

- [x] 殘值無法為0

這個問題和 @jing12345678910 確認是可以的，故不開票

**Comment by arealclimber** [comment]
> > 最後一項應為傳票，不是憑證，且傳票號碼連過去的頁面是壞掉的
> 
> ![image](https://private-user-images.githubusercontent.com/114177573/399895313-0b4115ef-35f7-4230-b5e8-adbe38ced433.png) 這邊是後端給的 voucher id 有誤，要請 @arealclimber 幫忙調整

在 #3894 處理此錯誤
