### ISSUE TITLE
🐛 [BUG] - 已關聯傳票的發票還在可以被選擇的發票清單中

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#3827]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

12/27 11:00

### Device

None

### OS

macOS

### Reproduction URL

https://isunfa.tw/users/accounting/edit_voucher

### Reproduction steps

```markdown
[需要跟測試人員/設計師確認]
```

### Current Result

```markdown
- 已附在上一張其他傳票的發票，但還是顯示在可選擇清單中
```

### Screenshots

<img width="602" alt="截圖 2024-12-27 下午2 59 01" src="https://github.com/user-attachments/assets/9b18fcb0-8d92-4687-999c-eeecf12a93e2" />

此處「捐款」發票已附在上一張新建的傳票，但此處卻還是顯示在可選擇清單中

關聯 issue #3788

### Expected Result

```markdown
- 已附在上一張其他傳票的發票，不能顯示在可選擇清單中
```

**Comment by TinyMurky** [comment]
took 2 hours
done

**Comment by TzuHanLiang** [comment]
took 1hrs debug and asked backend to help
