### ISSUE TITLE
[Guide] Contract

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#434]
根據Mockup畫面與設計之使用者流程製作用戶指南。
可參考
Mockup
#95

**Comment by JodieWu** [comment]
完成時間： 3 hr

https://www.figma.com/file/f0mIyEYG1u0420d7m6otWT/iSunFA-User-Guide?type=design&node-id=5%3A10780&mode=design&t=qzmFr3aKqltjqeO1-1
