### ISSUE TITLE
[Guide] Project

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#435]
根據Mockup畫面與設計之使用者流程製作用戶指南。
可參考
Mockup
#97

**Comment by JodieWu** [comment]
完成時間： 7 hr

https://www.figma.com/file/f0mIyEYG1u0420d7m6otWT/iSunFA-User-Guide?type=design&node-id=3%3A557&mode=design&t=kXYvcH3QkFZ4lepU-1
