### ISSUE TITLE
[Guide] Report

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#436]
根據Mockup畫面與設計之使用者流程製作用戶指南。
可參考
Mockup
#99

**Comment by JodieWu** [comment]
完成時間： 2 hr

https://www.figma.com/file/f0mIyEYG1u0420d7m6otWT/iSunFA-User-Guide?type=design&node-id=5%3A10876&mode=design&t=qzmFr3aKqltjqeO1-1
