### ISSUE TITLE
[Guide] KYC

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#442]
根據Mockup畫面與設計之使用者流程製作用戶指南。
可參考
Mockup
#322

**Comment by JodieWu** [comment]
完成時間： 5 hr

https://www.figma.com/file/f0mIyEYG1u0420d7m6otWT/iSunFA-User-Guide?type=design&node-id=28%3A3200&mode=design&t=oN517MgvxyNbzmDc-1
