### ISSUE TITLE
串接 Mock API - 建立日記帳

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/iSunFA#515]
1. 上傳發票 -> [I010002](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getInvoice)
2. 解析日記帳 -> [O011002](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#ocrgetanalyzedresult)
3. 預覽 -> [V012001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#voucheruploadinvoices-isfmk00034), [V013002](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#vouchergetpreviewvoucherbyresultid--isfmk00034)

**Comment by Julian0701** [comment]
- take 3 hrs, remain 預覽
- [ ] [V012001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#voucheruploadinvoices-isfmk00034)
- [ ] [V013002](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#vouchergetpreviewvoucherbyresultid--isfmk00034)

**Comment by Julian0701** [comment]
- [x] **ISFMK00034** 上傳 invoice 圖片 [I010002](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#createInvoice)
- [ ] **ISFMK00050** 解析 invoice [I010001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getInvoice)
- [ ] **ISFMK00050** 上傳 voucher [V012001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#vouchergenerate-isfmk00034)
- [ ] **右邊那頁** 取得 voucher [V013002](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#vouchergetpreviewvoucherbyresultid--isfmk00034)
- [ ] **右邊那頁** 上傳 journal POST /company/:companyId/journal
- [ ] **ISFMK00024** 取得 journal GET /company/:companyId/journal
- [ ] **ISFMK00024** 取得 invoice 圖片 GET /company/:companyId/invoice/:id

**Comment by TzuHanLiang** [comment]
> * [ ]  **ISFMK00034** 上傳 invoice 圖片 [I010002](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#createInvoice)
> * [x]  **ISFMK00050** 解析 invoice [I010001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getInvoice)
> * [ ]  **ISFMK00050** 上傳 voucher [V012001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#vouchergenerate-isfmk00034)
> * [ ]  **右邊那頁** 取得 voucher [V013002](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#vouchergetpreviewvoucherbyresultid--isfmk00034)
> * [ ]  **右邊那頁** 上傳 journal POST /company/:companyId/journal
> * [x]  **ISFMK00024** 取得 journal GET /company/:companyId/journal
> * [x]  **ISFMK00024** 取得 invoice 圖片 GET /company/:companyId/invoice/:id

- ISFMK00024 取得 journal GET /company/:companyId/journal 這個 API 應該需要調整為 [J010003](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getProcessedJournalData)
- ISFMK00024 取得 invoice 圖片需要新增API @TinyMurky @gibbs-shih  並且文件是不是需要調整？
![Screenshot 2024-05-09 at 11 53 02 AM](https://github.com/CAFECA-IO/iSunFA/assets/17249354/ff047dc1-46b5-46dd-b758-096f6b8426a7)
  這個是不是應該有兩隻 API 一個拿 invoice 資料一個拿invoice image，目前這個路徑回傳的是 invoice資料跟文件不符，頁面已經
串接
     - @Julian0701  這個我沒有找到你在 ISFMK00024 的component 實作的位置

**Comment by Julian0701** [comment]
- done
