### ISSUE TITLE
[UX] Wireframe- Employees & Salary

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#58]
- [x] 薪資支出記帳
- [x] 薪資設定
- [x] 員工清單（顯示公司員工、薪資、參與專案等資訊）

**Comment by StrawHo** [comment]
LINK:
https://www.figma.com/file/rBgNsf93LVEhZ1xnS5uCnD/iSunFA-Wireframe?type=design&node-id=36%3A27569&mode=design&t=3mLKukgRwsrrcLKG-1
花費時間：約7hr
