### ISSUE TITLE
[UX] 流程校正

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#584]
從初始登入到新增公司、訂閱、KYC 之流程重新設計

新增管理員之流程重新設計

[MVP Meeting](https://github.com/CAFECA-IO/EventReport/blob/main/meeting/20240509_isunfa_mvp.md)

@StrawHo -4pts
@JodieWu  -4pts

**Comment by StrawHo** [comment]
提供使用者做試用產品的服務
![image](https://github.com/CAFECA-IO/iSunFA/assets/77717533/2da2571a-21e5-442d-ab05-42b4ecb59181)

新建公司團隊後產生對應彈窗
![image](https://github.com/CAFECA-IO/iSunFA/assets/77717533/aba41ee8-1e41-4b0f-8cbc-739fe09fae6f)

警示彈窗並且連結至KYC
![image](https://github.com/CAFECA-IO/iSunFA/assets/77717533/512ddb96-f9c3-483b-b5d1-4d1f92ee52dc)
