### ISSUE TITLE
[UX] Wireframe- Accounting

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#59]
- [x] 日記帳 一般 ERP 介面
- [x] 傳票檢視

**Comment by StrawHo** [comment]
LINK:
https://www.figma.com/file/rBgNsf93LVEhZ1xnS5uCnD/iSunFA-Wireframe?type=design&node-id=36%3A55820&mode=design&t=hBwuuq3XVTWJXcsr-1

花費時間：約7hr
