### ISSUE TITLE
📝 `Toast (successful)` RWD

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#606]
![Screenshot 2024-05-10 at 12 46 44](https://github.com/CAFECA-IO/iSunFA/assets/20677913/629519f5-ac15-4153-8b5a-3987b01d637e)

-----
ref: [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1254-210537&m=dev)

**Comment by Julian0701** [comment]
- take 2 hrs
