### ISSUE TITLE
📝 `MessageModal (duplicate registration & entity already exist)` RWD

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#607]
![Screenshot 2024-05-10 at 12 46 57](https://github.com/CAFECA-IO/iSunFA/assets/20677913/6d2ec3b0-735d-44ae-835b-36ede70611f5)
![Screenshot 2024-05-10 at 12 46 53](https://github.com/CAFECA-IO/iSunFA/assets/20677913/4658a796-9fbe-4ec2-bb04-843309977ffc)

-----
ref: [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1254-210537&m=dev)

**Comment by Julian0701** [comment]
- take 1 hr
- 調整排版
