### ISSUE TITLE
📝 Select-entity page (mobile & desktop)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#609]
- [x] mobile
- [x] desktop

![Screenshot 2024-05-10 at 12 47 22](https://github.com/CAFECA-IO/iSunFA/assets/20677913/33fef207-0ebb-4a42-ac8e-0219f47928fb)

-----
ref: [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1254-210537&m=dev)

**Comment by Julian0701** [comment]
- take 5 hrs
