### ISSUE TITLE
📝 `CreateEntityModal` (mobile & desktop)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#610]
- [x] UI
- [x] functionality

![Screenshot 2024-05-10 at 12 46 49](https://github.com/CAFECA-IO/iSunFA/assets/20677913/35939f1c-81e1-4890-b52b-7e828b408f56)

-----
ref: [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1254-210537&m=dev)

**Comment by Julian0701** [comment]
- remain 3 hrs

- [ ] create success (API)
- [ ] Add KYC page link
