### ISSUE TITLE
📝 Menu to select an entity on select-company page (mobile & desktop)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#611]
- [x] UI
- [x] functionality

![Screenshot 2024-05-10 at 12 54 45](https://github.com/CAFECA-IO/iSunFA/assets/20677913/55ff3616-5fba-48a2-a65d-f7b518b0f440)

-----
ref: [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1254-210537&m=dev)

**Comment by Julian0701** [comment]
- 已於 #669 完成，故轉 won't fix
