### ISSUE TITLE
📝 `EntityInvitationModal` (mobile & desktop)

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#612]
- [x] UI
- [x] functionality

![Screenshot 2024-05-10 at 12 46 47](https://github.com/CAFECA-IO/iSunFA/assets/20677913/34d81cb0-1adc-462d-a36d-01b00941e9f2)

-----
ref: [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1254-210537&m=dev)

**Comment by Julian0701** [comment]
- take 5 hrs, remain error handler

**Comment by Julian0701** [comment]
- take 2 hrs
- done
