### ISSUE TITLE
📝 選擇公司 串接API

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#614]
將選擇公司功能串上 API，參考 [API 文件](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#listcompanies)

-----
ref: [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1254-210537&m=dev)

**Comment by Julian0701** [comment]
- take 1 hr , remain 1 hr
- 完成 company list

**Comment by Julian0701** [comment]
- take 1 hr

<img width="680" alt="截圖 2024-05-20 下午5 35 08" src="https://github.com/CAFECA-IO/iSunFA/assets/114177573/c5241bf7-e318-4cfe-8de2-296c30ee613d">

- (尚未完成)無法寫入 header

**Comment by Julian0701** [comment]
#781 由 Emily 協助完成
