### ISSUE TITLE
📝 加入公司 串接API

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#615]
將加入現有公司功能串上 API，參考 [API 文件](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0)

-----
ref: [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1254-210537&m=dev)

**Comment by Julian0701** [comment]
- take 3 hrs
