### ISSUE TITLE
調整 DashboardBookmark 樣式

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#617]
- 樣式調整，並放到標題旁邊
![Screenshot 2024-05-10 at 13 54 23](https://github.com/CAFECA-IO/iSunFA/assets/20677913/0e2dc924-6b90-4028-8d45-b0fc30aed0f1)

-----
- ref: [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1254-210537&m=dev)｜[API - v1.0.0 doc](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0)

**Comment by Julian0701** [comment]
- take 4 hrs, remain 2 hrs
- 尚未完成左右移動的按鈕

![截圖 2024-05-21 下午5 27 14](https://github.com/CAFECA-IO/iSunFA/assets/114177573/9db8b501-5262-4890-aeb7-170271bdcd50)
