### ISSUE TITLE
company data in context

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#618]
- 有許多頁面會用到 company data，須參考 mockup 設計相關頁面會用共用的數據，然後放到 context 裡

-----
- ref: [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1254-210537&m=dev)｜[API - v1.0.0 doc](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0)

**Comment by Julian0701** [comment]
- take 3 hrs, remain 2 hrs
