### ISSUE TITLE
[UX] Enhancement- Accounting

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#656]
# Accounting

- 新增縮圖點開功能（附件上傳畫面）
- 填寫事件表格需增加附件檢視區域及新增更多附件的功能

**Comment by StrawHo** [comment]
### 新增事件Description 製作可輸入多筆關鍵句的畫面:
使用流程為輸入描述後送出會顯示在Event list，使用者可以繼續輸入新的描述或是點擊List 中的描述開始建立傳票。
LINK:
https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=2156%3A148917&t=GCF4vq4IxEvufYeL-1

### 新增縮圖點開功能(附件上傳畫面):
在文件名稱後面新增view icon點擊後出現完整圖片彈窗。
![image](https://github.com/CAFECA-IO/iSunFA/assets/77717533/b57177eb-650a-459d-b43b-5cf15e5c3f4e)
![image](https://github.com/CAFECA-IO/iSunFA/assets/77717533/f5e4469f-55da-40d0-9f6f-1870eaca5ca7)

### 填寫事件表格需增加附件檢視區域~及新增更多附件的功能~
![image](https://github.com/CAFECA-IO/iSunFA/assets/77717533/ff09b901-d46c-4c8c-9bc5-a4fb39d1709d)

**Comment by JodieWu** [comment]
完成時間： 3 hr
https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=605%3A909664&t=JLVFFKFATMFce2je-1
