### ISSUE TITLE
評估 API 串接完成的時間

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#660]
- 列出所有需要串接的 API 已經目前的進度
   - 設計稿
   - UI
   - backend

**Comment by TzuHanLiang** [comment]
- 要加入 Julian 新增的畫面
   - 列出用戶的公司清單
   - 新增用戶公司

**Comment by TzuHanLiang** [comment]
- Login/Register: ISFMK00001
    - set User name
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
- Welcome: ISFMK00004
    - list entities
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api    
    - create entity
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api   
    - add entity invitation code
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
    - upload profile picture
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
- Add New Journal(step1: upload): ISFMK00019/ISFMK00046
    - list upload files progress (percentage ?)
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
    - use user phone as scanner: uploadInvoice (certificate?)
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
- Add New Journal(step2: fill up form): ISFMK00052
    - voucherGenerate
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
    - 彈出視窗(step3: confirm): uploadJournal
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
- Baifa Journal List: ISFMK00038/ISFMK00018
    - listJournals
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
    - edit
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
    - delete event?
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
- View Journal: ISFMK00015
    - getJournalDetail
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
- My Report: ISFMK00065/ISFMK00066
    - listPendingReports
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
    - listReports
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
- Financial Report: ISFMK00029
    - generateFinancialReport
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api
- [Balance Sheet]: ISFMK00022
    - getReport
        - [x] design
        - [ ] ui
        - [ ] backend api
        - [ ] frontend api

**Comment by TzuHanLiang** [comment]
### 用於追蹤未完成的 API
需要實作的 API 要額外開票
- took 5hrs
- done

**Comment by TzuHanLiang** [comment]
- took 2.5hr
- 確認並更新

**Comment by RexBearIU** [comment]
getUser api response已補上wiki
list entity與create entity已補上 [#630](https://github.com/CAFECA-IO/iSunFA/issues/630) ，wiki文件待補
upload profile picture，已補上wiki

**Comment by TinyMurky** [comment]
invoice 更新，並補上wiki
- #589

**Comment by gibbs-shih** [comment]
分支 Feature/progress comparison api => 等待 merge 中, 可先參考程式碼
Dashboard: ISFMK00002/ISFMK00006

- overview：8
  - 應該下面3支就可以了


- profit status: 9
  - [P030001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getPeriodProfit) - GET /company/:companyId/profit - ISFMK00006

- income/expense: 10
  - [P030001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getPeriodProfit) - GET /company/:companyId/profit - ISFMK00006
 
- project progress: 11
  - [P050001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getProjectProgress) - GET /company/:companyId/project_progress - ISFMK00006 右上角
  - 分支 Feature/progress comparison api 
 
- project ROI comparison: 12
  - [P040001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getProfitComparison) - GET /company/:companyId/profit_comparison - ISFMK00006 右下角
  - 分支 Feature/progress comparison api

**Comment by Julian0701** [comment]
- 已完成
  - list entities 的 UI #669 
  - create entity 的 UI #610 
  - add entity by invitation code 的 UI #612 

- 部分完成
- list entities 的 API 串接 #614 
- create entity 的 API 串接 #613

**Comment by RexBearIU** [comment]
list entity與create entity 文件已補上
add entity by invitation code: 已完成mock，還未連接上sign in sign up ，文件待捕

**Comment by TzuHanLiang** [comment]
> list entity與create entity 文件已補上 add entity by invitation code: 已完成mock，還未連接上sign in sign up ，文件待捕

(https://github.com/CAFECA-IO/iSunFA/issues/684#issuecomment-2111599153)

https://github.com/CAFECA-IO/iSunFA/issues/693
https://github.com/CAFECA-IO/iSunFA/issues/694

**Comment by TzuHanLiang** [comment]
- [w20 清點](https://github.com/CAFECA-IO/iSunFA/issues/681#issuecomment-2117100599)

**Comment by TinyMurky** [comment]
按照下圖新增 `POST /ocr`，並且完成wiki [createOCRAnalyzingProcess](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#createocranalyzingprocess)

這個是原本的post invoice, post invoice之後會更改成用來 upload `ISFMK00052`的 data

![](https://storage.googleapis.com/mermer-offical-km/km/journal%E6%B5%81%E7%A8%8B0520.excalidraw.svg)

**Comment by TinyMurky** [comment]
按照下圖新增 `GET /unprocess_journal`，並且完成wiki [getUnprocessJournal](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getunprocessjournal)

符合畫面`ISFMK00019`的 journal，會把所有該company的 還沒用在invoice的 journal都拉出來

我的票：
- [x] #773 
PR
- [x] #803 

![](https://storage.googleapis.com/mermer-offical-km/km/journal%E6%B5%81%E7%A8%8B0520.excalidraw.svg)

**Comment by TinyMurky** [comment]
按照下圖新增 `get /OCR/:resultId`, `Post /Invoice`，並且完成wiki:
- [getOCRResult](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getOCRResult)
- [createInvoice](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#createInvoice)

我的票：
- [x] #774 
- [x] #775
PR
- [x] #822  

![](https://storage.googleapis.com/mermer-offical-km/km/journal%E6%B5%81%E7%A8%8B0520.excalidraw.svg)

**Comment by TinyMurky** [comment]
按照下圖新增 `GET  /ask_ai/:resultId/status`, `GET /ask_ai/:resultId`，並且完成wiki:
- [askAiStatus](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#askaistatus)
- [askAiResult](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#askAiResult)

這個其實就是 `voucher/:voucherId` 和 `voucher/:voucherId/status`，但是為了讓他比較泛用才整合，需要在query的地方加上`?aiApi=vouchers`才會get voucher 

我的票：
- [x] #827 
- [x] #828 
PR
- [x] #829  

![](https://storage.googleapis.com/mermer-offical-km/km/journal%E6%B5%81%E7%A8%8B0520.excalidraw.svg)

**Comment by TzuHanLiang** [comment]
- #845
