### ISSUE TITLE
API 需求(文件修改)： postAnInvoice 用在 ISFMK00052

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#722]
## 修改建議
將 getAnInvoice 的 Response payload type 改成 IInvoice

### 文件位置
- [API: getAnInvoice](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getAnInvoice)

### 需調整的部份
<img width="975" alt="Screenshot 2024-05-17 at 11 35 42 AM" src="https://github.com/CAFECA-IO/iSunFA/assets/17249354/a28a5b44-2492-4004-ba96-52b8e1ecfb63">

### 對應的畫面
<img width="567" alt="Screenshot 2024-05-17 at 11 37 28 AM" src="https://github.com/CAFECA-IO/iSunFA/assets/17249354/1cbfda90-2382-4a5b-921d-07c9c2af074b">

#### 附註
- 如果認為原本的格式更好，可以就不修改在下面列出原因，然後大家可以討論

**Comment by TinyMurky** [comment]
took 2 hours
done
