### ISSUE TITLE
API 需求(修改現有的 mock api 含測試)： getAnInvoice 用在 ISFMK00052

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#724]
## 修改建議
將 getAnInvoice 的 Response payload type 改成 IInvoice

### 程式碼位置
`src/pages/api/v1/company/\[companyId\]/invoice/\[invoiceId\]/index.ts`

### 需調整的部份
- 5/17 pull 的 develop[9e3fa53]
<img width="735" alt="Screenshot 2024-05-17 at 12 08 03 PM" src="https://github.com/CAFECA-IO/iSunFA/assets/17249354/53d4db99-2021-4af7-9806-bb50c173cd99">

### 對應的畫面
<img width="567" alt="Screenshot 2024-05-17 at 11 37 28 AM" src="https://github.com/CAFECA-IO/iSunFA/assets/17249354/1cbfda90-2382-4a5b-921d-07c9c2af074b">

### 前端實作位置
`src/components/new_journal_form/new_journal_form.tsx `

#### 附註
- 如果認為原本的格式更好，可以就不修改在下面列出原因，然後大家可以討論

**Comment by TinyMurky** [comment]
目前修改成只會回轉單一宜個invoice
```typescript
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<IResponseData<IInvoice>>
) {
  try {
    const { invoiceId } = req.query;
    // Info Murky (20240416): Check if invoiceId is string
    if (Array.isArray(invoiceId) || !invoiceId || typeof invoiceId !== 'string') {
      throw new Error(STATUS_MESSAGE.INVALID_INPUT_PARAMETER);
    }
```
