### ISSUE TITLE
API 需求(文件修改)：uploadJournal 用在 ISFMK00052 upload 按鈕

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#725]
## 修改建議
以 5/17 pull 的 [develop](https://github.com/CAFECA-IO/iSunFA/commit/9e3fa5388cfb35d5a24893bd1aa8d0d31721bb23) 參考
#### 目前前端命名
`VOUCHER_GENERATE`
#### 期望命名
`JOURNAL_GENERATE`
#### 目前串接的路徑
`/company/:companyId/voucher`
#### 期望路徑
`/company/:companyId/journal`
#### 目前interface
`IInvoice[]`
#### 期望interface
`IJournal` 
id: 可以前端先產生隨機的 id，後端回傳的時候在更正成實際 id
invoiceId: 需要為 string | undefined
### api response
`IAccountResultStatus`
不用調整

### API文件位置
- [API: createAVoucher](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#createAVoucher )
    - body 跟 code 不一致
### API文件調整
- [ ] 命名、路徑、body、response 與 #726 實作的結果保持一致

### 對應的畫面
<img width="567" alt="Screenshot 2024-05-17 at 11 37 28 AM" src="https://github.com/CAFECA-IO/iSunFA/assets/17249354/1cbfda90-2382-4a5b-921d-07c9c2af074b">

#### 附註
- 如果認為原本的格式更好，可以就不修改在下面列出原因，然後大家可以討論

**Comment by TinyMurky** [comment]
後來改成在POST invoice的時候 generate journal所以暫時不修
