### ISSUE TITLE
API 需求(文件新增):  get /OCR progress status 用在 ISFMK00052 

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#727]
### api 路徑
`/company/:companyId/ocr`
取得所有 unprocess 的ocr

### api response
`IAccountResultStatus`

### 文件位置
- [ ] 新增

### 對應的畫面
<img width="567" alt="Screenshot 2024-05-17 at 11 37 28 AM" src="https://github.com/CAFECA-IO/iSunFA/assets/17249354/1cbfda90-2382-4a5b-921d-07c9c2af074b">

**Comment by TinyMurky** [comment]
took 2 hours
done
