### ISSUE TITLE
API 需求(修改現有的 mock api 含測試)：voucherGenerate 用在 ISFMK00052 右邊彈出的 modal

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#730]
## 修改建議
以 5/17 pull 的 develop[https://github.com/CAFECA-IO/iSunFA/commit/9e3fa5388cfb35d5a24893bd1aa8d0d31721bb23] 參考
#### 目前前端使用
 - function name：getVoucherStatus
 - APIName：`VOUCHER_GET_PROGRESS_STATUS`
#### 期望使用
 - function name：getJouranlStatus
 - APIName：`JOURNAL_GET_PROGRESS_STATUS`
#### 目前串接的路徑
`/company/:companyId/voucher/:voucherId/status`
#### 期望路徑
`/company/:companyId/journal/:journalId/status`

#### 目前interface
`IVoucher`
#### 期望interface
`jouranlId`  & `ILineItem[]`, ILineItem 可能可以改名成 IAccountingVoucher

#### 目前
`IJournal`

#### 期望
`ProgressStatus`

### API文件位置
- [API: createAJournal](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#createajournal)

### 對應的畫面
<img width="567" alt="Screenshot 2024-05-17 at 11 37 28 AM" src="https://github.com/CAFECA-IO/iSunFA/assets/17249354/1cbfda90-2382-4a5b-921d-07c9c2af074b">

#### 附註
- 如果認為原本的格式更好，可以就不修改在下面列出原因，然後大家可以討論

**Comment by TinyMurky** [comment]
目前改成ask_ai，暫時不修
