### ISSUE TITLE
[UI Design 調整需求] Dashboard 圖表調整

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#735]
<img width="1003" alt="Screenshot 2024-05-17 at 4 19 42 PM" src="https://github.com/CAFECA-IO/iSunFA/assets/17249354/13f52ca7-b5b1-46bf-b22d-d97c8dfca037">

- 左上角的 `Profit Status Trend Chart` 是不是可以整合進左下角的 `Project Financial Overview (Income vs. Expenditure)` 都是用百分比呈現
- 左上角的圖票改成獲利的絕對值呈現

**Comment by JodieWu** [comment]
完成時間： 3 hr

https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1109%3A136549&t=KtifBoNplRoOdFQB-1
