### ISSUE TITLE
調整 Dashboard: ISFMK00006 5支 api

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/iSunFA#736]
# 針對修改檢查  by Emily
- 這邊的 API 不完全符合需求，需要再調整，具體調整方向會在這邊逐一列出

### overview：8
是需要單獨的一隻API，提供下列圖票用到的值
<img width="675" alt="Screenshot 2024-05-17 at 2 58 54 PM" src="https://github.com/CAFECA-IO/iSunFA/assets/17249354/74476813-cb3c-4c14-b845-a9d5082fad5e">

### profit status: 9 & income/expense: 10 會合併
[API: P030001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getPeriodProfit) 
1. reposnse 的資料格式盡量不要用 data[] ，比較好的作法是幫忙定義 interface
2. 回傳範例的回傳值需要幫忙微調，需要的是`百分比`而不是`絕對值`，可以用 decimal 含精確到小數點後兩位或是 `[integer]%` 的形式表示，範例也要調整
```
 [
        {
            "date": "2024-03-01",
            "income": 70000,  --> 需要百分比
            "expenses": 50000,
            "profit": 20000
        },
]
```

### 原本的 profit status: 9 改成 profit trend
- 這裡需要回傳的格式同現在這個版本的這隻API [P030001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getPeriodProfit) - GET /company/:companyId/profit - ISFMK00006 
- 需要額外寫這個 API 文件
 
### project progress: 11
[P050001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getProjectProgress) 回傳調整：
| 名稱       | 類型     | 描述                      |
|------------|----------|---------------------------|
| progress   | string   | 進度狀態                 |
| ~project~    | ~string[]~ | ~以陣列形式存放的專案名稱~ |
| projectNum   | integer   | 專案數量                 |
 
### project ROI comparison: 12
[P040001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getProfitComparison) 回傳調整，範例也要調整
| 名稱          | 類型     | 描述                            |
|--------------|----------|---------------------------------|
| name         | string   | 專案名稱                        |
| profit       | ~Profit[]~ Profit | 期間內的利潤資訊（~Profit[]~ Profit）    |

**Comment by gibbs-shih** [comment]
- 新增 overview api: profitInsight
  - [ ] api 文件
  - [ ] mock api
  - [ ] test
 
- 修改  [P040001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getProfitComparison) profit_comparison
    - [ ] api 文件
    - [ ] mock api
    - [ ] test

名稱 | 類型 | 描述
-- | -- | --
name | string | 專案名稱
profit |  Profit | 期間內的利潤資訊（Profit）

```
{
...
payload: {
    startDate: "2024-04-01 ",
    endDate: "2024-05-01 ",
    comparisons: [
        {
            projectName: "iSunFa",
            income: 70000,
            expenses: 50000,
            profit: 20000,
        },
        ....
    ]
```
- 修改  [P050001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getProjectProgress) project_progress
    - [ ] api 文件
    - [ ] mock api
    - [ ] test
 
名稱 | 類型 | 描述
-- | -- | --
progress | string | 進度狀態
projectNum | integer | 專案數量

- 修改 [P030001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getPeriodProfit) profit
    - [ ] api 文件
    - [ ] mock api
    - [ ] test
  1. 改名 profit_trend 
  2. reposnse 的資料格式定義 interface
  3. 回傳需要的是百分比，可以用 decimal 含精確到小數點後兩位或是 [integer]% 的形式表示
``` 
[
        {
            "date": "2024-03-01",
            "income": 70000,  --> 需要百分比
            "expenses": 50000, --> 需要百分比
            "profit": 20000 --> 需要百分比
        },
]
``` 

- 新增 api: profit_value, 同原本 P030001, 但回傳值是數字
    - [ ] api 文件
    - [ ] mock api
    - [ ] test

**Comment by gibbs-shih** [comment]
take 4 hr

**Comment by TzuHanLiang** [comment]
- [P040001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getProfitComparison) profit_comparison
    - 前端定義的回傳 interface: IProjectROIComparisonChartData
- [P050001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getProjectProgress) project_progress   
    - 前端定義的回傳 interface: IProjectProgressChartData
- 這個是 income、expense、profit 會由你整合，介面參考就好
    - 前端定義的回傳 interface: IProfitTrendChartData
    - 前端定義的回傳 interface: IIncomeExpenseTrendChartData

**Comment by gibbs-shih** [comment]
- 修改 profit_insight interface 名稱與畫面一致
  - mock api
  - api 文件 

![CleanShot 2024-05-21 at 13 40 13](https://github.com/CAFECA-IO/iSunFA/assets/73210852/fd054601-c41c-482e-8c19-bd6c2816ec67)

**Comment by gibbs-shih** [comment]
- [P050001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getProjectProgress) project_progress
  - 修改使用 interface: IProjectProgressChartData
  - mock api,  使用 interface 裡的 function
  - test api
  - api 文件

<img width="604" alt="CleanShot 2024-05-21 at 15 52 48@2x" src="https://github.com/CAFECA-IO/iSunFA/assets/73210852/0eab6008-f7cd-453a-b284-2a542a02e20d">

**Comment by gibbs-shih** [comment]
todo:
income、expense、profit api 合併待與前端討論
新增 hr cost api

take another 4 hr
