### ISSUE TITLE
[UI] Module 通用系列

### ISSUE THREAD

**Issue by StrawHo** [CAFECA-IO/iSunFA#79]
通用模組：

- [x] 上方導覽列(header)：訪客模式、登入後模式
- [x] 左側功能選單(Menu)：目前有六種功能選單類型
- [x] 置底(footer)
- [x] 可輸入彈窗(input)：目前輸入彈窗依照不同類型由文字輸入(有無按鈕)、下拉選單、 單選選項、切換按鈕
- [x] 選項彈窗(confirm)：目前有二次確認以及完成確認兩種選項彈窗。
- [x] 篩選列模組(Filter bar)：目前篩選列包含狀態、排序、時間區間、搜尋、顯示方式，依照以上內容做變數。
- [x] 上傳附件模組(Upload)
- [x] 附件彈窗(file popup)：附件包含傳票、憑證等，多為圖片顯示。

**Comment by JodieWu** [comment]
部分完成： 2 hr

https://www.figma.com/file/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?type=design&node-id=4%3A337&mode=design&t=BEwhHesT54PzmaMV-1

**Comment by JodieWu** [comment]
部分完成： 2 hr

https://www.figma.com/file/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?type=design&node-id=89%3A67087&mode=design&t=EJI413MnD98mvmNZ-1
