### ISSUE TITLE
[Bug] landing page display issue with Safari

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/iSunFA#796]
- Test Environment
```
2024-05-21 19:39:19
iMac Pro
MacOS 14.5
Safari 17.5（19618.2.12.11.6）
```

- How To Reproduce
```
access https://www.isunfa.com/en#about with safari
```

- Exception Description
```
There are a lot of abnormal green gradient elements.
```

- Expect Result
```
Expect to be consistent with the Mockup
https://www.figma.com/design/4PS1QfFhlwIrJ5WwyDcWws/iSunFA-Landing-page?node-id=79-260&t=XmLDyR0oEBGXaYUM-0
```

- Refference
<img width="1247" alt="snapshot" src="https://github.com/CAFECA-IO/iSunFA/assets/270062/a307d75a-c2f0-4b61-9d55-a9b9131c5244">

**Comment by godmmt** [comment]
Safari does not support syntax `mix-blend-screen`.

mix-blend-screen is a CSS property:
`mix-blend-mode: screen;`

[See more about mix-blend-mode](https://drafts.fxtf.org/compositing/#mix-blend-mode)
### References

https://caniuse.com/?search=%20%20%20%20mix-blend-mode

<img width="1368" alt="截圖 2024-05-22 上午11 57 42" src="https://github.com/CAFECA-IO/iSunFA/assets/105651918/1d354320-8057-486c-bbf2-ce799936992d">

**Comment by godmmt** [comment]
找到問題點。如果要改的話，需要另外開單、使用的背景圖片可能要重新設計。

**Comment by godmmt** [comment]
took 2 hours

done.

**Comment by Luphia** [comment]
- still there

**Comment by arealclimber** [comment]
problem: Safari 常常會出現綠色圓圈
cause: Safari 不支援 blend mode
solution: 隱藏用 blend mode 顯示的異常 svg

**Comment by arealclimber** [comment]
https://github.com/user-attachments/assets/2f9ccf47-03ec-4dde-8327-2d457d8cfdf8

**Comment by arealclimber** [comment]
took 2 hrs
done
