### ISSUE TITLE
[Document] 用戶指南補充資訊與內容調整

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/iSunFA#799]
- [x] 缺少目錄&最後頁 - 1 pt
- [x] 章節順序需調整與用戶實際操作流程相同（訂閱與設定帳號置於最後章節） - 1 pt
- [x] 各章節應補充一段功能簡述 EX: Login ... 登入系統採用 FIDO2 登入機制 ... 帶來 xxx 好處 ...  - 2 pt
- [x] 需要補充Accounting章節 AI Accounting，描述如何操作以 AI 技術優化記帳流程 - 2 pt
- [x] 需要補充Report章節 AI Auditing，描述如何操作以 AI 技術實現持續審計，產生會計報表與審計報告 - 2 pt
- [x] 序 新增

**Comment by StrawHo** [comment]
目前完成內容為前三部分，剩餘部分待後續確認功能章節內容文字後新增。
LINK:
https://www.figma.com/design/f0mIyEYG1u0420d7m6otWT/iSunFA-User-Guide?node-id=1%3A6533&t=ViWdmFVMQ9o41z5w-1

花費時間約4hr20min

**Comment by StrawHo** [comment]
### 各章節補充功能簡述維以下內容：

- 登入系統採用FIDO2登入機制，無需設定帳號密碼，快速登入更方便、使用裝置登入更安全。
- Dashboard匯集公司近期財務評估、專案進度，迅速瞭解公司資訊，掌握人力與工作分配。
- iSunFA提供專業KYC認證，審核用戶資料並確保公司所有人權益。
- iSunFA會計功能，支援手機掃描憑證快速上傳，提高會計管理效率。帶給使用者更快速、方便的憑證處理流程，並確保資料準確性，讓他們能夠更專注於核心業務。
- 資產新增功能，能夠快速一鍵新增資產並記錄詳細資訊，簡化資產管理流程。提供公司資產管理更加方便、透明，有效地跟蹤和管理公司的各項資產，以最佳化運作和提升生產力。
- iSunFA的報告功能憑借 AI 技術持續審計並自動產生報表，提供準確的財務報告。可以讓使用者更輕鬆地掌握公司財務狀況，快速作出明智的商業決策，並節省大量時間和人力成本於財務管理的執行上。
- 在iSUNFA的專案管理系統能夠實時跟蹤專案進度並結合智能記賬，協助團隊高效管理專案，使用者能更有效地掌握專案進展情況，及時調整策略以確保專案按時完成並達到目標，提升整體工作效率和團隊協作能力。
- iSunFA將合約與專案關聯並提供合約進度檢視功能，用戶可以更輕鬆地跟蹤合約執行情況與專案進度，有助於及時識別可能的風險和機遇，提高管理效率並確保合約和專案的順利完成。
- 在iSunFA的薪資功能中，能夠支援員工工作時數記錄和薪資開立，提高薪資管理效率。幫助用戶更準確地記錄員工工時，自動計算薪資並生成薪資報表，簡化了薪資處理流程，讓管理人員能夠更專注於戰略性工作，同時確保員工薪資準確無誤，提升了整體的人力資源管理效率。

**Comment by StrawHo** [comment]
LINK:
https://www.figma.com/design/f0mIyEYG1u0420d7m6otWT/iSunFA-User-Guide?node-id=1-6533&t=dcDWcq9YD1Ta8cN9-1

完成時間共花費約7hr 30min

**Comment by StrawHo** [comment]
檔案下載連結:
https://drive.google.com/file/d/1dMy3B1c_jcoghdbsGEGmt3npODYODE0Z/view?usp=sharing
