### ISSUE TITLE
根據後端更新的 Add New Journal 相關 interface 調整前端

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#885]
- 在 PR #867 之後有請 murky 幫忙調整相關的 interface

**Comment by Julian0701** [comment]
- take 4 hrs, remind 1 hr
- [ ] Error handling 
- [ ] 檢查 lineItems 沒寫入資料的原因

**Comment by Julian0701** [comment]
- take 5 hrs
