### ISSUE TITLE
Adjust the bottom toast to not cover the menu of mobile layout

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#953]
- generating toast 顯示在桌面版的右下方，但是在行動版時顯示在網頁下方，會擋到底下的 app menu

![CleanShot 2024-07-26 at 10 18 56](https://github.com/user-attachments/assets/6112601f-6e34-4b63-b9ac-f0d2e1943e5b)

**Comment by godmmt** [comment]
took 3 hours

done.

**Comment by godmmt** [comment]
took 3.5 hours

done.

**Comment by godmmt** [comment]
took 4 hours

done.
